AIB
NAME
AIB -
SYNOPSIS
#include <AIB.h>
Inherits BANK.
Public Member Functions
AIB ()
AIB (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)
AIB (std::shared_ptr< BANK > obj, int _version, int _unique_id)
AIB (const AIB &orig)
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual int GetAccountNumber () const
GetAccountNumber getter for accountNumber private field.
virtual std::string GetAddress () const
GetAddress getter for address private field.
virtual double GetBalance () const
GetBalance getter for balance private field.
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
virtual std::string GetFirstName () const
GetFirstName getter for firstName private field.
virtual std::string GetFullname () const
GetFullname getter for fullname private field.
virtual std::string GetLastName () const
GetLastName getter for lastName private field.
AIB operator= (const AIB &orig)
virtual void SetAccountNumber (int accountNumber)
SetAccountNumber setter for accountNumber private field.
virtual void SetAddress (std::string address)
SetAddress setter for address private field.
virtual void SetBalance (double balance)
SetBalance setter for balance private field.
virtual void SetFirstName (std::string firstName)
SetFirstName setter for firstName private field.
virtual void SetFullname (std::string fullname)
SetFullname setter for fullname private field.
virtual void SetLastName (std::string lastName)
SetLastName setter for lastName private field.
virtual void toString ()
toString function, displays the object values in formatted way
virtual ~AIB ()
Private Attributes
int accountNumber
std::string address
double balance
std::string firstName
std::string fullname
std::string lastName
Detailed Description
Class AIB Inherit from BANK class
Definition at line 23 of file AIB.h.
Constructor & Destructor Documentation
AIB::AIB () [inline]
Constructor
Definition at line 28 of file AIB.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
Referenced by AIB(), and getBaseCopy().
         : BANK()
    {
        this->accountNumber = 0;
        this->balance = 50;
        this->firstName = "Joe";
        this->lastName = "Blog";
        this->address = "High street, Carlow";
        this->fullname = firstName + " " + lastName;
    
    };
AIB::AIB (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address) [inline]
Custom constructor
Parameters:
accountNumber integer
balance double
firstName string
lastName string
address string
Definition at line 46 of file AIB.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
                                                                                                      : BANK()
    {
        this->accountNumber = accountNumber;
        this->balance = balance;
        this->firstName = firstName;
        this->lastName = lastName;
        this->address = address;
        this->fullname = firstName + " " + lastName;
    };
AIB::AIB (std::shared_ptr< BANK > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Parameters:
obj std::shared_ptr<BANK>
_version integer
_unique_id integer
Definition at line 61 of file AIB.h.
References accountNumber, address, AIB(), balance, firstName, fullname, and lastName.
                                                              : BANK(_version, _unique_id)
    {
        this->accountNumber = obj->GetAccountNumber();
        this->balance = obj->GetBalance();
        this->firstName = obj->GetFirstName();
        this->lastName = obj->GetLastName();
        this->address = obj->GetAddress();
        this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
        
    };
AIB::AIB (const AIB & orig)
Copy constructor
AIB::~AIB () [virtual]
de-constructor
Definition at line 19 of file AIB.cpp.
Referenced by operator=().
          {
}
Member Function Documentation
void AIB::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer Implement OSTM virtual methods in cpp class
Parameters:
to std::shared_ptr<OSTM>, BANK type shared pointer used to copy into the values
from std::shared_ptr<OSTM>, BANK type shared ponter used to get object values tfrom copy
Dynamic cast from OSTM to AIB
Dynamic cast from OSTM to AIB
Set values fro object to object
Set values fro object to object
Set values fro object to object
Set values fro object to object
Reimplemented from OSTM.
Definition at line 41 of file AIB.cpp.
References OSTM::Set_Unique_ID().
Referenced by operator=().
                                                              {
    std::shared_ptr<AIB> objTO = std::dynamic_pointer_cast<AIB>(to);
    std::shared_ptr<AIB> objFROM = std::dynamic_pointer_cast<AIB>(from);
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    objTO->SetAccountNumber(objFROM->GetAccountNumber());
    objTO->SetBalance(objFROM->GetBalance());
}
int AIB::GetAccountNumber () const [virtual]
GetAccountNumber getter for accountNumber private field.
Reimplemented from BANK.
Definition at line 96 of file AIB.cpp.
References accountNumber.
Referenced by operator=(), and toString().
                                {
    return accountNumber;
}
std::string AIB::GetAddress () const [virtual]
GetAddress getter for address private field.
Reimplemented from BANK.
Definition at line 72 of file AIB.cpp.
References address.
Referenced by operator=().
                                {
    return address;
}
double AIB::GetBalance () const [virtual]
GetBalance getter for balance private field.
Reimplemented from BANK.
Definition at line 84 of file AIB.cpp.
References balance.
Referenced by operator=(), and toString().
                             {
    return balance;
}
std::shared_ptr< OSTM > AIB::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
Parameters:
object is a OSTM type shared pointer use to create a new copy of the pointer
Dynamic cast from OSTM to BANK type
BANK type Instance creation shared pointer
Dynamic cast from BANK to OSTM type
Return new OSTM copy onject
Reimplemented from OSTM.
Definition at line 25 of file AIB.cpp.
References AIB().
Referenced by operator=().
{
    std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
    std::shared_ptr<BANK> obj(new AIB(objTO, object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
std::string AIB::GetFirstName () const [virtual]
GetFirstName getter for firstName private field.
Reimplemented from BANK.
Definition at line 120 of file AIB.cpp.
References firstName.
Referenced by operator=(), and toString().
                                  {
    return firstName;
}
std::string AIB::GetFullname () const [virtual]
GetFullname getter for fullname private field.
Reimplemented from BANK.
Definition at line 132 of file AIB.cpp.
References fullname.
Referenced by operator=().
                                 {
    return fullname;
}
std::string AIB::GetLastName () const [virtual]
GetLastName getter for lastName private field.
Reimplemented from BANK.
Definition at line 108 of file AIB.cpp.
References lastName.
Referenced by operator=(), and toString().
                                 {
    return lastName;
}
AIB AIB::operator= (const AIB & orig) [inline]
Operator function
Definition at line 78 of file AIB.h.
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~AIB().
{};
void AIB::SetAccountNumber (int accountNumber) [virtual]
SetAccountNumber setter for accountNumber private field.
Reimplemented from BANK.
Definition at line 90 of file AIB.cpp.
References accountNumber.
Referenced by operator=().
                                            {
    this->accountNumber = accountNumber;
}
void AIB::SetAddress (std::string address) [virtual]
SetAddress setter for address private field.
Reimplemented from BANK.
Definition at line 66 of file AIB.cpp.
References address.
Referenced by operator=().
                                      {
    this->address = address;
}
void AIB::SetBalance (double balance) [virtual]
SetBalance setter for balance private field.
Reimplemented from BANK.
Definition at line 78 of file AIB.cpp.
References balance.
Referenced by operator=().
                                   {
    this->balance = balance;
}
void AIB::SetFirstName (std::string firstName) [virtual]
SetFirstName setter for firstName private field.
Reimplemented from BANK.
Definition at line 114 of file AIB.cpp.
References firstName.
Referenced by operator=().
                                          {
    this->firstName = firstName;
}
void AIB::SetFullname (std::string fullname) [virtual]
SetFullname setter for fullname private field.
Reimplemented from BANK.
Definition at line 126 of file AIB.cpp.
References fullname.
Referenced by operator=().
                                        {
    this->fullname = fullname;
}
void AIB::SetLastName (std::string lastName) [virtual]
SetLastName setter for lastName private field.
Reimplemented from BANK.
Definition at line 102 of file AIB.cpp.
References lastName.
Referenced by operator=().
                                        {
    this->lastName = lastName;
}
void AIB::toString () [virtual]
toString function, displays the object values in formatted way
Reimplemented from OSTM.
Definition at line 59 of file AIB.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName().
Referenced by operator=().
{
    std::cout << "\nAIB BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int AIB::accountNumber [private]
accountNumber int object private filed
Definition at line 123 of file AIB.h.
Referenced by AIB(), GetAccountNumber(), operator=(), and SetAccountNumber().
std::string AIB::address [private]
address string object private filed
Definition at line 131 of file AIB.h.
Referenced by AIB(), GetAddress(), operator=(), and SetAddress().
double AIB::balance [private]
balance double object private filed
Definition at line 127 of file AIB.h.
Referenced by AIB(), GetBalance(), operator=(), and SetBalance().
std::string AIB::firstName [private]
firstName string object private filed
Definition at line 115 of file AIB.h.
Referenced by AIB(), GetFirstName(), operator=(), and SetFirstName().
std::string AIB::fullname [private]
fullname string object private filed
Definition at line 111 of file AIB.h.
Referenced by AIB(), GetFullname(), operator=(), and SetFullname().
std::string AIB::lastName [private]
lastName string object private filed
Definition at line 119 of file AIB.h.
Referenced by AIB(), GetLastName(), operator=(), and SetLastName().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.