OSTM
NAME
OSTM -
SYNOPSIS
#include <OSTM.h>
Inherited by BANK.
Public Member Functions
virtual void copy (std::shared_ptr< OSTM > from, std::shared_ptr< OSTM > to)
The copy virtual method required for deep copy between objetcs within the transaction.
int Get_Unique_ID () const
@82 Function <Get_Unique_ID> getter for uniqueID private field
int Get_Version () const
@100 Function <Get_Version> setter for version private filed
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
The getbasecopy virtual method required for create a copy of the origin object/pointer and returning a copy of the object/pointer.
void increase_VersionNumber ()
@108 Function <increase_VersionNumber> commit time increase the version number associated with the object
bool Is_Abort_Transaction () const
@140 Function <Is_Abort_Transaction> return boolean value stored in the <abortTransaction> private filed
bool Is_Can_Commit () const
@124 Function <Is_Can_Commit> boolean function to determin the object can comit or need to roolback.
void lock_Mutex ()
@145 Function <lock_Mutex> setter for mutex to lock the object
OSTM ()
@21 Default constructor
OSTM (int _version_number_, int _unique_id_)
@39 Custom Constructor Used to copying objects
void Set_Abort_Transaction (bool abortTransaction)
@132 Function <Set_Abort_Transaction> setter for abortTransaction private filed
void Set_Can_Commit (bool canCommit)
@117 Function <Set_Can_Commit> setter for canCommit private filed
void Set_Unique_ID (int uniqueID)
@75 Function <Set_Unique_ID> setter for uniqueID private field
void Set_Version (int version)
@92 Function <Set_Version> setter for version private filed
virtual void toString ()
The toString function displaying/representing the object on the terminal is string format.
bool try_lock ()
@162 Function <is_Locked> Boolean function to try lock the object. If the object not locked then locks and return True it otherwise return False.
void unlock_Mutex ()
@154 Function <unlock_Mutex> setter for mutex to unlock the object
virtual ~OSTM ()
Private Member Functions
int Get_global_Unique_ID_Number ()
@61 Get_global_Unique_ID_Number function, If <global_Unique_ID_Number> equals to 10000000 then reset back to ZERO, to make sure the value of global_Unique_ID_Number never exceed the MAX_INT value
Private Attributes
bool abort_Transaction
bool canCommit
std::mutex mutex
int uniqueID
int version
const int ZERO = 0
Static Private Attributes
static int global_Unique_ID_Number = 0
Detailed Description
File: OSTM.h Author: Zoltan Fuzesi C00197361, IT Carlow, Software Engineering,
Supervisor : Joe Kehoe,
C++ Software Transactional Memory,
Created on December 18, 2017, 2:09 PM The OSTM class is the base class to all the inherited classes that intend to used with the Software Transactional memory library
Definition at line 23 of file OSTM.h.
Constructor & Destructor Documentation
OSTM::OSTM ()
@21 Default constructor
Definition at line 21 of file OSTM.cpp.
References abort_Transaction, canCommit, Get_global_Unique_ID_Number(), uniqueID, version, and ZERO.
{
    /* @24 Integer field <version> indicates the version number of the inherited child object */
    this->version = ZERO;
    /* @26 Integer field <uniqueID> is a unique identifier assigned to every object registered in OSTM library */
    this->uniqueID = Get_global_Unique_ID_Number();
    /* @28 Boolean value <canCommit> to determine the object can or cannot commit */
    this->canCommit = true;
    /* @30 Boolean field <abort_Transaction> to determine the object can or cannot commit */
    this->abort_Transaction = false;
}
OSTM::OSTM (int _version_number_, int _unique_id_)
@39 Custom Constructor Used to copying objects
Parameters:
version_number Integer value used to create a copy of the object with the actual version
unique_id Integer value used to create a copy of the object with the original unique ID
Definition at line 39 of file OSTM.cpp.
References abort_Transaction, canCommit, uniqueID, and version.
{
    /* @42 Integer field <version> indicates the version number of the inherited child object */
    this->uniqueID = _unique_id_;
    /* @44 Integer field <uniqueID> is a unique identifier assigned to every object registered in OSTM library */
    this->version = _version_number_;
    /* @46 Boolean value <canCommit> to determine the object can or cannot commit */
    this->canCommit = true;
    /* @48 Boolean value <abort_Transaction> to determine the object can or cannot commit */
    this->abort_Transaction = false;
}
OSTM::~OSTM () [virtual]
@54 Default De-constructor
Definition at line 54 of file OSTM.cpp.
            {
    /* Destroy the object. */
}
Member Function Documentation
virtual void OSTM::copy (std::shared_ptr< OSTM > from, std::shared_ptr< OSTM > to) [inline], [virtual]
The copy virtual method required for deep copy between objetcs within the transaction.
See also:
copy function implementation in inherited class class
Reimplemented in BOI, and AIB.
Definition at line 41 of file OSTM.h.
{};
int OSTM::Get_global_Unique_ID_Number () [private]
@61 Get_global_Unique_ID_Number function, If <global_Unique_ID_Number> equals to 10000000 then reset back to ZERO, to make sure the value of global_Unique_ID_Number never exceed the MAX_INT value Returning global_Unique_ID_Number to the constructor
Definition at line 61 of file OSTM.cpp.
References global_Unique_ID_Number.
Referenced by OSTM().
                                      {
    /* @64 Checking the global_Unique_ID_Number */
    if(global_Unique_ID_Number > 10000000)
        /* @65 Reset global_Unique_ID_Number to ZERO*/
        global_Unique_ID_Number = 0;
    /* @67 return static global_Unique_ID_Number */
    return ++global_Unique_ID_Number;
}
int OSTM::Get_Unique_ID () const
@82 Function <Get_Unique_ID> getter for uniqueID private field
Definition at line 82 of file OSTM.cpp.
References uniqueID.
Referenced by toString(), AIB::toString(), and BOI::toString().
{
    /* @85 return Object uniqueID */
    return uniqueID;
}
int OSTM::Get_Version () const
@100 Function <Get_Version> setter for version private filed
Definition at line 100 of file OSTM.cpp.
References version.
Referenced by toString(), AIB::toString(), and BOI::toString().
{
    /* return object version number */
    return version;
}
virtual std::shared_ptr<OSTM> OSTM::getBaseCopy (std::shared_ptr< OSTM > object) [inline], [virtual]
The getbasecopy virtual method required for create a copy of the origin object/pointer and returning a copy of the object/pointer.
See also:
getBaseCopy function implementation in child class
Reimplemented in AIB, and BOI.
Definition at line 46 of file OSTM.h.
{};
void OSTM::increase_VersionNumber ()
@108 Function <increase_VersionNumber> commit time increase the version number associated with the object
Definition at line 108 of file OSTM.cpp.
References version.
Referenced by toString().
{
    /* @111 increase object version number */
    this->version += 1;
}
bool OSTM::Is_Abort_Transaction () const
@140 Function <Is_Abort_Transaction> return boolean value stored in the <abortTransaction> private filed
Parameters:
abort_Transaction Boolean to determine the object can or cannot commit
Definition at line 140 of file OSTM.cpp.
References abort_Transaction.
Referenced by toString().
                                      {
    /* @142 return abort_Transaction object boolean value */
    return abort_Transaction;
}
bool OSTM::Is_Can_Commit () const
@124 Function <Is_Can_Commit> boolean function to determin the object can comit or need to roolback.
Definition at line 124 of file OSTM.cpp.
References canCommit.
Referenced by toString().
                               {
    /* @126 return canCommit boolean value TRUE/FALSE */
    return canCommit;
}
void OSTM::lock_Mutex ()
@145 Function <lock_Mutex> setter for mutex to lock the object
Definition at line 147 of file OSTM.cpp.
References mutex.
Referenced by toString().
                      {
    /* @149 Locking the mutex*/
    this->mutex.lock();
}
void OSTM::Set_Abort_Transaction (bool abortTransaction)
@132 Function <Set_Abort_Transaction> setter for abortTransaction private filed
Parameters:
abortTransaction Boolean to determine the object can or cannot commit
Definition at line 132 of file OSTM.cpp.
References abort_Transaction.
Referenced by toString().
                                                      {
    /* @134 set abort_Transaction object variable to parameter boolean value */
    this->abort_Transaction = abortTransaction;
}
void OSTM::Set_Can_Commit (bool canCommit)
@117 Function <Set_Can_Commit> setter for canCommit private filed
Parameters:
canCommit Boolean value to determine the object can or cannot commit
Definition at line 117 of file OSTM.cpp.
References canCommit.
Referenced by toString().
                                        {
    /* @119 set canCommit object variable to parameter boolean value*/
    this->canCommit = canCommit;
}
void OSTM::Set_Unique_ID (int uniqueID)
@75 Function <Set_Unique_ID> setter for uniqueID private field
Parameters:
uniqueID int Every object inherit from OSTM class will include a version number that is unique for every object. The STM library used this value to find object within the transaction to make changes or comparism ith them.
Definition at line 75 of file OSTM.cpp.
References uniqueID.
Referenced by AIB::copy(), BOI::copy(), and toString().
                                     {
    /* @77 set object uniqueID to parameter integer value */
    this->uniqueID = uniqueID;
}
void OSTM::Set_Version (int version)
@92 Function <Set_Version> setter for version private filed
Parameters:
version integer The verion number ZERO by default when the object created. When a transaction make changes with the object, then the version number will be increased, to indicate the changes on the object.
Definition at line 92 of file OSTM.cpp.
References version.
Referenced by toString().
{
    /* @95 set object version to parameter integer value */
    this->version = version;
}
virtual void OSTM::toString () [inline], [virtual]
The toString function displaying/representing the object on the terminal is string format.
See also:
toString function implementation in child class
Reimplemented in AIB, and BOI.
Definition at line 51 of file OSTM.h.
References canCommit, Get_Unique_ID(), Get_Version(), increase_VersionNumber(), Is_Abort_Transaction(), Is_Can_Commit(), lock_Mutex(), Set_Abort_Transaction(), Set_Can_Commit(), Set_Unique_ID(), Set_Version(), try_lock(), uniqueID, unlock_Mutex(), and version.
{};
bool OSTM::try_lock ()
@162 Function <is_Locked> Boolean function to try lock the object. If the object not locked then locks and return True it otherwise return False.
Definition at line 162 of file OSTM.cpp.
References mutex.
Referenced by toString().
                   {
    /* @164 Try to unlock the mutex, return TRUE if the lock was acquired successfully, otherwise return FALSE */
    return this->mutex.try_lock();
}
void OSTM::unlock_Mutex ()
@154 Function <unlock_Mutex> setter for mutex to unlock the object
Definition at line 154 of file OSTM.cpp.
References mutex.
Referenced by toString().
                        {
    /* @156 Locking the mutex */
    this->mutex.unlock();
}
Member Data Documentation
bool OSTM::abort_Transaction [private]
Boolean value <abort_Transaction> to determine the object can or cannot commit
Definition at line 125 of file OSTM.h.
Referenced by Is_Abort_Transaction(), OSTM(), and Set_Abort_Transaction().
bool OSTM::canCommit [private]
Boolean value <canCommit> to determine the object can or cannot commit
Definition at line 121 of file OSTM.h.
Referenced by Is_Can_Commit(), OSTM(), Set_Can_Commit(), and toString().
int OSTM::global_Unique_ID_Number = 0 [static], [private]
Unique object number start at ZERO The value stored in the static class level <global_Unique_ID_Number> increase every OSTM type object creation.
Definition at line 130 of file OSTM.h.
Referenced by Get_global_Unique_ID_Number().
std::mutex OSTM::mutex [private]
Mutex lock <mutex> use to lock the object with transaction, to make sure only one transaction can access the object at the time
Definition at line 139 of file OSTM.h.
Referenced by lock_Mutex(), try_lock(), and unlock_Mutex().
int OSTM::uniqueID [private]
Object unique identifier Every object inherit from OSTM class will include a version number that is unique for every object. The STM library used this value to find object within the transaction to make changes or comparism ith them.
Definition at line 117 of file OSTM.h.
Referenced by Get_Unique_ID(), OSTM(), Set_Unique_ID(), and toString().
int OSTM::version [private]
Object private version number. The verion number ZERO by default when the object created. When a transaction make changes with the object, then the version number will be increased, to indicate the changes on the object.
Definition at line 111 of file OSTM.h.
Referenced by Get_Version(), increase_VersionNumber(), OSTM(), Set_Version(), and toString().
const int OSTM::ZERO = 0 [private]
Integer <ZERO> meaninful string equalient to 0
Definition at line 134 of file OSTM.h.
Referenced by OSTM().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.