.TH "TX.h" 3 "Tue Mar 13 2018" "C++ Software transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TX.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <map>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <thread>\fP
.br
\fC#include 'OSTM\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTX\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software transactional Memory from the source code\&.
