.TH "WAREHOUSE" 3 "Sun Apr 1 2018" "Version v 0.0.1" "C++ Software Transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WAREHOUSE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WAREHOUSE\&.h>\fP
.PP
Inherits \fBOSTM\fP\&.
.PP
Inherited by \fBCARLOW_W\fP, \fBCARPHONE_WAREHOUSE\fP, \fBDUNDALK_W\fP, \fBKILKENNY_W\fP, \fBSLIGO_W\fP, and \fBTALLAGH_W\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWAREHOUSE\fP ()"
.br
.ti -1c
.RI "\fBWAREHOUSE\fP (int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBWAREHOUSE\fP (const \fBWAREHOUSE\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~WAREHOUSE\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_alcatel\fP (int _number_of_alcatel)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_alcatel\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_nokia\fP (int _number_of_nokia)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_nokia\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_huawei\fP (int _number_of_huawei)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_huawei\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_sony\fP (int _number_of_sony)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_sony\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_samsung\fP (int _number_of_samsung)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_samsung\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_iphones\fP (int _number_of_iphones)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_iphones\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetShop_name\fP (std::string _shop_name)"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_name\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetShop_address\fP (std::string _shop_address)"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_address\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWAREHOUSE\fP inherit from \fBOSTM\fP library 
.PP
Definition at line 16 of file WAREHOUSE\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WAREHOUSE::WAREHOUSE ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 21 of file WAREHOUSE\&.h\&.
.SS "WAREHOUSE::WAREHOUSE (int _version, int _unique_id)\fC [inline]\fP"
Custom Constructor 
.PP
Definition at line 27 of file WAREHOUSE\&.h\&.
.SS "WAREHOUSE::WAREHOUSE (const \fBWAREHOUSE\fP & orig)"
Copy constructor 
.PP
Definition at line 12 of file WAREHOUSE\&.cpp\&.
.SS "WAREHOUSE::~WAREHOUSE ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 15 of file WAREHOUSE\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual int WAREHOUSE::GetNumber_of_alcatel ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 44 of file WAREHOUSE\&.h\&.
.SS "virtual int WAREHOUSE::GetNumber_of_huawei ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 48 of file WAREHOUSE\&.h\&.
.SS "virtual int WAREHOUSE::GetNumber_of_iphones ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 54 of file WAREHOUSE\&.h\&.
.SS "virtual int WAREHOUSE::GetNumber_of_nokia ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 46 of file WAREHOUSE\&.h\&.
.SS "virtual int WAREHOUSE::GetNumber_of_samsung ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 52 of file WAREHOUSE\&.h\&.
.SS "virtual int WAREHOUSE::GetNumber_of_sony ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 50 of file WAREHOUSE\&.h\&.
.SS "virtual std::string WAREHOUSE::GetShop_address ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 58 of file WAREHOUSE\&.h\&.
.SS "virtual std::string WAREHOUSE::GetShop_name ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 56 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_alcatel (int _number_of_alcatel)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 43 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_huawei (int _number_of_huawei)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 47 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_iphones (int _number_of_iphones)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 53 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_nokia (int _number_of_nokia)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 45 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_samsung (int _number_of_samsung)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 51 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetNumber_of_sony (int _number_of_sony)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 49 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetShop_address (std::string _shop_address)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 57 of file WAREHOUSE\&.h\&.
.SS "virtual void WAREHOUSE::SetShop_name (std::string _shop_name)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCARPHONE_WAREHOUSE\fP, \fBSLIGO_W\fP, \fBTALLAGH_W\fP, \fBCARLOW_W\fP, \fBDUNDALK_W\fP, and \fBKILKENNY_W\fP\&.
.PP
Definition at line 55 of file WAREHOUSE\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional Memory from the source code\&.
