TX
NAME
TX -
SYNOPSIS
#include <TX.h>
Public Member Functions
TX (std::thread::id id)
Constructor.
~TX ()
De-constructor.
TX (const TX &orig)
Default copy constructor.
void ostm_exit ()
Delete all map entries associated with the main process.
void _register (std::shared_ptr< OSTM > object)
Register OSTM pointer into STM library.
std::shared_ptr< OSTM > load (std::shared_ptr< OSTM > object)
load std::shared_ptr<OSTM>, returning an std::shared_ptr<OSTM> copy of the original pointer, to work with during transaction life time
void store (std::shared_ptr< OSTM > object)
Store transactional changes.
bool commit ()
Commit transactional changes.
void _increase_tx_nesting ()
Add TX nesting level by one.
void _decrease_tx_nesting ()
Remove TX nesting level by one.
int getTest_counter ()
getTest_counter TESTING ONLY!!! returning the value of the test_counter stored, number of rollbacks
void _print_all_tx ()
Static Public Attributes
static int test_counter = 0
Friends
class TM
Detailed Description
Definition at line 24 of file TX.h.
Constructor & Destructor Documentation
TX::TX (std::thread::id id)
Constructor.
Parameters:
transaction_Number int, to store associated thread
_tx_nesting_level int, to store and indicate nesting level of transactions within transaction
Definition at line 31 of file TX.cpp.
                     {
    this->transaction_Number = id;
    this->_tx_nesting_level = 0;
}
TX::~TX ()
De-constructor.
Definition at line 38 of file TX.cpp.
        {
   
}
TX::TX (const TX & orig)
Default copy constructor.
Definition at line 44 of file TX.cpp.
                     {
}
Member Function Documentation
void TX::_decrease_tx_nesting ()
Remove TX nesting level by one. _decrease_tx_nesting decrease the value stored in _tx_nesting_level by one, when outer transactions commiting
Parameters:
_tx_nesting_level int
Definition at line 316 of file TX.cpp.
Referenced by commit().
                              {
   // std::cout << "[this->_tx_nesting_level] = " << this->_tx_nesting_level << std::endl;
    this->_tx_nesting_level -= 1;
;
}
void TX::_increase_tx_nesting ()
Add TX nesting level by one. _increase_tx_nesting increase the value stored in _tx_nesting_level by one, indicate that the transaction nested
Parameters:
_tx_nesting_level int
Definition at line 307 of file TX.cpp.
                              {
      
    this->_tx_nesting_level += 1;
    // std::cout << "[this->_tx_nesting_level] = " << this->_tx_nesting_level << std::endl;
}
void TX::_print_all_tx ()
ONLY FOR TESTING CHECK THE MAP AFTER THREAD EXIT AND ALL SHOULD BE DELETED!!!!!!!
Definition at line 346 of file TX.cpp.
                       {
    std::cout << "[PRINTALLTHREAD]" << std::endl;
    std::map< int, std::shared_ptr<OSTM> >::iterator it;
    /*
     * All registered thread id in the TX global
     */
     pid_t ppid = getppid();
    std::map<pid_t, std::map< int, int >>::iterator process_map_collection_Iterator = TX::process_map_collection.find(ppid);
    if (process_map_collection_Iterator != TX::process_map_collection.end()) {
        for (auto current = process_map_collection_Iterator->second.begin(); current != process_map_collection_Iterator->second.end(); ++current) {
            it = working_Map_collection.find(current->first);
            if(it != working_Map_collection.end()){
                std::cout << "[Unique number ] : " <<it->second->Get_Unique_ID() << std::endl;
            }
            
        }
     
    }
}
void TX::_register (std::shared_ptr< OSTM > object)
Register OSTM pointer into STM library. register void, receives an std::shared_ptr<OSTM> that point to the original memory space to protect from reca conditions
Parameters:
working_Map_collection std::map, store all the std::shared_ptr<OSTM> pointer in the transaction
main_Process_Map_collection std::map, store all std::shared_ptr<OSTM> from all transaction, used to lock and compare the objects
process_map_collection std::map, store all std::shared_ptr<OSTM> unique ID from all transaction, used to delete all pointers used by the main process, from all transaction before the program exit.
std::lock_guard use register_Lock(mutex) shared lock between all transaction
ppid int, store main process number
Definition at line 104 of file TX.cpp.
                                             {
    /*
     * MUST USE SHARED LOCK TO PROTECT SHARED GLOBAL MAP/COLLECTION
     */
    std::lock_guard<std::mutex> guard(TX::register_Lock);
    
    /*
     * Check for null pointer !
     * Null pointer can cause segmentation fault!!!
     */
    if(object == nullptr){
        throw std::runtime_error(std::string("[RUNTIME ERROR : NULL POINTER IN REGISTER FUNCTION]") );
    }
    
    pid_t ppid = getppid();
    std::map<pid_t, std::map< int, int >>::iterator process_map_collection_Iterator = TX::process_map_collection.find(ppid);
    if (process_map_collection_Iterator == TX::process_map_collection.end()) {
        /*
         * Register main process/application to the global map
         */
        std::map< int, int >map = get_thread_Map();
        TX::process_map_collection.insert({ppid, map});
        /*
         * Get the map if registered first time
         */
        process_map_collection_Iterator = TX::process_map_collection.find(ppid);
    }
    std::map<int, std::shared_ptr<OSTM>>::iterator main_Process_Map_collection_Iterator = TX::main_Process_Map_collection.find(object->Get_Unique_ID());
    if (main_Process_Map_collection_Iterator == TX::main_Process_Map_collection.end()) {
        /*
         * Insert to the GLOBAL MAP
         */
        TX::main_Process_Map_collection.insert({object->Get_Unique_ID(), object});
        /*
         * Insert to the GLOBAL MAP as a helper to clean up at end of main process
         */
        process_map_collection_Iterator->second.insert({object->Get_Unique_ID(), 1});
    }
    std::map< int, std::shared_ptr<OSTM> >::iterator working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.find(object->Get_Unique_ID());
    if (working_Map_collection_Object_Shared_Pointer_Iterator == working_Map_collection.end()) {
        working_Map_collection.insert({object->Get_Unique_ID(), object->getBaseCopy(object)});
    }
}
bool TX::commit ()
Commit transactional changes. commit bool, returns boolean value TRUE/FALSE depends on the action taken within the function
Parameters:
working_Map_collection std::map, store all the std::shared_ptr<OSTM> pointer in the transaction
main_Process_Map_collection std::map, store all std::shared_ptr<OSTM> from all transaction, used to lock and compare the objects
can_Commit bool, helps to make decision that the transaction can commit or rollback
Definition at line 202 of file TX.cpp.
References _decrease_tx_nesting(), and test_counter.
                {
    bool can_Commit = true;
 
    /*
     * Dealing with nested transactions first
     */
    if (this->_tx_nesting_level > 0) {
        _decrease_tx_nesting();
        return true;
    }
    
    std::map< int, std::shared_ptr<OSTM> >::iterator working_Map_collection_Object_Shared_Pointer_Iterator;
    std::map<int, std::shared_ptr<OSTM>>::iterator main_Process_Map_collection_Iterator;
    for (working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.begin(); working_Map_collection_Object_Shared_Pointer_Iterator != working_Map_collection.end(); working_Map_collection_Object_Shared_Pointer_Iterator++) {
            main_Process_Map_collection_Iterator = TX::main_Process_Map_collection.find(working_Map_collection_Object_Shared_Pointer_Iterator->second->Get_Unique_ID());
            /*
             * Throws runtime error if object can not find
             */
            if(main_Process_Map_collection_Iterator == TX::main_Process_Map_collection.end())
            {
                throw std::runtime_error(std::string("[RUNTIME ERROR : CAN'T FIND OBJECT COMMIT FUNCTION]"));
            }
        /*
         * Busy wait WHILE object locked by other thread
         */
        while(!(main_Process_Map_collection_Iterator->second)->is_Locked());
        if (main_Process_Map_collection_Iterator->second->Get_Version() > working_Map_collection_Object_Shared_Pointer_Iterator->second->Get_Version()) {
            working_Map_collection_Object_Shared_Pointer_Iterator->second->Set_Can_Commit(false);
            can_Commit = false;
            break;
        } else {
            working_Map_collection_Object_Shared_Pointer_Iterator->second->Set_Can_Commit(true);
        }
    }
    if (!can_Commit) {
        TX::test_counter += 1;
        for (working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.begin(); working_Map_collection_Object_Shared_Pointer_Iterator != working_Map_collection.end(); working_Map_collection_Object_Shared_Pointer_Iterator++) {
          
            main_Process_Map_collection_Iterator = TX::main_Process_Map_collection.find(working_Map_collection_Object_Shared_Pointer_Iterator->second->Get_Unique_ID());
            (working_Map_collection_Object_Shared_Pointer_Iterator->second)->copy(working_Map_collection_Object_Shared_Pointer_Iterator->second, main_Process_Map_collection_Iterator->second);
        }
        
        _release_object_lock();
        return false;
    } else {
        /*
         * Commit changes
         */
        for (working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.begin(); working_Map_collection_Object_Shared_Pointer_Iterator != working_Map_collection.end(); working_Map_collection_Object_Shared_Pointer_Iterator++) {
            
                main_Process_Map_collection_Iterator = TX::main_Process_Map_collection.find((working_Map_collection_Object_Shared_Pointer_Iterator->second)->Get_Unique_ID());
                if (main_Process_Map_collection_Iterator != TX::main_Process_Map_collection.end()) {
                    (main_Process_Map_collection_Iterator->second)->copy(main_Process_Map_collection_Iterator->second, working_Map_collection_Object_Shared_Pointer_Iterator->second);
                    main_Process_Map_collection_Iterator->second->increase_VersionNumber();
                } else {
                    throw std::runtime_error(std::string("[RUNTIME ERROR : CAN'T FIND OBJECT COMMIT FUNCTION]"));
                }
        }
        _release_object_lock();
        this->th_exit();
        return true;
    }
}//Commit finish
int TX::getTest_counter ()
getTest_counter TESTING ONLY!!! returning the value of the test_counter stored, number of rollbacks
Definition at line 324 of file TX.cpp.
References test_counter.
                        {
    return TX::test_counter;
}
std::shared_ptr< OSTM > TX::load (std::shared_ptr< OSTM > object)
load std::shared_ptr<OSTM>, returning an std::shared_ptr<OSTM> copy of the original pointer, to work with during transaction life time Register OSTM pointer into STM library
Parameters:
working_Map_collection std::map, store all the std::shared_ptr<OSTM> pointer in the transaction
Definition at line 155 of file TX.cpp.
                                                       {
    std::map< int, std::shared_ptr<OSTM> >::iterator working_Map_collection_Object_Shared_Pointer_Iterator;
    /*
     * Check for null pointer !
     * Null pointer can cause segmentation fault!!!
     */
    if(object == nullptr){
        throw std::runtime_error(std::string("[RUNTIME ERROR : NULL POINTER IN LOAD FUNCTION]") );
    }
        working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.find(object->Get_Unique_ID());
    if (working_Map_collection_Object_Shared_Pointer_Iterator != working_Map_collection.end()) {
        return working_Map_collection_Object_Shared_Pointer_Iterator->second->getBaseCopy(working_Map_collection_Object_Shared_Pointer_Iterator->second);
        
    } else { throw std::runtime_error(std::string("[RUNTIME ERROR : NO OBJECT FOUND LOAD FUNCTION]") );}
}
void TX::ostm_exit ()
Delete all map entries associated with the main process. ostm_exit void, clear all elements from the shared global collections associated with the main process
Parameters:
main_Process_Map_collection std::map, store all std::shared_ptr<OSTM> from all transaction shared between multiple processes
process_map_collection std::map, store all unique id from all transaction within main process DO NOT CALL THIS METHOD EXPLICITLY!!!!!! WILL DELETE ALL PROCESS ASSOCIATED ELEMENTS!!!!
Definition at line 72 of file TX.cpp.
Referenced by TM::_TX_EXIT().
                   {
    std::map<int, std::shared_ptr<OSTM>>::iterator main_Process_Map_collection_Iterator;
     
    pid_t ppid = getppid();
    std::map<pid_t, std::map< int, int >>::iterator process_map_collection_Iterator = TX::process_map_collection.find(ppid);
    if (process_map_collection_Iterator != TX::process_map_collection.end()) {
        for (auto current = process_map_collection_Iterator->second.begin(); current != process_map_collection_Iterator->second.end(); ++current) {
            main_Process_Map_collection_Iterator = TX::main_Process_Map_collection.find(current->first);
            if (main_Process_Map_collection_Iterator != TX::main_Process_Map_collection.end()){
                /*
                 * Delete element from shared main_Process_Map_collection by object unique key value, shared_ptr will destroy automatically
                 */
                TX::main_Process_Map_collection.erase(main_Process_Map_collection_Iterator->first);
            }
        }
        /*
         * Delete from Process_map_collection, Main process exits delete association with library
         */
        TX::process_map_collection.erase(process_map_collection_Iterator->first);
    }
}
void TX::store (std::shared_ptr< OSTM > object)
Store transactional changes. store void, receive an std::shared_ptr<OSTM> object to store the changes within the transaction, depends the user action
Parameters:
working_Map_collection std::map, store all the std::shared_ptr<OSTM> pointer in the transaction
Definition at line 178 of file TX.cpp.
                                         {
    /*
     * Check for null pointer !
     * Null pointer can cause segmentation fault!!!
     */
    if(object == nullptr){
        throw std::runtime_error(std::string("[RUNTIME ERROR : NULL POINTER IN STORE FUNCTION]") );
    }
    
    std::map< int, std::shared_ptr<OSTM> >::iterator working_Map_collection_Object_Shared_Pointer_Iterator;
    working_Map_collection_Object_Shared_Pointer_Iterator = working_Map_collection.find(object->Get_Unique_ID());
    if (working_Map_collection_Object_Shared_Pointer_Iterator != working_Map_collection.end()) {
        working_Map_collection_Object_Shared_Pointer_Iterator->second = object;
    } else { std::cout << "[ERROR STORE]" << std::endl; }
}
Friends And Related Function Documentation
friend class TM [friend]
Only TM Transaction Manager can create instance of TX Transaction
Definition at line 70 of file TX.h.
Member Data Documentation
int TX::test_counter = 0 [static]
Parameters:
test_counter int ONLY FOR TESTING!!!
static Global counter for rollback
Definition at line 78 of file TX.h.
Referenced by commit(), and getTest_counter().
Author
Generated automatically by Doxygen for O_STM from the source code.