.TH "OSTM.cpp" 3 "Sun Apr 1 2018" "Version v 0.0.1" "C++ Software Transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OSTM.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OSTM\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional Memory from the source code\&.
