.TH "SWBPLC" 3 "Sun Apr 1 2018" "Version v 0.0.1" "C++ Software Transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SWBPLC \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SWBPLC\&.h>\fP
.PP
Inherits \fBBANK\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSWBPLC\fP ()"
.br
.ti -1c
.RI "\fBSWBPLC\fP (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)"
.br
.ti -1c
.RI "\fBSWBPLC\fP (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBSWBPLC\fP (const \fBSWBPLC\fP &orig)"
.br
.ti -1c
.RI "\fBSWBPLC\fP \fBoperator=\fP (const \fBSWBPLC\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~SWBPLC\fP ()"
.br
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)"
.br
.RI "\fIcopy function, make deep copy of the object/pointer \fP"
.ti -1c
.RI "virtual std::shared_ptr< \fBOSTM\fP > \fBgetBaseCopy\fP (std::shared_ptr< \fBOSTM\fP > object)"
.br
.RI "\fIgetBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object \fP"
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type \fP"
.ti -1c
.RI "virtual void \fBSetAddress\fP (std::string address)"
.br
.ti -1c
.RI "virtual std::string \fBGetAddress\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetBalance\fP (double balance)"
.br
.ti -1c
.RI "virtual double \fBGetBalance\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetAccountNumber\fP (int accountNumber)"
.br
.ti -1c
.RI "virtual int \fBGetAccountNumber\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetLastName\fP (std::string lastName)"
.br
.ti -1c
.RI "virtual std::string \fBGetLastName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFirstName\fP (std::string firstName)"
.br
.ti -1c
.RI "virtual std::string \fBGetFirstName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFullname\fP (std::string fullname)"
.br
.ti -1c
.RI "virtual std::string \fBGetFullname\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Inherit from \fBBANK\fP 
.PP
Definition at line 19 of file SWBPLC\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SWBPLC::SWBPLC ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 24 of file SWBPLC\&.h\&.
.SS "SWBPLC::SWBPLC (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)\fC [inline]\fP"
Custom constructor 
.PP
Definition at line 35 of file SWBPLC\&.h\&.
.SS "SWBPLC::SWBPLC (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)\fC [inline]\fP"
Custom constructor, used by the library for deep copying 
.PP
Definition at line 46 of file SWBPLC\&.h\&.
.SS "SWBPLC::SWBPLC (const \fBSWBPLC\fP & orig)"
Copy constructor 
.PP
Definition at line 12 of file SWBPLC\&.cpp\&.
.SS "SWBPLC::~SWBPLC ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 15 of file SWBPLC\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void SWBPLC::copy (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)\fC [virtual]\fP"

.PP
copy function, make deep copy of the object/pointer 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.br
\fIobjFROM\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 34 of file SWBPLC\&.cpp\&.
.SS "int SWBPLC::GetAccountNumber () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 80 of file SWBPLC\&.cpp\&.
.SS "std::string SWBPLC::GetAddress () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 64 of file SWBPLC\&.cpp\&.
.SS "double SWBPLC::GetBalance () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 72 of file SWBPLC\&.cpp\&.
.SS "std::shared_ptr< \fBOSTM\fP > SWBPLC::getBaseCopy (std::shared_ptr< \fBOSTM\fP > object)\fC [virtual]\fP"

.PP
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a \fBBANK\fP type pointer for casting 
.br
\fIobj\fP is a std::shared_ptr<BANK> return type 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 22 of file SWBPLC\&.cpp\&.
.SS "std::string SWBPLC::GetFirstName () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 96 of file SWBPLC\&.cpp\&.
.SS "std::string SWBPLC::GetFullname () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 104 of file SWBPLC\&.cpp\&.
.SS "std::string SWBPLC::GetLastName () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 88 of file SWBPLC\&.cpp\&.
.SS "\fBSWBPLC\fP SWBPLC::operator= (const \fBSWBPLC\fP & orig)\fC [inline]\fP"
Operator 
.PP
Definition at line 63 of file SWBPLC\&.h\&.
.SS "void SWBPLC::SetAccountNumber (int accountNumber)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 76 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::SetAddress (std::string address)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 60 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::SetBalance (double balance)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 68 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::SetFirstName (std::string firstName)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 92 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::SetFullname (std::string fullname)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 100 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::SetLastName (std::string lastName)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 84 of file SWBPLC\&.cpp\&.
.SS "void SWBPLC::toString ()\fC [virtual]\fP"

.PP
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 55 of file SWBPLC\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional Memory from the source code\&.
