.TH "main.cpp" 3 "Sun Apr 1 2018" "CppUnit test STM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <cppunit/extensions/TestFactoryRegistry\&.h>\fP
.br
\fC#include <cppunit/extensions/HelperMacros\&.h>\fP
.br
\fC#include <cppunit/ui/text/TestRunner\&.h>\fP
.br
\fC#include 'MyTestCAse\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCPPUNIT_TEST_SUITE_REGISTRATION\fP (\fBMyTestCAse\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "CPPUNIT_TEST_SUITE_REGISTRATION (\fBMyTestCAse\fP)"

.SS "int main (int argc, char ** argv)"

.PP
Definition at line 13 of file main\&.cpp\&.
.PP
.nf
13                                 {
14     TextUi::TestRunner runner;
15     TestFactoryRegistry  &registry = TestFactoryRegistry::getRegistry();
16     runner\&.addTest(registry\&.makeTest());
17     runner\&.run();
18     return (EXIT_SUCCESS);
19 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for CppUnit test STM from the source code\&.
