MyTestCAse
NAME
MyTestCAse -
SYNOPSIS
#include <MyTestCAse.h>
Inherits TestCase.
Public Member Functions
void _collection_bject_ (std::vector< std::shared_ptr< OSTM >> _customer_vec, TM &_tm, double _amount, int loop)
Test with a vector collection.
void _complex_transfer_ (std::shared_ptr< OSTM > _from_, std::shared_ptr< OSTM > _from_two_, std::vector< std::shared_ptr< OSTM >> _customer_vec, TM &_tm, double _amount)
This function use two single objects and a collection of objects in the transaction. The two single object transfer 1 - 1 (2) unit to every object in the collection.
void _nesting_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
Testing nested transaction.
void _one_account_transfer_ (std::shared_ptr< OSTM > _to_, TM &_tm, double _amount)
one object in the trasaction
void _six_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_one_, std::shared_ptr< OSTM > _from_two_, std::shared_ptr< OSTM > _from_three_, std::shared_ptr< OSTM > _from_four_, std::shared_ptr< OSTM > _from_five_, TM &_tm, double _amount)
Testing the transactions between six object.
void _two_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM &tm, double _amount)
Testin transaction between two pointer.
void compare_Transaction_Manager_singleton_instance ()
This testing function comparing the Transaction Manager to make sure the application using a Singleton object.
void complex_threaded_functionality_hundred_threads ()
void complex_threaded_functionality_ten_threads ()
Testing the library consistent behavior This test transfer 1 - 1 unit by 10 threads = 10 * 1 = 10 to evey object in the collection (-600) by single objects After transfer from account has -10 * 600 for both single objects and + 2 unit * 10 to every objects.
void decrease_nesting ()
Testing the nesting decrease function.
void decrease_nesting_fail ()
Testing the nesting decrease function to make sure the variable state changing.
void increase_nesting ()
Testing the nesting increase function.
void increase_nesting_fail ()
Testing the nesting increase function to make sure the variable state changing.
void multi_threaded_multiple_object_exchange_test ()
Design Manual document based tests Implementations.
void multi_threaded_multiple_objects_test ()
4.
Multi-threaded multiple Objects test.
"
void multi_threaded_single_object_test_with_ten_threads ()
2.
Multi-threaded single Object test with 10 threads.
"
MyTestCAse ()
MyTestCAse (const MyTestCAse &orig)
void nested_hundred_thread_functionality ()
Testing the library consistent behavior Nested threaded function : 3 level of nesting, every thread transfer 3 unit from one object to the another object so, at end of the 100 thransaction the from object transfer 100 * 3 (300) to the another object 500 - 300 = 200 AND 500 + 300 = 800.
void nested_thousand_thread_functionality ()
Testing the library consistent behavior Nested threaded function : 3 level of nesting, every thread transfer 3 unit from one object to the another object so, at end of the 100 thransaction the from object transfer 1000 * 3 (3000) to the another object 500 - 3000 = -2500 AND 500 + 3000 = 3500.
void nested_transaction_object_test ()
Testing the library consistent behavior This test calls the nested function, where every thread transfer 3 unit in the nested transactions. Because this test in not threaded, the 3 level deep nesting transfer 3*20 = 60 from one object to the another object. 500 - 60 = 440 AND 500 + 60 = 560.
void object_not_registered_throw_runtime_error ()
The library function throws runtime error if the client application tries to load a working pointer from the library of a not registered pointer by the client application. Runtime error should be thrown.
void register_null_pointer_throw_runtime_error ()
void setUp ()
void single_threaded_multiple_object_test ()
3.
Single-threaded multiple object test.
"
void store_null_pointer_throw_runtime_error ()
The test function throws runtime error if the client application tries to store the changed working pointer as a null pointer. Runtime error should be thrown.
void tearDown ()
void threaded_functionality_hundred_threads ()
void threaded_functionality_hundred_threads_six_account ()
Testing the library consistent behavior This test transfer 1 unit by 100 threads from five account to one account After transfer from account has - 100*1 from the accounts, and to account has +100*5.
void threaded_functionality_thousand_threads ()
Testing the library consistent behavior This test transfer 1 unit by 1000 threads = 1000 *1 = 100 After transfer from account has -1000, and to account has +1000.
void threaded_functionality_thousand_threads_six_account ()
Testing the library consistent behavior This test transfer 1 unit by 1000 threads from five account to one account After transfer from account has - 1000*1 from the accounts, and to account has +1000*5.
void TM_get_thread_map ()
This function testing the returned map from the Transaction Manager class.
void two_object_transfer_complete ()
Testing the library consistent behavior Transfer between two objects : the from object transfer 20 to the another object 500 - 20 = 480 AND 500 + 20 = 520.
void two_object_transfer_state_change ()
This function proves the objects states must change from the base values.
virtual ~MyTestCAse ()
Public Attributes
std::shared_ptr< OSTM > aib_ptr
std::shared_ptr< OSTM > boa_ptr
std::shared_ptr< OSTM > boi_ptr
std::shared_ptr< OSTM > swplc_ptr
TM & tm = TM::Instance()
std::shared_ptr< OSTM > ulster_ptr
std::shared_ptr< OSTM > unbl_ptr
Private Member Functions
CPPUNIT_TEST (threaded_functionality_hundred_threads)
CPPUNIT_TEST (threaded_functionality_thousand_threads)
CPPUNIT_TEST (threaded_functionality_hundred_threads_six_account)
CPPUNIT_TEST (threaded_functionality_thousand_threads_six_account)
CPPUNIT_TEST (nested_hundred_thread_functionality)
CPPUNIT_TEST (nested_thousand_thread_functionality)
CPPUNIT_TEST (complex_threaded_functionality_hundred_threads)
CPPUNIT_TEST (complex_threaded_functionality_ten_threads)
CPPUNIT_TEST (two_object_transfer_complete)
CPPUNIT_TEST (two_object_transfer_state_change)
CPPUNIT_TEST (nested_transaction_object_test)
CPPUNIT_TEST (multi_threaded_multiple_object_exchange_test)
CPPUNIT_TEST (multi_threaded_single_object_test_with_ten_threads)
CPPUNIT_TEST (single_threaded_multiple_object_test)
CPPUNIT_TEST (multi_threaded_multiple_objects_test)
CPPUNIT_TEST (increase_nesting)
CPPUNIT_TEST (increase_nesting_fail)
CPPUNIT_TEST (decrease_nesting)
CPPUNIT_TEST (decrease_nesting_fail)
CPPUNIT_TEST (two_object_transfer_state_change)
CPPUNIT_TEST (compare_Transaction_Manager_singleton_instance)
CPPUNIT_TEST (TM_get_thread_map)
CPPUNIT_TEST_EXCEPTION (register_null_pointer_throw_runtime_error, std::runtime_error)
CPPUNIT_TEST_EXCEPTION (object_not_registered_throw_runtime_error, std::runtime_error)
CPPUNIT_TEST_EXCEPTION (store_null_pointer_throw_runtime_error, std::runtime_error)
CPPUNIT_TEST_SUITE (MyTestCAse)
CPPUNIT_TEST_SUITE_END ()
Private Attributes
client * a
client * b
client * c
Detailed Description
Definition at line 18 of file MyTestCAse.h.
Constructor & Destructor Documentation
MyTestCAse::MyTestCAse () [inline]
Definition at line 61 of file MyTestCAse.h.
{};
MyTestCAse::MyTestCAse (const MyTestCAse & orig)
Definition at line 9 of file MyTestCAse.cpp.
                                             {
}
MyTestCAse::~MyTestCAse () [virtual]
Definition at line 12 of file MyTestCAse.cpp.
                        {
}
Member Function Documentation
void MyTestCAse::_collection_bject_ (std::vector< std::shared_ptr< OSTM >> _customer_vec, TM & _tm, double _amount, int loop)
Test with a vector collection.
Parameters:
_customer_vec collection of OSTM type objects
_tm TRansaction Manager
_amount value used in the transaction
Declare required pointers
Register customers accounts from the collection (vector)
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 20 of file MyTestCAse.cpp.
References TM::_get_tx(), and BANK::SetBalance().
Referenced by multi_threaded_multiple_objects_test(), and single_threaded_multiple_object_test().
                                                                                                                   {
    
     std::shared_ptr<TX> tx = _tm._get_tx();
    std::shared_ptr<OSTM> _TO_OSTM_;
    std::shared_ptr<BANK> _TO_;
    bool done = false;
    try {
        while (!done) {
            for (int i = 0; i < loop; ++i) {
                for (auto&& obj : _customer_vec) {
                    // auto&& obj = _customer_vec.at(i);
                    tx->_register(obj);
                    _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(obj));
                    _TO_->SetBalance(_TO_->GetBalance() + (_amount));
                    _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_);
                    tx->store(_TO_OSTM_);
                }
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void MyTestCAse::_complex_transfer_ (std::shared_ptr< OSTM > _from_, std::shared_ptr< OSTM > _from_two_, std::vector< std::shared_ptr< OSTM >> _customer_vec, TM & _tm, double _amount)
This function use two single objects and a collection of objects in the transaction. The two single object transfer 1 - 1 (2) unit to every object in the collection.
Parameters:
<em>from</em> pointer used in transaction
<em>from_two</em> pointer used in transaction
_customer_vec collection of pointer
_tm TRansaction Manager
_amount value used in the transaction
Register the two single account
Declare required pointers
Register customers accounts from the collection (vector)
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 126 of file MyTestCAse.cpp.
References TM::_get_tx(), and BANK::SetBalance().
Referenced by complex_threaded_functionality_hundred_threads(), and complex_threaded_functionality_ten_threads().
                                                                                                                                                                     {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_from_);
    tx->_register(_from_two_);
    std::shared_ptr<OSTM> _FROM_OSTM_ONE_, _FROM_OSTM_TWO_, _TO_OSTM_;
    std::shared_ptr<BANK> _FROM_, _FROM_TWO_, _TO_;
    bool done = false;
    try {
        while (!done) {
            // for (int i = 0; i < vector_number; ++i) {
            for (auto&& obj : _customer_vec) {
                // auto&& obj = _customer_vec.at(i);
                tx->_register(obj);
                _FROM_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
                _FROM_TWO_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_two_));
                _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(obj));
                _FROM_->SetBalance(_FROM_->GetBalance() - _amount);
                _FROM_TWO_->SetBalance(_FROM_TWO_->GetBalance() - _amount);
                _TO_->SetBalance(_TO_->GetBalance() + (_amount * 2));
                _FROM_OSTM_ONE_ = std::dynamic_pointer_cast<OSTM> (_FROM_);
                _FROM_OSTM_TWO_ = std::dynamic_pointer_cast<OSTM> (_FROM_TWO_);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_);
                tx->store(_FROM_OSTM_ONE_);
                tx->store(_FROM_OSTM_TWO_);
                tx->store(_TO_OSTM_);
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void MyTestCAse::_nesting_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
Testing nested transaction.
Parameters:
<em>to</em> pointer used in transaction
<em>from</em> pointer used in transaction
_tm Transaction Manager
_amount value used in the transaction
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED TRANSACTION
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED TRANSACTION IN THE NESTED TRANSACTION two_account_transfer function call
Commit changes
Definition at line 320 of file MyTestCAse.cpp.
References TM::_get_tx(), _two_account_transfer_(), and BANK::SetBalance().
Referenced by nested_hundred_thread_functionality(), and nested_thousand_thread_functionality().
                                                                                                        {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_);
    std::shared_ptr<BANK> _TO_BANK_, _FROM_BANK_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
            _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
            _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            std::shared_ptr<TX> txTwo = _tm._get_tx();
            bool nestedDone = false;
            while (!nestedDone) {
                _TO_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_to_));
                _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_from_));
                _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
                _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
                txTwo->store(_TO_OSTM_);
                txTwo->store(_FROM_OSTM_);
                _two_account_transfer_(_to_, _from_, _tm, _amount);
                nestedDone = txTwo->commit();
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void MyTestCAse::_one_account_transfer_ (std::shared_ptr< OSTM > _to_, TM & _tm, double _amount)
one object in the trasaction
Parameters:
<em>to</em> pointer used in transaction
_tm TRansaction Manager
_amount value used in the transaction
Register the two single account
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 74 of file MyTestCAse.cpp.
References TM::_get_tx(), BANK::SetBalance(), and tm.
Referenced by multi_threaded_single_object_test_with_ten_threads().
                                                                                        {
     std::shared_ptr<TX> tx = tm._get_tx();
    tx->_register(_to_);
    
    std::shared_ptr<OSTM> _TO_OSTM_;
    std::shared_ptr<BANK> _TO_;
    
    try {
        bool done = false;
        while (!done) {
            _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _TO_->SetBalance(_TO_->GetBalance() + (_amount ));
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_);
            tx->store(_TO_OSTM_);
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
    
    
    
}
void MyTestCAse::_six_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_one_, std::shared_ptr< OSTM > _from_two_, std::shared_ptr< OSTM > _from_three_, std::shared_ptr< OSTM > _from_four_, std::shared_ptr< OSTM > _from_five_, TM & _tm, double _amount)
Testing the transactions between six object.
Parameters:
<em>to</em> pointer used in transaction
<em>from_one</em> pointer used in transaction
<em>from_two</em> pointer used in transaction
<em>from_three</em> pointer used in transaction
<em>from_four</em> pointer used in transaction
<em>from_five</em> pointer used in transaction
_tm Transaction Manager
_amount value used in the transaction
Register the two single account
Required pointers to use in transaction
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 194 of file MyTestCAse.cpp.
References TM::_get_tx(), and BANK::SetBalance().
Referenced by threaded_functionality_hundred_threads_six_account(), and threaded_functionality_thousand_threads_six_account().
                                                                                                                                                                                                                                                             {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_one_);
    tx->_register(_from_two_);
    tx->_register(_from_three_);
    tx->_register(_from_four_);
    tx->_register(_from_five_);
    std::shared_ptr<OSTM> _TO_OSTM, _FROM_ONE_OSTM, _FROM_TWO_OSTM, _FROM_THREE_OSTM, _FROM_FOUR_OSTM, _FROM_FIVE_OSTM;
    std::shared_ptr<BANK> _TO_, _FROM_ONE_, _FROM_TWO_, _FROM_THREE_, _FROM_FOUR_, _FROM_FIVE_;
    try {
        bool done = false;
        while (!done) {
            _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_ONE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_one_));
            _FROM_TWO_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_two_));
            _FROM_THREE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_three_));
            _FROM_FOUR_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_four_));
            _FROM_FIVE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_five_));
            _TO_->SetBalance(_TO_->GetBalance() + (_amount * 5));
            _FROM_ONE_->SetBalance(_FROM_ONE_->GetBalance() - _amount);
            _FROM_TWO_->SetBalance(_FROM_TWO_->GetBalance() - _amount);
            _FROM_THREE_->SetBalance(_FROM_THREE_->GetBalance() - _amount);
            _FROM_FOUR_->SetBalance(_FROM_FOUR_->GetBalance() - _amount);
            _FROM_FIVE_->SetBalance(_FROM_FIVE_->GetBalance() - _amount);
            _TO_OSTM = std::dynamic_pointer_cast<OSTM> (_TO_);
            _FROM_ONE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_ONE_);
            _FROM_TWO_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_TWO_);
            _FROM_THREE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_THREE_);
            _FROM_FOUR_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_FOUR_);
            _FROM_FIVE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_FIVE_);
            tx->store(_TO_OSTM);
            tx->store(_FROM_ONE_OSTM);
            tx->store(_FROM_TWO_OSTM);
            tx->store(_FROM_THREE_OSTM);
            tx->store(_FROM_FOUR_OSTM);
            tx->store(_FROM_FIVE_OSTM);
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void MyTestCAse::_two_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM & tm, double _amount)
Testin transaction between two pointer.
Parameters:
<em>to</em> pointer used in transaction
<em>from</em> pointer used in transaction
tm TRansaction Manager
_amount value used in the transaction
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 266 of file MyTestCAse.cpp.
References TM::_get_tx(), and BANK::SetBalance().
Referenced by _nesting_(), multi_threaded_multiple_object_exchange_test(), threaded_functionality_hundred_threads(), and threaded_functionality_thousand_threads().
                                                                                                                     {
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_);
    std::shared_ptr<BANK> _TO_BANK_, _FROM_BANK_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
            _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
            _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void MyTestCAse::compare_Transaction_Manager_singleton_instance ()
This testing function comparing the Transaction Manager to make sure the application using a Singleton object.
Definition at line 896 of file MyTestCAse.cpp.
References TM::Instance(), and tm.
                                                               {
    TM& tm_copy = TM::Instance();
    CPPUNIT_ASSERT( tm == tm_copy );
}
void MyTestCAse::complex_threaded_functionality_hundred_threads ()
\ brief Testing the library consistent behavior LONG RUNNING PROCESS !!!! 1.5 - 2 Minutes !!! This test transfer 1 - 1 unit by 100 threads = 100 * 1 = 100 to every object in the collection (-6000) by single objects After transfer from account has -100 * 600 for both single objects and + 2 unit * 100 to every objects
Definition at line 412 of file MyTestCAse.cpp.
References _complex_transfer_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                               {
    tm._TX_EXIT();
     std::vector<std::shared_ptr < OSTM>>_customer_vec;
     for (int i = 0; i < 600; ++i) {
        if (i % 6 == 0) {
            std::shared_ptr<OSTM> sharedptr(new AIB(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOI(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOA(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SWBPLC(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new ULSTER(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new UNBL(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        }
    }
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 100;
    std::thread thArray[threadArraySize];
   
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_complex_transfer_, this, aib_ptr, boi_ptr, std::ref(_customer_vec), std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == -59500);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == -59500);
    
}
void MyTestCAse::complex_threaded_functionality_ten_threads ()
Testing the library consistent behavior This test transfer 1 - 1 unit by 10 threads = 10 * 1 = 10 to evey object in the collection (-600) by single objects After transfer from account has -10 * 600 for both single objects and + 2 unit * 10 to every objects.
Definition at line 467 of file MyTestCAse.cpp.
References _complex_transfer_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                           {
    tm._TX_EXIT();
    std::vector<std::shared_ptr < OSTM>>_customer_vec;
     for (int i = 0; i < 600; ++i) {
        if (i % 6 == 0) {
            std::shared_ptr<OSTM> sharedptr(new AIB(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOI(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOA(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SWBPLC(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new ULSTER(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new UNBL(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        }
    }
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 10;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_complex_transfer_, this, aib_ptr, boi_ptr, std::ref(_customer_vec), std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == -5500);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == -5500);
    
}
MyTestCAse::CPPUNIT_TEST (threaded_functionality_hundred_threads) [private]
MyTestCAse::CPPUNIT_TEST (threaded_functionality_thousand_threads) [private]
MyTestCAse::CPPUNIT_TEST (threaded_functionality_hundred_threads_six_account) [private]
MyTestCAse::CPPUNIT_TEST (threaded_functionality_thousand_threads_six_account) [private]
MyTestCAse::CPPUNIT_TEST (nested_hundred_thread_functionality) [private]
MyTestCAse::CPPUNIT_TEST (nested_thousand_thread_functionality) [private]
MyTestCAse::CPPUNIT_TEST (complex_threaded_functionality_hundred_threads) [private]
MyTestCAse::CPPUNIT_TEST (complex_threaded_functionality_ten_threads) [private]
MyTestCAse::CPPUNIT_TEST (two_object_transfer_complete) [private]
MyTestCAse::CPPUNIT_TEST (two_object_transfer_state_change) [private]
MyTestCAse::CPPUNIT_TEST (nested_transaction_object_test) [private]
MyTestCAse::CPPUNIT_TEST (multi_threaded_multiple_object_exchange_test) [private]
MyTestCAse::CPPUNIT_TEST (multi_threaded_single_object_test_with_ten_threads) [private]
MyTestCAse::CPPUNIT_TEST (single_threaded_multiple_object_test) [private]
MyTestCAse::CPPUNIT_TEST (multi_threaded_multiple_objects_test) [private]
MyTestCAse::CPPUNIT_TEST (increase_nesting) [private]
MyTestCAse::CPPUNIT_TEST (increase_nesting_fail) [private]
MyTestCAse::CPPUNIT_TEST (decrease_nesting) [private]
MyTestCAse::CPPUNIT_TEST (decrease_nesting_fail) [private]
MyTestCAse::CPPUNIT_TEST (two_object_transfer_state_change) [private]
MyTestCAse::CPPUNIT_TEST (compare_Transaction_Manager_singleton_instance) [private]
MyTestCAse::CPPUNIT_TEST (TM_get_thread_map) [private]
MyTestCAse::CPPUNIT_TEST_EXCEPTION (register_null_pointer_throw_runtime_error, std::runtime_error) [private]
MyTestCAse::CPPUNIT_TEST_EXCEPTION (object_not_registered_throw_runtime_error, std::runtime_error) [private]
MyTestCAse::CPPUNIT_TEST_EXCEPTION (store_null_pointer_throw_runtime_error, std::runtime_error) [private]
MyTestCAse::CPPUNIT_TEST_SUITE (MyTestCAse) [private]
MyTestCAse::CPPUNIT_TEST_SUITE_END () [private]
void MyTestCAse::decrease_nesting ()
Testing the nesting decrease function.
Definition at line 853 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                 {
    
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->setTx_nesting_level(10);
    tx->_decrease_tx_nesting();
    tx->_decrease_tx_nesting();
    tx->_decrease_tx_nesting();
    
    CPPUNIT_ASSERT( tx->getTx_nesting_level() == 7);
    tx->_decrease_tx_nesting();
    CPPUNIT_ASSERT( tx->getTx_nesting_level() == 6);
}
void MyTestCAse::decrease_nesting_fail ()
Testing the nesting decrease function to make sure the variable state changing.
Definition at line 881 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                      {
    
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->setTx_nesting_level(10);
    tx->_decrease_tx_nesting();
    tx->_decrease_tx_nesting();
    tx->_decrease_tx_nesting();
    
    CPPUNIT_ASSERT( !(tx->getTx_nesting_level() == 10));
    tx->_decrease_tx_nesting();
    CPPUNIT_ASSERT( !(tx->getTx_nesting_level() == 12));
}
void MyTestCAse::increase_nesting ()
Testing the nesting increase function.
Definition at line 841 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                 {
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->setTx_nesting_level(0);
    tx->_increase_tx_nesting();
    tx->_increase_tx_nesting();
    tx->_increase_tx_nesting();
    CPPUNIT_ASSERT( tx->getTx_nesting_level() == 3);
}
void MyTestCAse::increase_nesting_fail ()
Testing the nesting increase function to make sure the variable state changing.
Definition at line 868 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                      {
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->setTx_nesting_level(0);
    tx->_increase_tx_nesting();
    tx->_increase_tx_nesting();
    tx->_increase_tx_nesting();
    CPPUNIT_ASSERT( !(tx->getTx_nesting_level() == 0));
}
void MyTestCAse::multi_threaded_multiple_object_exchange_test ()
Design Manual document based tests Implementations.
1.
Single thread multiple transactional object exchange test
2.
Multi-threaded single Object test with 10 threads.
3.
Single-threaded multiple object test.
4.
Multi-threaded multiple Objects test.
1.
Single thread multiple transactional object exchange test
Definition at line 922 of file MyTestCAse.cpp.
References _two_account_transfer_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                             {
    //ten threads using same objects
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 100, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 100, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 5;
    int threadArraySize = 10;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_two_account_transfer_, this, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == 50);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 150);
    
}
void MyTestCAse::multi_threaded_multiple_objects_test ()
4.
Multi-threaded multiple Objects test.
Definition at line 1040 of file MyTestCAse.cpp.
References _collection_bject_(), TM::_TX_EXIT(), and tm.
                                                     {
    //three threads all thread use different objects
    tm._TX_EXIT();
    std::vector<std::shared_ptr < OSTM>>_customer_vec;
     for (int i = 0; i < 10; ++i) {
        if (i % 6 == 0) {
            std::shared_ptr<OSTM> sharedptr(new AIB(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOI(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOA(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SWBPLC(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new ULSTER(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new UNBL(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        }
    }
    std::shared_ptr<BANK> _one_, _two_, _three_, _four_, _five_, _six_;
    int loop = 1;
    int transferAmount = 1;
    int threadArraySize = 10;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_collection_bject_, this, std::ref(_customer_vec), std::ref(tm), transferAmount , loop);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _one_ = std::dynamic_pointer_cast<BANK> (_customer_vec[0]);
    _two_ = std::dynamic_pointer_cast<BANK> (_customer_vec[1]);
    _three_ = std::dynamic_pointer_cast<BANK> (_customer_vec[2]);
    _four_ = std::dynamic_pointer_cast<BANK> (_customer_vec[3]);
    _five_ = std::dynamic_pointer_cast<BANK> (_customer_vec[4]);
    _six_ = std::dynamic_pointer_cast<BANK> (_customer_vec[5]);
 
    CPPUNIT_ASSERT(_one_->GetBalance() == 20);
    CPPUNIT_ASSERT(_two_->GetBalance() == 20);
    CPPUNIT_ASSERT(_three_->GetBalance() == 20);
    CPPUNIT_ASSERT(_four_->GetBalance() == 20);
    CPPUNIT_ASSERT(_five_->GetBalance() == 20);
    CPPUNIT_ASSERT(_six_->GetBalance() == 20);
}
void MyTestCAse::multi_threaded_single_object_test_with_ten_threads ()
2.
Multi-threaded single Object test with 10 threads.
Definition at line 954 of file MyTestCAse.cpp.
References _one_account_transfer_(), TM::_TX_EXIT(), aib_ptr, and tm.
                                                                   {
    //one object ten threads
    tm._TX_EXIT();
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 100, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 10;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_one_account_transfer_, this, aib_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 110);
}
void MyTestCAse::nested_hundred_thread_functionality ()
Testing the library consistent behavior Nested threaded function : 3 level of nesting, every thread transfer 3 unit from one object to the another object so, at end of the 100 thransaction the from object transfer 100 * 3 (300) to the another object 500 - 300 = 200 AND 500 + 300 = 800.
Definition at line 680 of file MyTestCAse.cpp.
References _nesting_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                    {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 100;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_nesting_, this, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == 200);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 800);
    
}
void MyTestCAse::nested_thousand_thread_functionality ()
Testing the library consistent behavior Nested threaded function : 3 level of nesting, every thread transfer 3 unit from one object to the another object so, at end of the 100 thransaction the from object transfer 1000 * 3 (3000) to the another object 500 - 3000 = -2500 AND 500 + 3000 = 3500.
Definition at line 715 of file MyTestCAse.cpp.
References _nesting_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                     {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 1000;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_nesting_, this, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == -2500);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 3500);
    
}
void MyTestCAse::nested_transaction_object_test ()
Testing the library consistent behavior This test calls the nested function, where every thread transfer 3 unit in the nested transactions. Because this test in not threaded, the 3 level deep nesting transfer 3*20 = 60 from one object to the another object. 500 - 60 = 440 AND 500 + 60 = 560.
Definition at line 787 of file MyTestCAse.cpp.
References client::_nesting_(), TM::_TX_EXIT(), a, tm, ulster_ptr, and unbl_ptr.
                                               {
    tm._TX_EXIT();
    std::shared_ptr<OSTM> ulster_ptr(new ULSTER(500, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> unbl_ptr(new UNBL(600, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    a->_nesting_(ulster_ptr, unbl_ptr, tm, 20);
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (unbl_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (ulster_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == 440);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 560);
    
}
void MyTestCAse::object_not_registered_throw_runtime_error ()
The library function throws runtime error if the client application tries to load a working pointer from the library of a not registered pointer by the client application. Runtime error should be thrown.
Definition at line 818 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                                          {
    
    std::shared_ptr<OSTM> not_registered_object(new BOA(300, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->load(not_registered_object);
}
void MyTestCAse::register_null_pointer_throw_runtime_error ()
Definition at line 805 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                                          {
    
    std::shared_ptr<OSTM> null_ptr;
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->_register(null_ptr);
}
void MyTestCAse::setUp () [inline]
Definition at line 108 of file MyTestCAse.h.
  {
      a = new client(1);
      b = new client(1);
      c = new client(1);
  }
void MyTestCAse::single_threaded_multiple_object_test ()
3.
Single-threaded multiple object test.
Definition at line 983 of file MyTestCAse.cpp.
References _collection_bject_(), TM::_TX_EXIT(), and tm.
                                                     {
    //one transaction multiple objects six object function
    tm._TX_EXIT();
    std::vector<std::shared_ptr < OSTM>>_customer_vec;
     for (int i = 0; i < 10; ++i) {
        if (i % 6 == 0) {
            std::shared_ptr<OSTM> sharedptr(new AIB(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOI(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOA(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SWBPLC(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new ULSTER(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new UNBL(i, 10, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        }
    }
    std::shared_ptr<BANK> _one_, _two_, _three_, _four_, _five_, _six_;
    int loop = 5;
    int transferAmount = 1;
    int threadArraySize = 1;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_collection_bject_, this, std::ref(_customer_vec), std::ref(tm), transferAmount , loop);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _one_ = std::dynamic_pointer_cast<BANK> (_customer_vec[0]);
    _two_ = std::dynamic_pointer_cast<BANK> (_customer_vec[1]);
    _three_ = std::dynamic_pointer_cast<BANK> (_customer_vec[2]);
    _four_ = std::dynamic_pointer_cast<BANK> (_customer_vec[3]);
    _five_ = std::dynamic_pointer_cast<BANK> (_customer_vec[4]);
    _six_ = std::dynamic_pointer_cast<BANK> (_customer_vec[5]);
    
    CPPUNIT_ASSERT(_one_->GetBalance() == 15);
    CPPUNIT_ASSERT(_two_->GetBalance() == 15);
    CPPUNIT_ASSERT(_three_->GetBalance() == 15);
    CPPUNIT_ASSERT(_four_->GetBalance() == 15);
    CPPUNIT_ASSERT(_five_->GetBalance() == 15);
    CPPUNIT_ASSERT(_six_->GetBalance() == 15);
}
void MyTestCAse::store_null_pointer_throw_runtime_error ()
The test function throws runtime error if the client application tries to store the changed working pointer as a null pointer. Runtime error should be thrown.
Definition at line 831 of file MyTestCAse.cpp.
References TM::_get_tx(), and tm.
                                                       {
    
    std::shared_ptr<OSTM> null_ptr;
    std::shared_ptr<TX> tx = tm._get_tx();
    tx->store(null_ptr);
}
void MyTestCAse::tearDown () [inline]
Definition at line 116 of file MyTestCAse.h.
  {
      delete a;
      delete b;
      delete c;
  }
void MyTestCAse::threaded_functionality_hundred_threads ()
Testing the library consistent behavior This test transfer 1 unit by 100 threads = 100 *1 = 100 After transfer from account has -100, and to account has +100
Definition at line 523 of file MyTestCAse.cpp.
References _two_account_transfer_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                       {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 100;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_two_account_transfer_, this, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == 400);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 600);
    
}
void MyTestCAse::threaded_functionality_hundred_threads_six_account ()
Testing the library consistent behavior This test transfer 1 unit by 100 threads from five account to one account After transfer from account has - 100*1 from the accounts, and to account has +100*5.
Definition at line 589 of file MyTestCAse.cpp.
References _six_account_transfer_(), TM::_TX_EXIT(), aib_ptr, boa_ptr, boi_ptr, swplc_ptr, tm, ulster_ptr, and unbl_ptr.
                                                                   {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_ONE,_FROM_BANK_TWO,_FROM_BANK_THREE, _FROM_BANK_FOUR, _FROM_BANK_FIVE;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boa_ptr(new BOA(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> ulster_ptr(new ULSTER(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> unbl_ptr(new UNBL(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> swplc_ptr(new SWBPLC(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 100;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_six_account_transfer_, this, aib_ptr, boi_ptr, boa_ptr, ulster_ptr, unbl_ptr, swplc_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ONE = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _FROM_BANK_TWO = std::dynamic_pointer_cast<BANK> (boa_ptr);
    _FROM_BANK_THREE = std::dynamic_pointer_cast<BANK> (ulster_ptr);
    _FROM_BANK_FOUR = std::dynamic_pointer_cast<BANK> (unbl_ptr);
    _FROM_BANK_FIVE = std::dynamic_pointer_cast<BANK> (swplc_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_ONE->GetBalance() == 400);
    CPPUNIT_ASSERT(_FROM_BANK_TWO->GetBalance() == 400);
    CPPUNIT_ASSERT(_FROM_BANK_THREE->GetBalance() == 400);
    CPPUNIT_ASSERT(_FROM_BANK_FOUR->GetBalance() == 400);
    CPPUNIT_ASSERT(_FROM_BANK_FIVE->GetBalance() == 400);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 1000);
    
}
void MyTestCAse::threaded_functionality_thousand_threads ()
Testing the library consistent behavior This test transfer 1 unit by 1000 threads = 1000 *1 = 100 After transfer from account has -1000, and to account has +1000.
Definition at line 556 of file MyTestCAse.cpp.
References _two_account_transfer_(), TM::_TX_EXIT(), aib_ptr, boi_ptr, and tm.
                                                        {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 1000;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_two_account_transfer_, this, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == -500);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 1500);
    
}
void MyTestCAse::threaded_functionality_thousand_threads_six_account ()
Testing the library consistent behavior This test transfer 1 unit by 1000 threads from five account to one account After transfer from account has - 1000*1 from the accounts, and to account has +1000*5.
Definition at line 634 of file MyTestCAse.cpp.
References _six_account_transfer_(), TM::_TX_EXIT(), aib_ptr, boa_ptr, boi_ptr, swplc_ptr, tm, ulster_ptr, and unbl_ptr.
                                                                    {
    tm._TX_EXIT();
    std::shared_ptr<BANK> _FROM_BANK_ONE,_FROM_BANK_TWO,_FROM_BANK_THREE, _FROM_BANK_FOUR, _FROM_BANK_FIVE;
    std::shared_ptr<BANK> _TO_BANK_;
    
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boa_ptr(new BOA(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> ulster_ptr(new ULSTER(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> unbl_ptr(new UNBL(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> swplc_ptr(new SWBPLC(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    
    int transferAmount = 1;
    int threadArraySize = 1000;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i] = std::thread(&MyTestCAse::_six_account_transfer_, this, aib_ptr, boi_ptr, boa_ptr, ulster_ptr, unbl_ptr, swplc_ptr, std::ref(tm), transferAmount);
    }
    
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    
    _FROM_BANK_ONE = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _FROM_BANK_TWO = std::dynamic_pointer_cast<BANK> (boa_ptr);
    _FROM_BANK_THREE = std::dynamic_pointer_cast<BANK> (ulster_ptr);
    _FROM_BANK_FOUR = std::dynamic_pointer_cast<BANK> (unbl_ptr);
    _FROM_BANK_FIVE = std::dynamic_pointer_cast<BANK> (swplc_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_ONE->GetBalance() == -500);
    CPPUNIT_ASSERT(_FROM_BANK_TWO->GetBalance() == -500);
    CPPUNIT_ASSERT(_FROM_BANK_THREE->GetBalance() == -500);
    CPPUNIT_ASSERT(_FROM_BANK_FOUR->GetBalance() == -500);
    CPPUNIT_ASSERT(_FROM_BANK_FIVE->GetBalance() == -500);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 5500);
    
}
void MyTestCAse::TM_get_thread_map ()
This function testing the returned map from the Transaction Manager class.
Definition at line 903 of file MyTestCAse.cpp.
References TM::get_thread_Map(), and tm.
                                  {
    
    std::map< std::thread::id, int > localMap;
    std::map< std::thread::id, int > tmMap = tm.get_thread_Map();
    
    CPPUNIT_ASSERT(localMap == tmMap);
}
void MyTestCAse::two_object_transfer_complete ()
Testing the library consistent behavior Transfer between two objects : the from object transfer 20 to the another object 500 - 20 = 480 AND 500 + 20 = 520.
Definition at line 748 of file MyTestCAse.cpp.
References client::_two_account_transfer_(), TM::_TX_EXIT(), a, aib_ptr, boi_ptr, and tm.
                                             {
    tm._TX_EXIT();
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    a->_two_account_transfer_(aib_ptr, boi_ptr, tm, 20);
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boi_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (aib_ptr);
    
    CPPUNIT_ASSERT(_FROM_BANK_->GetBalance() == 480);
    CPPUNIT_ASSERT(_TO_BANK_->GetBalance() == 520);
    
}
void MyTestCAse::two_object_transfer_state_change ()
This function proves the objects states must change from the base values.
Definition at line 765 of file MyTestCAse.cpp.
References client::_two_account_transfer_(), TM::_TX_EXIT(), a, boa_ptr, swplc_ptr, and tm.
                                                 {
    tm._TX_EXIT();
    std::shared_ptr<OSTM> boa_ptr(new BOA(300, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> swplc_ptr(new SWBPLC(400, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<BANK> _FROM_BANK_;
    std::shared_ptr<BANK> _TO_BANK_;
    a->_two_account_transfer_(swplc_ptr, boa_ptr, tm, 20);
    _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (boa_ptr);
    _TO_BANK_ = std::dynamic_pointer_cast<BANK> (swplc_ptr);
   
    CPPUNIT_ASSERT(!(_FROM_BANK_->GetBalance() == 500));
    CPPUNIT_ASSERT(!(_TO_BANK_->GetBalance() == 500));
    
}
Member Data Documentation
client* MyTestCAse::a [private]
Definition at line 126 of file MyTestCAse.h.
Referenced by nested_transaction_object_test(), two_object_transfer_complete(), and two_object_transfer_state_change().
std::shared_ptr<OSTM> MyTestCAse::aib_ptr
Definition at line 66 of file MyTestCAse.h.
Referenced by complex_threaded_functionality_hundred_threads(), complex_threaded_functionality_ten_threads(), multi_threaded_multiple_object_exchange_test(), multi_threaded_single_object_test_with_ten_threads(), nested_hundred_thread_functionality(), nested_thousand_thread_functionality(), threaded_functionality_hundred_threads(), threaded_functionality_hundred_threads_six_account(), threaded_functionality_thousand_threads(), threaded_functionality_thousand_threads_six_account(), and two_object_transfer_complete().
client * MyTestCAse::b [private]
Definition at line 126 of file MyTestCAse.h.
std::shared_ptr<OSTM> MyTestCAse::boa_ptr
Definition at line 68 of file MyTestCAse.h.
Referenced by threaded_functionality_hundred_threads_six_account(), threaded_functionality_thousand_threads_six_account(), and two_object_transfer_state_change().
std::shared_ptr<OSTM> MyTestCAse::boi_ptr
Definition at line 67 of file MyTestCAse.h.
Referenced by complex_threaded_functionality_hundred_threads(), complex_threaded_functionality_ten_threads(), multi_threaded_multiple_object_exchange_test(), nested_hundred_thread_functionality(), nested_thousand_thread_functionality(), threaded_functionality_hundred_threads(), threaded_functionality_hundred_threads_six_account(), threaded_functionality_thousand_threads(), threaded_functionality_thousand_threads_six_account(), and two_object_transfer_complete().
client * MyTestCAse::c [private]
Definition at line 126 of file MyTestCAse.h.
std::shared_ptr<OSTM> MyTestCAse::swplc_ptr
Definition at line 69 of file MyTestCAse.h.
Referenced by threaded_functionality_hundred_threads_six_account(), threaded_functionality_thousand_threads_six_account(), and two_object_transfer_state_change().
TM& MyTestCAse::tm = TM::Instance()
Definition at line 65 of file MyTestCAse.h.
Referenced by _one_account_transfer_(), compare_Transaction_Manager_singleton_instance(), complex_threaded_functionality_hundred_threads(), complex_threaded_functionality_ten_threads(), decrease_nesting(), decrease_nesting_fail(), increase_nesting(), increase_nesting_fail(), multi_threaded_multiple_object_exchange_test(), multi_threaded_multiple_objects_test(), multi_threaded_single_object_test_with_ten_threads(), nested_hundred_thread_functionality(), nested_thousand_thread_functionality(), nested_transaction_object_test(), object_not_registered_throw_runtime_error(), register_null_pointer_throw_runtime_error(), single_threaded_multiple_object_test(), store_null_pointer_throw_runtime_error(), threaded_functionality_hundred_threads(), threaded_functionality_hundred_threads_six_account(), threaded_functionality_thousand_threads(), threaded_functionality_thousand_threads_six_account(), TM_get_thread_map(), two_object_transfer_complete(), and two_object_transfer_state_change().
std::shared_ptr<OSTM> MyTestCAse::ulster_ptr
Definition at line 70 of file MyTestCAse.h.
Referenced by nested_transaction_object_test(), threaded_functionality_hundred_threads_six_account(), and threaded_functionality_thousand_threads_six_account().
std::shared_ptr<OSTM> MyTestCAse::unbl_ptr
Definition at line 71 of file MyTestCAse.h.
Referenced by nested_transaction_object_test(), threaded_functionality_hundred_threads_six_account(), and threaded_functionality_thousand_threads_six_account().
Author
Generated automatically by Doxygen for CppUnit test STM from the source code.