ULSTER
NAME
ULSTER -
SYNOPSIS
#include <ULSTER.h>
Inherits BANK.
Public Member Functions
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
OSTM required virtual method for deep copy.
virtual int GetAccountNumber () const
virtual std::string GetAddress () const
virtual double GetBalance () const
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
OSTM required virtual method for returning a pointer that is copy of the original pointer.
virtual std::string GetFirstName () const
virtual std::string GetFullname () const
virtual std::string GetLastName () const
ULSTER operator= (const ULSTER &orig)
virtual void SetAccountNumber (int accountNumber)
virtual void SetAddress (std::string address)
virtual void SetBalance (double balance)
virtual void SetFirstName (std::string firstName)
virtual void SetFullname (std::string fullname)
virtual void SetLastName (std::string lastName)
virtual void toString ()
OSTM required virtual method for display object.
ULSTER ()
ULSTER (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)
ULSTER (std::shared_ptr< BANK > obj, int _version, int _unique_id)
ULSTER (const ULSTER &orig)
virtual ~ULSTER ()
Private Attributes
int accountNumber
std::string address
double balance
std::string firstName
std::string fullname
std::string lastName
Detailed Description
Definition at line 19 of file ULSTER.h.
Constructor & Destructor Documentation
ULSTER::ULSTER () [inline]
Definition at line 24 of file ULSTER.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
Referenced by getBaseCopy(), and ULSTER().
             : BANK() {
        this->accountNumber = 0;
        this->balance = 50;
        this->firstName = "Joe";
        this->lastName = "Blog";
        this->address = "High street, Carlow";
        this->fullname = firstName + " " + lastName;
    };
ULSTER::ULSTER (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address) [inline]
Definition at line 35 of file ULSTER.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
                                                                                                          : BANK() {
        this->accountNumber = accountNumber;
        this->balance = balance;
        this->firstName = firstName;
        this->lastName = lastName;
        this->address = address;
        this->fullname = firstName + " " + lastName;
    };
ULSTER::ULSTER (std::shared_ptr< BANK > obj, int _version, int _unique_id) [inline]
Definition at line 46 of file ULSTER.h.
References accountNumber, address, balance, firstName, fullname, lastName, and ULSTER().
                                                                  : BANK(_version, _unique_id) {
        this->accountNumber = obj->GetAccountNumber();
        this->balance = obj->GetBalance();
        this->firstName = obj->GetFirstName();
        this->lastName = obj->GetLastName();
        this->address = obj->GetAddress();
        this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
    };
ULSTER::ULSTER (const ULSTER & orig)
Definition at line 13 of file ULSTER.cpp.
                                 {
}
ULSTER::~ULSTER () [virtual]
Definition at line 16 of file ULSTER.cpp.
Referenced by operator=().
                {
}
Member Function Documentation
void ULSTER::copy (std::shared_ptr< OSTM > from, std::shared_ptr< OSTM > to) [virtual]
OSTM required virtual method for deep copy.
Reimplemented from OSTM.
Definition at line 35 of file ULSTER.cpp.
References OSTM::Set_Unique_ID().
Referenced by operator=().
                                                                 {
    std::shared_ptr<ULSTER> objTO = std::dynamic_pointer_cast<ULSTER>(to);
    std::shared_ptr<ULSTER> objFROM = std::dynamic_pointer_cast<ULSTER>(from);
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    objTO->SetAccountNumber(objFROM->GetAccountNumber());
    objTO->SetBalance(objFROM->GetBalance());
    
}
int ULSTER::GetAccountNumber () const [virtual]
Reimplemented from BANK.
Definition at line 78 of file ULSTER.cpp.
References accountNumber.
Referenced by operator=(), and toString().
                                   {
    return accountNumber;
}
std::string ULSTER::GetAddress () const [virtual]
Reimplemented from BANK.
Definition at line 62 of file ULSTER.cpp.
References address.
Referenced by operator=().
                                   {
    return address;
}
double ULSTER::GetBalance () const [virtual]
Reimplemented from BANK.
Definition at line 70 of file ULSTER.cpp.
References balance.
Referenced by operator=(), and toString().
                                {
    return balance;
}
std::shared_ptr< OSTM > ULSTER::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
OSTM required virtual method for returning a pointer that is copy of the original pointer.
Reimplemented from OSTM.
Definition at line 23 of file ULSTER.cpp.
References ULSTER().
Referenced by operator=().
{
    std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
    std::shared_ptr<BANK> obj(new ULSTER(objTO,object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
std::string ULSTER::GetFirstName () const [virtual]
Reimplemented from BANK.
Definition at line 94 of file ULSTER.cpp.
References firstName.
Referenced by operator=(), and toString().
                                     {
    return firstName;
}
std::string ULSTER::GetFullname () const [virtual]
Reimplemented from BANK.
Definition at line 102 of file ULSTER.cpp.
References fullname.
Referenced by operator=().
                                    {
    return fullname;
}
std::string ULSTER::GetLastName () const [virtual]
Reimplemented from BANK.
Definition at line 86 of file ULSTER.cpp.
References lastName.
Referenced by operator=(), and toString().
                                    {
    return lastName;
}
ULSTER ULSTER::operator= (const ULSTER & orig) [inline]
Definition at line 62 of file ULSTER.h.
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~ULSTER().
{};
void ULSTER::SetAccountNumber (int accountNumber) [virtual]
Reimplemented from BANK.
Definition at line 74 of file ULSTER.cpp.
References accountNumber.
Referenced by operator=().
                                               {
    this->accountNumber = accountNumber;
}
void ULSTER::SetAddress (std::string address) [virtual]
Reimplemented from BANK.
Definition at line 58 of file ULSTER.cpp.
References address.
Referenced by operator=().
                                         {
    this->address = address;
}
void ULSTER::SetBalance (double balance) [virtual]
Reimplemented from BANK.
Definition at line 66 of file ULSTER.cpp.
References balance.
Referenced by operator=().
                                      {
    this->balance = balance;
}
void ULSTER::SetFirstName (std::string firstName) [virtual]
Reimplemented from BANK.
Definition at line 90 of file ULSTER.cpp.
References firstName.
Referenced by operator=().
                                             {
    this->firstName = firstName;
}
void ULSTER::SetFullname (std::string fullname) [virtual]
Reimplemented from BANK.
Definition at line 98 of file ULSTER.cpp.
References fullname.
Referenced by operator=().
                                           {
    this->fullname = fullname;
}
void ULSTER::SetLastName (std::string lastName) [virtual]
Reimplemented from BANK.
Definition at line 82 of file ULSTER.cpp.
References lastName.
Referenced by operator=().
                                           {
    this->lastName = lastName;
}
void ULSTER::toString () [virtual]
OSTM required virtual method for display object.
Reimplemented from OSTM.
Definition at line 53 of file ULSTER.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName().
Referenced by operator=().
{
   std::cout << "\nULSTER BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int ULSTER::accountNumber [private]
Definition at line 95 of file ULSTER.h.
Referenced by GetAccountNumber(), operator=(), SetAccountNumber(), and ULSTER().
std::string ULSTER::address [private]
Definition at line 97 of file ULSTER.h.
Referenced by GetAddress(), operator=(), SetAddress(), and ULSTER().
double ULSTER::balance [private]
Definition at line 96 of file ULSTER.h.
Referenced by GetBalance(), operator=(), SetBalance(), and ULSTER().
std::string ULSTER::firstName [private]
Definition at line 93 of file ULSTER.h.
Referenced by GetFirstName(), operator=(), SetFirstName(), and ULSTER().
std::string ULSTER::fullname [private]
Definition at line 92 of file ULSTER.h.
Referenced by GetFullname(), operator=(), SetFullname(), and ULSTER().
std::string ULSTER::lastName [private]
Definition at line 94 of file ULSTER.h.
Referenced by GetLastName(), operator=(), SetLastName(), and ULSTER().
Author
Generated automatically by Doxygen for CppUnit test STM from the source code.