.TH "UNBL" 3 "Sun Apr 1 2018" "CppUnit test STM" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UNBL \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UNBL\&.h>\fP
.PP
Inherits \fBBANK\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)"
.br
.RI "\fI\fBOSTM\fP required virtual method for deep copy\&. \fP"
.ti -1c
.RI "virtual int \fBGetAccountNumber\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetAddress\fP () const "
.br
.ti -1c
.RI "virtual double \fBGetBalance\fP () const "
.br
.ti -1c
.RI "virtual std::shared_ptr< \fBOSTM\fP > \fBgetBaseCopy\fP (std::shared_ptr< \fBOSTM\fP > object)"
.br
.RI "\fI\fBOSTM\fP required virtual method for returning a pointer that is copy of the original pointer\&. \fP"
.ti -1c
.RI "virtual std::string \fBGetFirstName\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetFullname\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetLastName\fP () const "
.br
.ti -1c
.RI "\fBUNBL\fP \fBoperator=\fP (const \fBUNBL\fP &orig)"
.br
.ti -1c
.RI "virtual void \fBSetAccountNumber\fP (int \fBaccountNumber\fP)"
.br
.ti -1c
.RI "virtual void \fBSetAddress\fP (std::string \fBaddress\fP)"
.br
.ti -1c
.RI "virtual void \fBSetBalance\fP (double \fBbalance\fP)"
.br
.ti -1c
.RI "virtual void \fBSetFirstName\fP (std::string \fBfirstName\fP)"
.br
.ti -1c
.RI "virtual void \fBSetFullname\fP (std::string \fBfullname\fP)"
.br
.ti -1c
.RI "virtual void \fBSetLastName\fP (std::string \fBlastName\fP)"
.br
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI\fBOSTM\fP required virtual method for display object\&. \fP"
.ti -1c
.RI "\fBUNBL\fP ()"
.br
.ti -1c
.RI "\fBUNBL\fP (int \fBaccountNumber\fP, double \fBbalance\fP, std::string \fBfirstName\fP, std::string \fBlastName\fP, std::string \fBaddress\fP)"
.br
.ti -1c
.RI "\fBUNBL\fP (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBUNBL\fP (const \fBUNBL\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~UNBL\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBaccountNumber\fP"
.br
.ti -1c
.RI "std::string \fBaddress\fP"
.br
.ti -1c
.RI "double \fBbalance\fP"
.br
.ti -1c
.RI "std::string \fBfirstName\fP"
.br
.ti -1c
.RI "std::string \fBfullname\fP"
.br
.ti -1c
.RI "std::string \fBlastName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file UNBL\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UNBL::UNBL ()\fC [inline]\fP"

.PP
Definition at line 22 of file UNBL\&.h\&.
.PP
References accountNumber, address, balance, firstName, fullname, and lastName\&.
.PP
Referenced by getBaseCopy(), and UNBL()\&.
.PP
.nf
22            : BANK() {
23         this->accountNumber = 0;
24         this->balance = 50;
25         this->firstName = "Joe";
26         this->lastName = "Blog";
27         this->address = "High street, Carlow";
28         this->fullname = firstName + " " + lastName;
29     };
.fi
.SS "UNBL::UNBL (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)\fC [inline]\fP"

.PP
Definition at line 33 of file UNBL\&.h\&.
.PP
References accountNumber, address, balance, firstName, fullname, and lastName\&.
.PP
.nf
33                                                                                                         : BANK() {
34         this->accountNumber = accountNumber;
35         this->balance = balance;
36         this->firstName = firstName;
37         this->lastName = lastName;
38         this->address = address;
39         this->fullname = firstName + " " + lastName;
40     };
.fi
.SS "UNBL::UNBL (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)\fC [inline]\fP"

.PP
Definition at line 44 of file UNBL\&.h\&.
.PP
References accountNumber, address, balance, firstName, fullname, lastName, and UNBL()\&.
.PP
.nf
44                                                                 : BANK(_version, _unique_id) {
45  
46         this->accountNumber = obj->GetAccountNumber();
47         this->balance = obj->GetBalance();
48         this->firstName = obj->GetFirstName();
49         this->lastName = obj->GetLastName();
50         this->address = obj->GetAddress();
51         this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
52     };
.fi
.SS "UNBL::UNBL (const \fBUNBL\fP & orig)"

.PP
Definition at line 11 of file UNBL\&.cpp\&.
.PP
.nf
11                            {
12 }
.fi
.SS "UNBL::~UNBL ()\fC [virtual]\fP"

.PP
Definition at line 14 of file UNBL\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
14             {
15 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void UNBL::copy (std::shared_ptr< \fBOSTM\fP > from, std::shared_ptr< \fBOSTM\fP > to)\fC [virtual]\fP"

.PP
\fBOSTM\fP required virtual method for deep copy\&. 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 33 of file UNBL\&.cpp\&.
.PP
References OSTM::Set_Unique_ID()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
33                                                                {
34 
35     std::shared_ptr<UNBL> objTO = std::dynamic_pointer_cast<UNBL>(to);
36     std::shared_ptr<UNBL> objFROM = std::dynamic_pointer_cast<UNBL>(from);
37     objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
38     objTO->Set_Version(objFROM->Get_Version());
39     objTO->SetAccountNumber(objFROM->GetAccountNumber());
40     objTO->SetBalance(objFROM->GetBalance());
41    
42 }
.fi
.SS "int UNBL::GetAccountNumber () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 75 of file UNBL\&.cpp\&.
.PP
References accountNumber\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
75                                  {
76     return accountNumber;
77 }
.fi
.SS "std::string UNBL::GetAddress () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 59 of file UNBL\&.cpp\&.
.PP
References address\&.
.PP
Referenced by operator=()\&.
.PP
.nf
59                                  {
60     return address;
61 }
.fi
.SS "double UNBL::GetBalance () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 67 of file UNBL\&.cpp\&.
.PP
References balance\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
67                               {
68     return balance;
69 }
.fi
.SS "std::shared_ptr< \fBOSTM\fP > UNBL::getBaseCopy (std::shared_ptr< \fBOSTM\fP > object)\fC [virtual]\fP"

.PP
\fBOSTM\fP required virtual method for returning a pointer that is copy of the original pointer\&. 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 21 of file UNBL\&.cpp\&.
.PP
References UNBL()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
22 {
23     std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
24     std::shared_ptr<BANK> obj(new UNBL(objTO,object->Get_Version(),object->Get_Unique_ID())); 
25     std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);                                  
26     return ostm_obj;
27 }
.fi
.SS "std::string UNBL::GetFirstName () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 91 of file UNBL\&.cpp\&.
.PP
References firstName\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
91                                    {
92     return firstName;
93 }
.fi
.SS "std::string UNBL::GetFullname () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 99 of file UNBL\&.cpp\&.
.PP
References fullname\&.
.PP
Referenced by operator=()\&.
.PP
.nf
99                                   {
100     return fullname;
101 }
.fi
.SS "std::string UNBL::GetLastName () const\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 83 of file UNBL\&.cpp\&.
.PP
References lastName\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
83                                   {
84     return lastName;
85 }
.fi
.SS "\fBUNBL\fP UNBL::operator= (const \fBUNBL\fP & orig)\fC [inline]\fP"

.PP
Definition at line 60 of file UNBL\&.h\&.
.PP
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~UNBL()\&.
.PP
.nf
60 {};
.fi
.SS "void UNBL::SetAccountNumber (int accountNumber)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 71 of file UNBL\&.cpp\&.
.PP
References accountNumber\&.
.PP
Referenced by operator=()\&.
.PP
.nf
71                                              {
72     this->accountNumber = accountNumber;
73 }
.fi
.SS "void UNBL::SetAddress (std::string address)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 55 of file UNBL\&.cpp\&.
.PP
References address\&.
.PP
Referenced by operator=()\&.
.PP
.nf
55                                        {
56     this->address = address;
57 }
.fi
.SS "void UNBL::SetBalance (double balance)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 63 of file UNBL\&.cpp\&.
.PP
References balance\&.
.PP
Referenced by operator=()\&.
.PP
.nf
63                                     {
64     this->balance = balance;
65 }
.fi
.SS "void UNBL::SetFirstName (std::string firstName)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 87 of file UNBL\&.cpp\&.
.PP
References firstName\&.
.PP
Referenced by operator=()\&.
.PP
.nf
87                                            {
88     this->firstName = firstName;
89 }
.fi
.SS "void UNBL::SetFullname (std::string fullname)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 95 of file UNBL\&.cpp\&.
.PP
References fullname\&.
.PP
Referenced by operator=()\&.
.PP
.nf
95                                          {
96     this->fullname = fullname;
97 }
.fi
.SS "void UNBL::SetLastName (std::string lastName)\fC [virtual]\fP"

.PP
Reimplemented from \fBBANK\fP\&.
.PP
Definition at line 79 of file UNBL\&.cpp\&.
.PP
References lastName\&.
.PP
Referenced by operator=()\&.
.PP
.nf
79                                          {
80     this->lastName = lastName;
81 }
.fi
.SS "void UNBL::toString ()\fC [virtual]\fP"

.PP
\fBOSTM\fP required virtual method for display object\&. 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 50 of file UNBL\&.cpp\&.
.PP
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
51 {
52    std::cout << "\nUNBL BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName()  << "\nVersion number : " << this->Get_Version() << std::endl;
53 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "int UNBL::accountNumber\fC [private]\fP"

.PP
Definition at line 93 of file UNBL\&.h\&.
.PP
Referenced by GetAccountNumber(), operator=(), SetAccountNumber(), and UNBL()\&.
.SS "std::string UNBL::address\fC [private]\fP"

.PP
Definition at line 95 of file UNBL\&.h\&.
.PP
Referenced by GetAddress(), operator=(), SetAddress(), and UNBL()\&.
.SS "double UNBL::balance\fC [private]\fP"

.PP
Definition at line 94 of file UNBL\&.h\&.
.PP
Referenced by GetBalance(), operator=(), SetBalance(), and UNBL()\&.
.SS "std::string UNBL::firstName\fC [private]\fP"

.PP
Definition at line 91 of file UNBL\&.h\&.
.PP
Referenced by GetFirstName(), operator=(), SetFirstName(), and UNBL()\&.
.SS "std::string UNBL::fullname\fC [private]\fP"

.PP
Definition at line 90 of file UNBL\&.h\&.
.PP
Referenced by GetFullname(), operator=(), SetFullname(), and UNBL()\&.
.SS "std::string UNBL::lastName\fC [private]\fP"

.PP
Definition at line 92 of file UNBL\&.h\&.
.PP
Referenced by GetLastName(), operator=(), SetLastName(), and UNBL()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CppUnit test STM from the source code\&.
