.TH "BANK" 3 "Sun Apr 1 2018" "C++ Software transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BANK \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BANK\&.h>\fP
.PP
Inherits \fBOSTM\fP\&.
.PP
Inherited by \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBANK\fP ()"
.br
.ti -1c
.RI "\fBBANK\fP (int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBBANK\fP (const \fBBANK\fP &orig)"
.br
.ti -1c
.RI "virtual int \fBGetAccountNumber\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetAddress\fP () const "
.br
.ti -1c
.RI "virtual double \fBGetBalance\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetFirstName\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetFullname\fP () const "
.br
.ti -1c
.RI "virtual std::string \fBGetLastName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetAccountNumber\fP (int accountNumber)"
.br
.ti -1c
.RI "virtual void \fBSetAddress\fP (std::string address)"
.br
.ti -1c
.RI "virtual void \fBSetBalance\fP (double balance)"
.br
.ti -1c
.RI "virtual void \fBSetFirstName\fP (std::string firstName)"
.br
.ti -1c
.RI "virtual void \fBSetFullname\fP (std::string fullname)"
.br
.ti -1c
.RI "virtual void \fBSetLastName\fP (std::string lastName)"
.br
.ti -1c
.RI "virtual \fB~BANK\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBANK\fP inherit from the \fBOSTM\fP library\&. It is declares the common functions in the child classes as a virtual function\&. 
.PP
Definition at line 16 of file BANK\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BANK::BANK ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 23 of file BANK\&.h\&.
.PP
Referenced by BANK()\&.
.PP
.nf
23           : OSTM(){
24         
25     };
.fi
.SS "BANK::BANK (int _version, int _unique_id)\fC [inline]\fP"
Custom Constructor 
.PP
Definition at line 29 of file BANK\&.h\&.
.PP
References BANK(), and ~BANK()\&.
.PP
.nf
29                                        : OSTM(_version, _unique_id){
30         
31     };
.fi
.SS "BANK::BANK (const \fBBANK\fP & orig)"
Copy constructor 
.PP
Definition at line 11 of file BANK\&.cpp\&.
.PP
.nf
11                            {
12 }
.fi
.SS "BANK::~BANK ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 14 of file BANK\&.cpp\&.
.PP
Referenced by BANK()\&.
.PP
.nf
14             {
15 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual int BANK::GetAccountNumber () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 49 of file BANK\&.h\&.
.PP
.nf
49 {};
.fi
.SS "virtual std::string BANK::GetAddress () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 45 of file BANK\&.h\&.
.PP
.nf
45 {};
.fi
.SS "virtual double BANK::GetBalance () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 47 of file BANK\&.h\&.
.PP
.nf
47 {};
.fi
.SS "virtual std::string BANK::GetFirstName () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 53 of file BANK\&.h\&.
.PP
.nf
53 {};
.fi
.SS "virtual std::string BANK::GetFullname () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 55 of file BANK\&.h\&.
.PP
.nf
55 {};
.fi
.SS "virtual std::string BANK::GetLastName () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 51 of file BANK\&.h\&.
.PP
.nf
51 {};
.fi
.SS "virtual void BANK::SetAccountNumber (int accountNumber)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 48 of file BANK\&.h\&.
.PP
.nf
48 {};
.fi
.SS "virtual void BANK::SetAddress (std::string address)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 44 of file BANK\&.h\&.
.PP
.nf
44 {};
.fi
.SS "virtual void BANK::SetBalance (double balance)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 46 of file BANK\&.h\&.
.PP
Referenced by _complex_transfer_(), _nesting_(), _six_account_transfer_(), and _two_account_transfer_()\&.
.PP
.nf
46 {};
.fi
.SS "virtual void BANK::SetFirstName (std::string firstName)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 52 of file BANK\&.h\&.
.PP
.nf
52 {};
.fi
.SS "virtual void BANK::SetFullname (std::string fullname)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 54 of file BANK\&.h\&.
.PP
.nf
54 {};
.fi
.SS "virtual void BANK::SetLastName (std::string lastName)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBAIB\fP, \fBBOA\fP, \fBBOI\fP, \fBSWBPLC\fP, \fBULSTER\fP, and \fBUNBL\fP\&.
.PP
Definition at line 50 of file BANK\&.h\&.
.PP
.nf
50 {};
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software transactional Memory from the source code\&.
