BANK
NAME
BANK -
SYNOPSIS
#include <BANK.h>
Inherits OSTM.
Inherited by AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Public Member Functions
BANK ()
BANK (int _version, int _unique_id)
BANK (const BANK &orig)
virtual int GetAccountNumber () const
virtual std::string GetAddress () const
virtual double GetBalance () const
virtual std::string GetFirstName () const
virtual std::string GetFullname () const
virtual std::string GetLastName () const
virtual void SetAccountNumber (int accountNumber)
virtual void SetAddress (std::string address)
virtual void SetBalance (double balance)
virtual void SetFirstName (std::string firstName)
virtual void SetFullname (std::string fullname)
virtual void SetLastName (std::string lastName)
virtual ~BANK ()
Detailed Description
BANK inherit from the OSTM library. It is declares the common functions in the child classes as a virtual function.
Definition at line 16 of file BANK.h.
Constructor & Destructor Documentation
BANK::BANK () [inline]
Constructor
Definition at line 23 of file BANK.h.
Referenced by BANK().
          : OSTM(){
        
    };
BANK::BANK (int _version, int _unique_id) [inline]
Custom Constructor
Definition at line 29 of file BANK.h.
References BANK(), and ~BANK().
                                       : OSTM(_version, _unique_id){
        
    };
BANK::BANK (const BANK & orig)
Copy constructor
Definition at line 11 of file BANK.cpp.
                           {
}
BANK::~BANK () [virtual]
de-constructor
Definition at line 14 of file BANK.cpp.
Referenced by BANK().
            {
}
Member Function Documentation
virtual int BANK::GetAccountNumber () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 49 of file BANK.h.
{};
virtual std::string BANK::GetAddress () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 45 of file BANK.h.
{};
virtual double BANK::GetBalance () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 47 of file BANK.h.
{};
virtual std::string BANK::GetFirstName () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 53 of file BANK.h.
{};
virtual std::string BANK::GetFullname () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 55 of file BANK.h.
{};
virtual std::string BANK::GetLastName () const [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 51 of file BANK.h.
{};
virtual void BANK::SetAccountNumber (int accountNumber) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 48 of file BANK.h.
{};
virtual void BANK::SetAddress (std::string address) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 44 of file BANK.h.
{};
virtual void BANK::SetBalance (double balance) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 46 of file BANK.h.
Referenced by _complex_transfer_(), _nesting_(), _six_account_transfer_(), and _two_account_transfer_().
{};
virtual void BANK::SetFirstName (std::string firstName) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 52 of file BANK.h.
{};
virtual void BANK::SetFullname (std::string fullname) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 54 of file BANK.h.
{};
virtual void BANK::SetLastName (std::string lastName) [inline], [virtual]
Reimplemented in AIB, BOA, BOI, SWBPLC, ULSTER, and UNBL.
Definition at line 50 of file BANK.h.
{};
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.