BOA
NAME
BOA -
SYNOPSIS
#include <BOA.h>
Inherits BANK.
Public Member Functions
BOA ()
BOA (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)
BOA (std::shared_ptr< BANK > obj, int _version, int _unique_id)
BOA (const BOA &orig)
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual int GetAccountNumber () const
virtual std::string GetAddress () const
virtual double GetBalance () const
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
virtual std::string GetFirstName () const
virtual std::string GetFullname () const
virtual std::string GetLastName () const
BOA operator= (const BOA &orig)
virtual void SetAccountNumber (int accountNumber)
virtual void SetAddress (std::string address)
virtual void SetBalance (double balance)
virtual void SetFirstName (std::string firstName)
virtual void SetFullname (std::string fullname)
virtual void SetLastName (std::string lastName)
virtual void toString ()
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type
virtual ~BOA ()
Private Attributes
int accountNumber
std::string address
double balance
std::string firstName
std::string fullname
std::string lastName
Detailed Description
Inherit from BANK
Definition at line 18 of file BOA.h.
Constructor & Destructor Documentation
BOA::BOA () [inline]
Constructor
Definition at line 24 of file BOA.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
Referenced by BOA(), and getBaseCopy().
          : BANK() {
        this->accountNumber = 0;
        this->balance = 50;
        this->firstName = "Joe";
        this->lastName = "Blog";
        this->address = "High street, Carlow";
        this->fullname = firstName + " " + lastName;
    };
BOA::BOA (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address) [inline]
Custom constructor
Definition at line 35 of file BOA.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
                                                                                                       : BANK() {
        this->accountNumber = accountNumber;
        this->balance = balance;
        this->firstName = firstName;
        this->lastName = lastName;
        this->address = address;
        this->fullname = firstName + " " + lastName;
    };
BOA::BOA (std::shared_ptr< BANK > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Definition at line 46 of file BOA.h.
References accountNumber, address, balance, BOA(), firstName, fullname, and lastName.
                                                               : BANK(_version, _unique_id) {
 
        this->accountNumber = obj->GetAccountNumber();
        this->balance = obj->GetBalance();
        this->firstName = obj->GetFirstName();
        this->lastName = obj->GetLastName();
        this->address = obj->GetAddress();
        this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
    };
BOA::BOA (const BOA & orig)
Copy constructor
Definition at line 12 of file BOA.cpp.
                        {
}
BOA::~BOA () [virtual]
de-constructor
Definition at line 15 of file BOA.cpp.
Referenced by operator=().
          {
}
Member Function Documentation
void BOA::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer
Parameters:
objTO is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
objFROM is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
Reimplemented from OSTM.
Definition at line 34 of file BOA.cpp.
References OSTM::Set_Unique_ID().
Referenced by operator=().
                                                              {
    std::shared_ptr<BOA> objTO = std::dynamic_pointer_cast<BOA>(to);
    std::shared_ptr<BOA> objFROM = std::dynamic_pointer_cast<BOA>(from);
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    objTO->SetAccountNumber(objFROM->GetAccountNumber());
    objTO->SetBalance(objFROM->GetBalance());
        
}
int BOA::GetAccountNumber () const [virtual]
Reimplemented from BANK.
Definition at line 80 of file BOA.cpp.
References accountNumber.
Referenced by operator=(), and toString().
                                {
    return accountNumber;
}
std::string BOA::GetAddress () const [virtual]
Reimplemented from BANK.
Definition at line 64 of file BOA.cpp.
References address.
Referenced by operator=().
                                {
    return address;
}
double BOA::GetBalance () const [virtual]
Reimplemented from BANK.
Definition at line 72 of file BOA.cpp.
References balance.
Referenced by operator=(), and toString().
                             {
    return balance;
}
std::shared_ptr< OSTM > BOA::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
Parameters:
objTO is a BANK type pointer for casting
obj is a std::shared_ptr<BANK> return type
Reimplemented from OSTM.
Definition at line 22 of file BOA.cpp.
References BOA().
Referenced by operator=().
{
        std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
    std::shared_ptr<BANK> obj(new BOA(objTO,object->Get_Version(),object->Get_Unique_ID()));
        std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
std::string BOA::GetFirstName () const [virtual]
Reimplemented from BANK.
Definition at line 96 of file BOA.cpp.
References firstName.
Referenced by operator=(), and toString().
                                  {
    return firstName;
}
std::string BOA::GetFullname () const [virtual]
Reimplemented from BANK.
Definition at line 104 of file BOA.cpp.
References fullname.
Referenced by operator=().
                                 {
    return fullname;
}
std::string BOA::GetLastName () const [virtual]
Reimplemented from BANK.
Definition at line 88 of file BOA.cpp.
References lastName.
Referenced by operator=(), and toString().
                                 {
    return lastName;
}
BOA BOA::operator= (const BOA & orig) [inline]
Operator
Definition at line 64 of file BOA.h.
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~BOA().
                                   {
    };
void BOA::SetAccountNumber (int accountNumber) [virtual]
Reimplemented from BANK.
Definition at line 76 of file BOA.cpp.
References accountNumber.
Referenced by operator=().
                                            {
    this->accountNumber = accountNumber;
}
void BOA::SetAddress (std::string address) [virtual]
Reimplemented from BANK.
Definition at line 60 of file BOA.cpp.
References address.
Referenced by operator=().
                                      {
    this->address = address;
}
void BOA::SetBalance (double balance) [virtual]
Reimplemented from BANK.
Definition at line 68 of file BOA.cpp.
References balance.
Referenced by operator=().
                                   {
    this->balance = balance;
}
void BOA::SetFirstName (std::string firstName) [virtual]
Reimplemented from BANK.
Definition at line 92 of file BOA.cpp.
References firstName.
Referenced by operator=().
                                          {
    this->firstName = firstName;
}
void BOA::SetFullname (std::string fullname) [virtual]
Reimplemented from BANK.
Definition at line 100 of file BOA.cpp.
References fullname.
Referenced by operator=().
                                        {
    this->fullname = fullname;
}
void BOA::SetLastName (std::string lastName) [virtual]
Reimplemented from BANK.
Definition at line 84 of file BOA.cpp.
References lastName.
Referenced by operator=().
                                        {
    this->lastName = lastName;
}
void BOA::toString () [virtual]
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way
Reimplemented from OSTM.
Definition at line 54 of file BOA.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName().
Referenced by operator=().
{
   // std::cout << "\nUnique ID : " << this->GetUniqueID() << "\nInt value : " << this->GetV_int() << "\nDouble value : " << this->GetV_double() << "\nFloat value : " << this->GetV_float() << "\nString value : " << this->GetV_string() << "\nVersion number : " << this->GetVersion() << "\nLoad Counter : "<< this->GetLoadCounter() << "\nWrite Counter : "<< this->GetWriteCounter() << std::endl;
     std::cout << "\nBOA BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int BOA::accountNumber [private]
Definition at line 98 of file BOA.h.
Referenced by BOA(), GetAccountNumber(), operator=(), and SetAccountNumber().
std::string BOA::address [private]
Definition at line 100 of file BOA.h.
Referenced by BOA(), GetAddress(), operator=(), and SetAddress().
double BOA::balance [private]
Definition at line 99 of file BOA.h.
Referenced by BOA(), GetBalance(), operator=(), and SetBalance().
std::string BOA::firstName [private]
Definition at line 96 of file BOA.h.
Referenced by BOA(), GetFirstName(), operator=(), and SetFirstName().
std::string BOA::fullname [private]
Definition at line 95 of file BOA.h.
Referenced by BOA(), GetFullname(), operator=(), and SetFullname().
std::string BOA::lastName [private]
Definition at line 97 of file BOA.h.
Referenced by BOA(), GetLastName(), operator=(), and SetLastName().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.