CARPHONE_WAREHOUSE
NAME
CARPHONE_WAREHOUSE -
SYNOPSIS
#include <CARPHONE_WAREHOUSE.h>
Inherits WAREHOUSE.
Public Member Functions
CARPHONE_WAREHOUSE ()
CARPHONE_WAREHOUSE (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)
CARPHONE_WAREHOUSE (std::shared_ptr< WAREHOUSE > obj, int _version, int _unique_id)
CARPHONE_WAREHOUSE (const CARPHONE_WAREHOUSE &orig)
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object
virtual int GetNumber_of_alcatel ()
virtual int GetNumber_of_huawei ()
virtual int GetNumber_of_iphones ()
virtual int GetNumber_of_nokia ()
virtual int GetNumber_of_samsung ()
virtual int GetNumber_of_sony ()
virtual std::string GetShop_address ()
virtual std::string GetShop_name ()
CARPHONE_WAREHOUSE operator= (const CARPHONE_WAREHOUSE &orig)
virtual void SetNumber_of_alcatel (int _number_of_alcatel)
virtual void SetNumber_of_huawei (int _number_of_huawei)
virtual void SetNumber_of_iphones (int _number_of_iphones)
virtual void SetNumber_of_nokia (int _number_of_nokia)
virtual void SetNumber_of_samsung (int _number_of_samsung)
virtual void SetNumber_of_sony (int _number_of_sony)
virtual void SetShop_address (std::string _shop_address)
virtual void SetShop_name (std::string _shop_name)
virtual void toString ()
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type
virtual ~CARPHONE_WAREHOUSE ()
Private Attributes
int _number_of_alcatel
int _number_of_huawei
int _number_of_iphones
int _number_of_nokia
int _number_of_samsung
int _number_of_sony
std::string _shop_address
std::string _shop_name
Detailed Description
Inherit from WAREHOUSE
Definition at line 19 of file CARPHONE_WAREHOUSE.h.
Constructor & Destructor Documentation
CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE () [inline]
Constructor
Definition at line 24 of file CARPHONE_WAREHOUSE.h.
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, and _shop_name.
Referenced by CARPHONE_WAREHOUSE(), and getBaseCopy().
                        : WAREHOUSE(){
        
        this->_shop_address = "DUBLIN XII";
        this->_shop_name = "DISTRIBUTION CENTER";
        this->_number_of_iphones = 10000;
        this->_number_of_samsung = 10000;
        this->_number_of_sony = 10000;
        this->_number_of_huawei = 10000;
        this->_number_of_nokia = 10000;
        this->_number_of_alcatel = 10000;
    };
CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel) [inline]
Custom constructor
Definition at line 38 of file CARPHONE_WAREHOUSE.h.
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, and _shop_name.
                                                                                                                                     : WAREHOUSE(){
        /*
         * copy over values
         */
        this->_shop_address = address;
        this->_shop_name = shop_name;
        this->_number_of_iphones = iphone;
        this->_number_of_samsung = samsung;
        this->_number_of_sony = sony;
        this->_number_of_huawei = huawei;
        this->_number_of_nokia = nokia;
        this->_number_of_alcatel = alcatel;
        
    };
CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (std::shared_ptr< WAREHOUSE > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Definition at line 55 of file CARPHONE_WAREHOUSE.h.
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, _shop_name, and CARPHONE_WAREHOUSE().
                                                                                  : WAREHOUSE(_version, _unique_id){
        /*
         * copy over values
         */
        this->_shop_address = obj->GetShop_address();
        this->_shop_name = obj->GetShop_name();
        this->_number_of_iphones = obj->GetNumber_of_iphones();
        this->_number_of_samsung = obj->GetNumber_of_samsung();
        this->_number_of_sony = obj->GetNumber_of_sony();
        this->_number_of_huawei = obj->GetNumber_of_huawei();
        this->_number_of_nokia = obj->GetNumber_of_nokia();
        this->_number_of_alcatel = obj->GetNumber_of_alcatel();
    }
CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (const CARPHONE_WAREHOUSE & orig)
Copy constructor
Definition at line 11 of file CARPHONE_WAREHOUSE.cpp.
                                                                     {
}
CARPHONE_WAREHOUSE::~CARPHONE_WAREHOUSE () [virtual]
de-constructor
Definition at line 14 of file CARPHONE_WAREHOUSE.cpp.
Referenced by operator=().
                                        {
}
Member Function Documentation
void CARPHONE_WAREHOUSE::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer
Parameters:
objTO is a BANK* type object casted back from std::shared_ptr<OSTM>
objFROM is a BANK* type object casted back from std::shared_ptr<OSTM>
Reimplemented from OSTM.
Definition at line 34 of file CARPHONE_WAREHOUSE.cpp.
References _shop_address.
Referenced by operator=().
                                                                             {
    std::shared_ptr<CARPHONE_WAREHOUSE> objTO = std::dynamic_pointer_cast<CARPHONE_WAREHOUSE>(to);
    std::shared_ptr<CARPHONE_WAREHOUSE> objFROM = std::dynamic_pointer_cast<CARPHONE_WAREHOUSE>(from);
    objTO->_shop_address = objFROM->GetShop_address();
    objTO->_shop_name = objFROM->GetShop_name();
    objTO->_number_of_iphones = objFROM->GetNumber_of_iphones();
    objTO->_number_of_samsung = objFROM->GetNumber_of_samsung();
    objTO->_number_of_sony = objFROM->GetNumber_of_sony();
    objTO->_number_of_huawei = objFROM->GetNumber_of_huawei();
    objTO->_number_of_nokia = objFROM->GetNumber_of_nokia();
    objTO->_number_of_alcatel = objFROM->GetNumber_of_alcatel();
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
   
}
std::shared_ptr< OSTM > CARPHONE_WAREHOUSE::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object
Parameters:
objTO is a BANK type pointer for casting
obj is a BANK* return type
Reimplemented from OSTM.
Definition at line 21 of file CARPHONE_WAREHOUSE.cpp.
References CARPHONE_WAREHOUSE().
Referenced by operator=().
{
    std::shared_ptr<WAREHOUSE> objTO = std::dynamic_pointer_cast<WAREHOUSE>(object);
    std::shared_ptr<WAREHOUSE> obj(new CARPHONE_WAREHOUSE(objTO, object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
int CARPHONE_WAREHOUSE::GetNumber_of_alcatel () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 71 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_alcatel.
Referenced by operator=(), and toString().
                                            {
    return _number_of_alcatel;
}
int CARPHONE_WAREHOUSE::GetNumber_of_huawei () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 87 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_huawei.
Referenced by operator=(), and toString().
                                           {
    return _number_of_huawei;
}
int CARPHONE_WAREHOUSE::GetNumber_of_iphones () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 111 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_iphones.
Referenced by operator=(), and toString().
                                            {
    return _number_of_iphones;
}
int CARPHONE_WAREHOUSE::GetNumber_of_nokia () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 79 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_nokia.
Referenced by operator=(), and toString().
                                          {
    return _number_of_nokia;
}
int CARPHONE_WAREHOUSE::GetNumber_of_samsung () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 103 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_samsung.
Referenced by operator=(), and toString().
                                            {
    return _number_of_samsung;
}
int CARPHONE_WAREHOUSE::GetNumber_of_sony () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 95 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_sony.
Referenced by operator=(), and toString().
                                         {
    return _number_of_sony;
}
std::string CARPHONE_WAREHOUSE::GetShop_address () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 127 of file CARPHONE_WAREHOUSE.cpp.
References _shop_address.
Referenced by operator=(), and toString().
                                             {
    return _shop_address;
}
std::string CARPHONE_WAREHOUSE::GetShop_name () [virtual]
Reimplemented from WAREHOUSE.
Definition at line 119 of file CARPHONE_WAREHOUSE.cpp.
References _shop_name.
Referenced by operator=(), and toString().
                                          {
    return _shop_name;
}
CARPHONE_WAREHOUSE CARPHONE_WAREHOUSE::operator= (const CARPHONE_WAREHOUSE & orig) [inline]
Operator
Definition at line 75 of file CARPHONE_WAREHOUSE.h.
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, _shop_name, copy(), getBaseCopy(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), GetShop_name(), SetNumber_of_alcatel(), SetNumber_of_huawei(), SetNumber_of_iphones(), SetNumber_of_nokia(), SetNumber_of_samsung(), SetNumber_of_sony(), SetShop_address(), SetShop_name(), toString(), and ~CARPHONE_WAREHOUSE().
{};
void CARPHONE_WAREHOUSE::SetNumber_of_alcatel (int _number_of_alcatel) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 67 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_alcatel.
Referenced by operator=().
                                                                    {
    this->_number_of_alcatel = _number_of_alcatel;
}
void CARPHONE_WAREHOUSE::SetNumber_of_huawei (int _number_of_huawei) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 83 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_huawei.
Referenced by operator=().
                                                                  {
    this->_number_of_huawei = _number_of_huawei;
}
void CARPHONE_WAREHOUSE::SetNumber_of_iphones (int _number_of_iphones) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 107 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_iphones.
Referenced by operator=().
                                                                    {
    this->_number_of_iphones = _number_of_iphones;
}
void CARPHONE_WAREHOUSE::SetNumber_of_nokia (int _number_of_nokia) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 75 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_nokia.
Referenced by operator=().
                                                                {
    this->_number_of_nokia = _number_of_nokia;
}
void CARPHONE_WAREHOUSE::SetNumber_of_samsung (int _number_of_samsung) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 99 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_samsung.
Referenced by operator=().
                                                                    {
    this->_number_of_samsung = _number_of_samsung;
}
void CARPHONE_WAREHOUSE::SetNumber_of_sony (int _number_of_sony) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 91 of file CARPHONE_WAREHOUSE.cpp.
References _number_of_sony.
Referenced by operator=().
                                                              {
    this->_number_of_sony = _number_of_sony;
}
void CARPHONE_WAREHOUSE::SetShop_address (std::string _shop_address) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 123 of file CARPHONE_WAREHOUSE.cpp.
References _shop_address.
Referenced by operator=().
                                                                {
    this->_shop_address = _shop_address;
}
void CARPHONE_WAREHOUSE::SetShop_name (std::string _shop_name) [virtual]
Reimplemented from WAREHOUSE.
Definition at line 115 of file CARPHONE_WAREHOUSE.cpp.
References _shop_name.
Referenced by operator=().
                                                          {
    this->_shop_name = _shop_name;
}
void CARPHONE_WAREHOUSE::toString () [virtual]
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way
Reimplemented from OSTM.
Definition at line 60 of file CARPHONE_WAREHOUSE.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), and GetShop_name().
Referenced by operator=().
{
   std::cout << "\n" << this->GetShop_name() << "\nUnique ID : " << this->Get_Unique_ID() << "\nShop Name : " << this->GetShop_name() << "\nShop Address : " << this->GetShop_address() << "\nNo. Iphones : " << this->GetNumber_of_iphones() << "\nNo. Samsung : " << this->GetNumber_of_samsung() << "\nNo. Sony : " << this->GetNumber_of_sony() << "\nNo. Huawei : " << this->GetNumber_of_huawei() << "\nNo. Nokia : " << this->GetNumber_of_nokia() << "\nNo. Alcatel : " << this->GetNumber_of_alcatel() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int CARPHONE_WAREHOUSE::_number_of_alcatel [private]
Definition at line 118 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_alcatel(), operator=(), and SetNumber_of_alcatel().
int CARPHONE_WAREHOUSE::_number_of_huawei [private]
Definition at line 116 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_huawei(), operator=(), and SetNumber_of_huawei().
int CARPHONE_WAREHOUSE::_number_of_iphones [private]
Definition at line 113 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_iphones(), operator=(), and SetNumber_of_iphones().
int CARPHONE_WAREHOUSE::_number_of_nokia [private]
Definition at line 117 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_nokia(), operator=(), and SetNumber_of_nokia().
int CARPHONE_WAREHOUSE::_number_of_samsung [private]
Definition at line 114 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_samsung(), operator=(), and SetNumber_of_samsung().
int CARPHONE_WAREHOUSE::_number_of_sony [private]
Definition at line 115 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_sony(), operator=(), and SetNumber_of_sony().
std::string CARPHONE_WAREHOUSE::_shop_address [private]
Definition at line 111 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), copy(), GetShop_address(), operator=(), and SetShop_address().
std::string CARPHONE_WAREHOUSE::_shop_name [private]
Definition at line 112 of file CARPHONE_WAREHOUSE.h.
Referenced by CARPHONE_WAREHOUSE(), GetShop_name(), operator=(), and SetShop_name().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.