.TH "CARPHONE_WAREHOUSE.cpp" 3 "Sun Apr 1 2018" "C++ Software transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CARPHONE_WAREHOUSE.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CARPHONE_WAREHOUSE\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software transactional Memory from the source code\&.
