.TH "CARPHONE_WAREHOUSE" 3 "Sun Apr 1 2018" "C++ Software transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CARPHONE_WAREHOUSE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CARPHONE_WAREHOUSE\&.h>\fP
.PP
Inherits \fBWAREHOUSE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCARPHONE_WAREHOUSE\fP ()"
.br
.ti -1c
.RI "\fBCARPHONE_WAREHOUSE\fP (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)"
.br
.ti -1c
.RI "\fBCARPHONE_WAREHOUSE\fP (std::shared_ptr< \fBWAREHOUSE\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBCARPHONE_WAREHOUSE\fP (const \fBCARPHONE_WAREHOUSE\fP &orig)"
.br
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)"
.br
.RI "\fIcopy function, make deep copy of the object/pointer \fP"
.ti -1c
.RI "virtual std::shared_ptr< \fBOSTM\fP > \fBgetBaseCopy\fP (std::shared_ptr< \fBOSTM\fP > object)"
.br
.RI "\fIgetBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object \fP"
.ti -1c
.RI "virtual int \fBGetNumber_of_alcatel\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_huawei\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_iphones\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_nokia\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_samsung\fP ()"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_sony\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_address\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_name\fP ()"
.br
.ti -1c
.RI "\fBCARPHONE_WAREHOUSE\fP \fBoperator=\fP (const \fBCARPHONE_WAREHOUSE\fP &orig)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_alcatel\fP (int \fB_number_of_alcatel\fP)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_huawei\fP (int \fB_number_of_huawei\fP)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_iphones\fP (int \fB_number_of_iphones\fP)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_nokia\fP (int \fB_number_of_nokia\fP)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_samsung\fP (int \fB_number_of_samsung\fP)"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_sony\fP (int \fB_number_of_sony\fP)"
.br
.ti -1c
.RI "virtual void \fBSetShop_address\fP (std::string \fB_shop_address\fP)"
.br
.ti -1c
.RI "virtual void \fBSetShop_name\fP (std::string \fB_shop_name\fP)"
.br
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type \fP"
.ti -1c
.RI "virtual \fB~CARPHONE_WAREHOUSE\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fB_number_of_alcatel\fP"
.br
.ti -1c
.RI "int \fB_number_of_huawei\fP"
.br
.ti -1c
.RI "int \fB_number_of_iphones\fP"
.br
.ti -1c
.RI "int \fB_number_of_nokia\fP"
.br
.ti -1c
.RI "int \fB_number_of_samsung\fP"
.br
.ti -1c
.RI "int \fB_number_of_sony\fP"
.br
.ti -1c
.RI "std::string \fB_shop_address\fP"
.br
.ti -1c
.RI "std::string \fB_shop_name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inherit from \fBWAREHOUSE\fP 
.PP
Definition at line 19 of file CARPHONE_WAREHOUSE\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 24 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, and _shop_name\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), and getBaseCopy()\&.
.PP
.nf
24                         : WAREHOUSE(){
25         
26         this->_shop_address = "DUBLIN XII";
27         this->_shop_name = "DISTRIBUTION CENTER";
28         this->_number_of_iphones = 10000;
29         this->_number_of_samsung = 10000;
30         this->_number_of_sony = 10000;
31         this->_number_of_huawei = 10000;
32         this->_number_of_nokia = 10000;
33         this->_number_of_alcatel = 10000;
34     };
.fi
.SS "CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)\fC [inline]\fP"
Custom constructor 
.PP
Definition at line 38 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, and _shop_name\&.
.PP
.nf
38                                                                                                                                      : WAREHOUSE(){
39         /*
40          * copy over values
41          */
42         this->_shop_address = address;
43         this->_shop_name = shop_name;
44         this->_number_of_iphones = iphone;
45         this->_number_of_samsung = samsung;
46         this->_number_of_sony = sony;
47         this->_number_of_huawei = huawei;
48         this->_number_of_nokia = nokia;
49         this->_number_of_alcatel = alcatel;
50         
51     }; 
.fi
.SS "CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (std::shared_ptr< \fBWAREHOUSE\fP > obj, int _version, int _unique_id)\fC [inline]\fP"
Custom constructor, used by the library for deep copying 
.PP
Definition at line 55 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, _shop_name, and CARPHONE_WAREHOUSE()\&.
.PP
.nf
55                                                                                   : WAREHOUSE(_version, _unique_id){
56         /*
57          * copy over values
58          */
59         this->_shop_address = obj->GetShop_address();
60         this->_shop_name = obj->GetShop_name();
61         this->_number_of_iphones = obj->GetNumber_of_iphones();
62         this->_number_of_samsung = obj->GetNumber_of_samsung();
63         this->_number_of_sony = obj->GetNumber_of_sony();
64         this->_number_of_huawei = obj->GetNumber_of_huawei();
65         this->_number_of_nokia = obj->GetNumber_of_nokia();
66         this->_number_of_alcatel = obj->GetNumber_of_alcatel();
67     }
.fi
.SS "CARPHONE_WAREHOUSE::CARPHONE_WAREHOUSE (const \fBCARPHONE_WAREHOUSE\fP & orig)"
Copy constructor 
.PP
Definition at line 11 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
.nf
11                                                                      {
12 }
.fi
.SS "CARPHONE_WAREHOUSE::~CARPHONE_WAREHOUSE ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 14 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
14                                         {
15 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void CARPHONE_WAREHOUSE::copy (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)\fC [virtual]\fP"

.PP
copy function, make deep copy of the object/pointer 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a BANK* type object casted back from std::shared_ptr<OSTM> 
.br
\fIobjFROM\fP is a BANK* type object casted back from std::shared_ptr<OSTM> 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 34 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _shop_address\&.
.PP
Referenced by operator=()\&.
.PP
.nf
34                                                                              {
35 
36     std::shared_ptr<CARPHONE_WAREHOUSE> objTO = std::dynamic_pointer_cast<CARPHONE_WAREHOUSE>(to);
37     std::shared_ptr<CARPHONE_WAREHOUSE> objFROM = std::dynamic_pointer_cast<CARPHONE_WAREHOUSE>(from);
38     objTO->_shop_address = objFROM->GetShop_address();
39     objTO->_shop_name = objFROM->GetShop_name();
40     objTO->_number_of_iphones = objFROM->GetNumber_of_iphones();
41     objTO->_number_of_samsung = objFROM->GetNumber_of_samsung();
42     objTO->_number_of_sony = objFROM->GetNumber_of_sony();
43     objTO->_number_of_huawei = objFROM->GetNumber_of_huawei();
44     objTO->_number_of_nokia = objFROM->GetNumber_of_nokia();
45     objTO->_number_of_alcatel = objFROM->GetNumber_of_alcatel();
46     objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
47     objTO->Set_Version(objFROM->Get_Version());
48    
49 }
.fi
.SS "std::shared_ptr< \fBOSTM\fP > CARPHONE_WAREHOUSE::getBaseCopy (std::shared_ptr< \fBOSTM\fP > object)\fC [virtual]\fP"

.PP
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a \fBBANK\fP type pointer for casting 
.br
\fIobj\fP is a BANK* return type 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 21 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References CARPHONE_WAREHOUSE()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
22 {
23 
24     std::shared_ptr<WAREHOUSE> objTO = std::dynamic_pointer_cast<WAREHOUSE>(object);
25     std::shared_ptr<WAREHOUSE> obj(new CARPHONE_WAREHOUSE(objTO, object->Get_Version(),object->Get_Unique_ID()));
26     std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
27     return ostm_obj;
28 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_alcatel ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 71 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_alcatel\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
71                                             {
72     return _number_of_alcatel;
73 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_huawei ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 87 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_huawei\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
87                                            {
88     return _number_of_huawei;
89 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_iphones ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 111 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_iphones\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
111                                             {
112     return _number_of_iphones;
113 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_nokia ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 79 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_nokia\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
79                                           {
80     return _number_of_nokia;
81 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_samsung ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 103 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_samsung\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
103                                             {
104     return _number_of_samsung; 
105 }
.fi
.SS "int CARPHONE_WAREHOUSE::GetNumber_of_sony ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 95 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_sony\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
95                                          {
96     return _number_of_sony;
97 }
.fi
.SS "std::string CARPHONE_WAREHOUSE::GetShop_address ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 127 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _shop_address\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
127                                              {
128     return _shop_address;
129 }
.fi
.SS "std::string CARPHONE_WAREHOUSE::GetShop_name ()\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 119 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _shop_name\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
119                                           {
120     return _shop_name;
121 }
.fi
.SS "\fBCARPHONE_WAREHOUSE\fP CARPHONE_WAREHOUSE::operator= (const \fBCARPHONE_WAREHOUSE\fP & orig)\fC [inline]\fP"
Operator 
.PP
Definition at line 75 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
References _number_of_alcatel, _number_of_huawei, _number_of_iphones, _number_of_nokia, _number_of_samsung, _number_of_sony, _shop_address, _shop_name, copy(), getBaseCopy(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), GetShop_name(), SetNumber_of_alcatel(), SetNumber_of_huawei(), SetNumber_of_iphones(), SetNumber_of_nokia(), SetNumber_of_samsung(), SetNumber_of_sony(), SetShop_address(), SetShop_name(), toString(), and ~CARPHONE_WAREHOUSE()\&.
.PP
.nf
75 {};
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_alcatel (int _number_of_alcatel)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 67 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_alcatel\&.
.PP
Referenced by operator=()\&.
.PP
.nf
67                                                                     {
68     this->_number_of_alcatel = _number_of_alcatel;
69 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_huawei (int _number_of_huawei)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 83 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_huawei\&.
.PP
Referenced by operator=()\&.
.PP
.nf
83                                                                   {
84     this->_number_of_huawei = _number_of_huawei;
85 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_iphones (int _number_of_iphones)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 107 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_iphones\&.
.PP
Referenced by operator=()\&.
.PP
.nf
107                                                                     {
108     this->_number_of_iphones = _number_of_iphones;
109 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_nokia (int _number_of_nokia)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 75 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_nokia\&.
.PP
Referenced by operator=()\&.
.PP
.nf
75                                                                 {
76     this->_number_of_nokia = _number_of_nokia;
77 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_samsung (int _number_of_samsung)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 99 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_samsung\&.
.PP
Referenced by operator=()\&.
.PP
.nf
99                                                                     {
100     this->_number_of_samsung = _number_of_samsung;
101 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetNumber_of_sony (int _number_of_sony)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 91 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _number_of_sony\&.
.PP
Referenced by operator=()\&.
.PP
.nf
91                                                               {
92     this->_number_of_sony = _number_of_sony;
93 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetShop_address (std::string _shop_address)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 123 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _shop_address\&.
.PP
Referenced by operator=()\&.
.PP
.nf
123                                                                 {
124     this->_shop_address = _shop_address;
125 }
.fi
.SS "void CARPHONE_WAREHOUSE::SetShop_name (std::string _shop_name)\fC [virtual]\fP"

.PP
Reimplemented from \fBWAREHOUSE\fP\&.
.PP
Definition at line 115 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References _shop_name\&.
.PP
Referenced by operator=()\&.
.PP
.nf
115                                                           {
116     this->_shop_name = _shop_name;
117 }
.fi
.SS "void CARPHONE_WAREHOUSE::toString ()\fC [virtual]\fP"

.PP
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 60 of file CARPHONE_WAREHOUSE\&.cpp\&.
.PP
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), and GetShop_name()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
61 {
62    std::cout << "\n" <<  this->GetShop_name() << "\nUnique ID : " << this->Get_Unique_ID() << "\nShop Name : "  << this->GetShop_name() << "\nShop Address : " << this->GetShop_address() << "\nNo\&. Iphones : " << this->GetNumber_of_iphones() << "\nNo\&. Samsung : " << this->GetNumber_of_samsung() << "\nNo\&. Sony : " << this->GetNumber_of_sony() << "\nNo\&. Huawei : " << this->GetNumber_of_huawei() << "\nNo\&. Nokia : " << this->GetNumber_of_nokia() << "\nNo\&. Alcatel : " << this->GetNumber_of_alcatel() << "\nVersion number : " << this->Get_Version() << std::endl;
63 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "int CARPHONE_WAREHOUSE::_number_of_alcatel\fC [private]\fP"

.PP
Definition at line 118 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_alcatel(), operator=(), and SetNumber_of_alcatel()\&.
.SS "int CARPHONE_WAREHOUSE::_number_of_huawei\fC [private]\fP"

.PP
Definition at line 116 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_huawei(), operator=(), and SetNumber_of_huawei()\&.
.SS "int CARPHONE_WAREHOUSE::_number_of_iphones\fC [private]\fP"

.PP
Definition at line 113 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_iphones(), operator=(), and SetNumber_of_iphones()\&.
.SS "int CARPHONE_WAREHOUSE::_number_of_nokia\fC [private]\fP"

.PP
Definition at line 117 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_nokia(), operator=(), and SetNumber_of_nokia()\&.
.SS "int CARPHONE_WAREHOUSE::_number_of_samsung\fC [private]\fP"

.PP
Definition at line 114 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_samsung(), operator=(), and SetNumber_of_samsung()\&.
.SS "int CARPHONE_WAREHOUSE::_number_of_sony\fC [private]\fP"

.PP
Definition at line 115 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetNumber_of_sony(), operator=(), and SetNumber_of_sony()\&.
.SS "std::string CARPHONE_WAREHOUSE::_shop_address\fC [private]\fP"

.PP
Definition at line 111 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), copy(), GetShop_address(), operator=(), and SetShop_address()\&.
.SS "std::string CARPHONE_WAREHOUSE::_shop_name\fC [private]\fP"

.PP
Definition at line 112 of file CARPHONE_WAREHOUSE\&.h\&.
.PP
Referenced by CARPHONE_WAREHOUSE(), GetShop_name(), operator=(), and SetShop_name()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software transactional Memory from the source code\&.
