main.cpp
NAME
main.cpp -
SYNOPSIS
#include <cstdlib>
#include <iostream>
#include <thread>
#include 'TM.h'
#include 'AIB.h'
#include 'BOI.h'
#include 'BOA.h'
#include 'SWBPLC.h'
#include 'ULSTER.h'
#include 'UNBL.h'
#include 'WAREHOUSE.h'
#include 'CARPHONE_WAREHOUSE.h'
#include 'CARLOW_W.h'
#include 'KILKENNY_W.h'
#include 'TALLAGH_W.h'
#include 'DUNDALK_W.h'
#include 'SLIGO_W.h'
#include <mutex>
#include <memory>
#include <condition_variable>
#include <vector>
Functions
void _complex_transfer_ (std::shared_ptr< OSTM > _from_, std::shared_ptr< OSTM > _from_two_, std::vector< std::shared_ptr< OSTM >> _customer_vec, TM &_tm, double _amount)
complex_transfer function, takes two std::shared_ptr<OSTM> pointer, a vector of std::shared_ptr<OSTM> pointers, the Transaction manager, and the amount to use in the transaction, and transfer the _amount value from booth single objects to the objects to the vector collection
void _complex_warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _to_two, std::shared_ptr< OSTM > _to_three, std::vector< std::shared_ptr< OSTM >> _warehouse_vec, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
void _nested_warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _to_two, std::shared_ptr< OSTM > _to_three, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
nested_warehouse_transfer function, takes three std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
void _nesting_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
nesting function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account This function create nested transactions inside the transaction, and call other function to nesting the transaction as well
void _six_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_one_, std::shared_ptr< OSTM > _from_two_, std::shared_ptr< OSTM > _from_three_, std::shared_ptr< OSTM > _from_four_, std::shared_ptr< OSTM > _from_five_, TM &_tm, double _amount)
six_account_transfer function, takes six std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from five account to one account
void _two_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
two_account_transfer function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
void _warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM &_tm, double _amount)
warehouse_transfer function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
int main (void)
Variables
static int vector_number = 600
Function Documentation
void _complex_transfer_ (std::shared_ptr< OSTM > _from_, std::shared_ptr< OSTM > _from_two_, std::vector< std::shared_ptr< OSTM >> _customer_vec, TM & _tm, double _amount)
complex_transfer function, takes two std::shared_ptr<OSTM> pointer, a vector of std::shared_ptr<OSTM> pointers, the Transaction manager, and the amount to use in the transaction, and transfer the _amount value from booth single objects to the objects to the vector collection
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<BANK> type, FROM & FROM_TWO & TO
std::shared_ptr<OSTM> type, FROM_OSTM_ONE & FROM_OSTM_TWO & TO_OSTM
Register the two single account
Declare required pointers
Register customers accounts from the collection (vector)
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 294 of file main.cpp.
References TM::_get_tx(), and BANK::SetBalance().
                                                                                                                                                           {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_from_);
    tx->_register(_from_two_);
    std::shared_ptr<OSTM> _FROM_OSTM_ONE_, _FROM_OSTM_TWO_, _TO_OSTM_;
    std::shared_ptr<BANK> _FROM_, _FROM_TWO_, _TO_;
    bool done = false;
    try {
        while (!done) {
            // for (int i = 0; i < vector_number; ++i) {
            for (auto&& obj : _customer_vec) {
                // auto&& obj = _customer_vec.at(i);
                tx->_register(obj);
                _FROM_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
                _FROM_TWO_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_two_));
                _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(obj));
                _FROM_->SetBalance(_FROM_->GetBalance() - _amount);
                _FROM_TWO_->SetBalance(_FROM_TWO_->GetBalance() - _amount);
                _TO_->SetBalance(_TO_->GetBalance() + (_amount * 2));
                _FROM_OSTM_ONE_ = std::dynamic_pointer_cast<OSTM> (_FROM_);
                _FROM_OSTM_TWO_ = std::dynamic_pointer_cast<OSTM> (_FROM_TWO_);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_);
                tx->store(_FROM_OSTM_ONE_);
                tx->store(_FROM_OSTM_TWO_);
                tx->store(_TO_OSTM_);
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _complex_warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _to_two, std::shared_ptr< OSTM > _to_three, std::vector< std::shared_ptr< OSTM >> _warehouse_vec, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
Register the two single account
Declare required pointers
Register customers accounts from the collection (vector)
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<WAREHOUSE> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED WAREHOUSE TEST _to_two
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 518 of file main.cpp.
References TM::_get_tx(), _nested_warehouse_transfer_(), _warehouse_transfer_(), and WAREHOUSE::SetNumber_of_nokia().
                                                                                                                                                                                                                            {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_to_two);
    tx->_register(_to_three);
    tx->_register(_from_);
    std::shared_ptr<WAREHOUSE> _TO_SHOP_, _TO_SHOP_TWO, _TO_SHOP_VEC, _FROM_DIST_;
    std::shared_ptr<OSTM> _TO_OSTM_, _TO_OSTM_TWO, _TO_OSTM_VEC, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            // for (int i = 0; i < vector_number; ++i) {
            for (auto&& obj : _warehouse_vec) {
                //auto&& obj = _warehouse_vec.at(i);
                tx->_register(obj);
                _TO_SHOP_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_to_));
                _TO_SHOP_TWO = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_to_two));
                _TO_SHOP_VEC = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(obj));
                _FROM_DIST_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_from_));
                _TO_SHOP_->SetNumber_of_nokia(_TO_SHOP_->GetNumber_of_nokia() + _amount);
                _TO_SHOP_TWO->SetNumber_of_nokia(_TO_SHOP_TWO->GetNumber_of_nokia() + _amount);
                _TO_SHOP_VEC->SetNumber_of_nokia(_TO_SHOP_VEC->GetNumber_of_nokia() + _amount);
                _FROM_DIST_->SetNumber_of_nokia(_FROM_DIST_->GetNumber_of_nokia() - (_amount * 3));
                _TO_SHOP_->SetNumber_of_samsung(_TO_SHOP_->GetNumber_of_samsung() + _amount);
                _TO_SHOP_TWO->SetNumber_of_samsung(_TO_SHOP_TWO->GetNumber_of_samsung() + _amount);
                _TO_SHOP_VEC->SetNumber_of_samsung(_TO_SHOP_VEC->GetNumber_of_samsung() + _amount);
                _FROM_DIST_->SetNumber_of_samsung(_FROM_DIST_->GetNumber_of_samsung() - (_amount * 3));
                _TO_SHOP_->SetNumber_of_iphones(_TO_SHOP_->GetNumber_of_iphones() + _amount);
                _TO_SHOP_TWO->SetNumber_of_iphones(_TO_SHOP_TWO->GetNumber_of_iphones() + _amount);
                _TO_SHOP_VEC->SetNumber_of_iphones(_TO_SHOP_VEC->GetNumber_of_iphones() + _amount);
                _FROM_DIST_->SetNumber_of_iphones(_FROM_DIST_->GetNumber_of_iphones() - (_amount * 3));
                _TO_SHOP_->SetNumber_of_sony(_TO_SHOP_->GetNumber_of_sony() + _amount);
                _TO_SHOP_TWO->SetNumber_of_sony(_TO_SHOP_TWO->GetNumber_of_sony() + _amount);
                _TO_SHOP_VEC->SetNumber_of_sony(_TO_SHOP_VEC->GetNumber_of_sony() + _amount);
                _FROM_DIST_->SetNumber_of_sony(_FROM_DIST_->GetNumber_of_sony() - (_amount * 3));
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_);
                _TO_OSTM_TWO = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_TWO);
                _TO_OSTM_VEC = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_VEC);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_DIST_);
                tx->store(_TO_OSTM_);
                tx->store(_TO_SHOP_TWO);
                tx->store(_TO_SHOP_VEC);
                tx->store(_FROM_OSTM_);
            }
            std::shared_ptr<TX> txTwo = _tm._get_tx();
            bool nestedDone = false;
            while (!nestedDone) {
                _TO_SHOP_ = std::dynamic_pointer_cast<WAREHOUSE> (txTwo->load(_to_two));
                _FROM_DIST_ = std::dynamic_pointer_cast<WAREHOUSE> (txTwo->load(_from_));
                _TO_SHOP_->SetNumber_of_nokia(_TO_SHOP_->GetNumber_of_nokia() + _amount);
                _FROM_DIST_->SetNumber_of_nokia(_FROM_DIST_->GetNumber_of_nokia() - _amount);
                _TO_SHOP_->SetNumber_of_samsung(_TO_SHOP_->GetNumber_of_samsung() + _amount);
                _FROM_DIST_->SetNumber_of_samsung(_FROM_DIST_->GetNumber_of_samsung() - _amount);
                _TO_SHOP_->SetNumber_of_iphones(_TO_SHOP_->GetNumber_of_iphones() + _amount);
                _FROM_DIST_->SetNumber_of_iphones(_FROM_DIST_->GetNumber_of_iphones() - _amount);
                _TO_SHOP_->SetNumber_of_sony(_TO_SHOP_->GetNumber_of_sony() + _amount);
                _FROM_DIST_->SetNumber_of_sony(_FROM_DIST_->GetNumber_of_sony() - _amount);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_DIST_);
                txTwo->store(_TO_OSTM_);
                txTwo->store(_FROM_OSTM_);
                /*
                 * NESTED TRANSACTION TEST _to_three
                 */
                _warehouse_transfer_(_to_three, _from_, _tm, _amount);
                _nested_warehouse_transfer_(_to_, _to_two, _to_three, _from_, _tm, _amount);
                nestedDone = tx->commit();
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _nested_warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _to_two, std::shared_ptr< OSTM > _to_three, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
nested_warehouse_transfer function, takes three std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<WAREHOUSE> type, TO_SHOP & FROM_DIST
std::shared_ptr<OSTM> type, TO_OSTM & FROM_OSTM
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED WAREHOUSE TEST _to_two
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 419 of file main.cpp.
References TM::_get_tx(), _warehouse_transfer_(), and WAREHOUSE::SetNumber_of_nokia().
Referenced by _complex_warehouse_transfer_().
                                                                                                                                                                            {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_to_two);
    tx->_register(_to_three);
    tx->_register(_from_);
    std::shared_ptr<WAREHOUSE> _TO_SHOP_, _FROM_DIST_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_SHOP_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_to_));
            _FROM_DIST_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_from_));
            _TO_SHOP_->SetNumber_of_nokia(_TO_SHOP_->GetNumber_of_nokia() + _amount);
            _FROM_DIST_->SetNumber_of_nokia(_FROM_DIST_->GetNumber_of_nokia() - _amount);
            _TO_SHOP_->SetNumber_of_samsung(_TO_SHOP_->GetNumber_of_samsung() + _amount);
            _FROM_DIST_->SetNumber_of_samsung(_FROM_DIST_->GetNumber_of_samsung() - _amount);
            _TO_SHOP_->SetNumber_of_iphones(_TO_SHOP_->GetNumber_of_iphones() + _amount);
            _FROM_DIST_->SetNumber_of_iphones(_FROM_DIST_->GetNumber_of_iphones() - _amount);
            _TO_SHOP_->SetNumber_of_sony(_TO_SHOP_->GetNumber_of_sony() + _amount);
            _FROM_DIST_->SetNumber_of_sony(_FROM_DIST_->GetNumber_of_sony() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_DIST_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            std::shared_ptr<TX> txTwo = _tm._get_tx();
            bool nestedDone = false;
            while (!nestedDone) {
                _TO_SHOP_ = std::dynamic_pointer_cast<WAREHOUSE> (txTwo->load(_to_two));
                _FROM_DIST_ = std::dynamic_pointer_cast<WAREHOUSE> (txTwo->load(_from_));
                _TO_SHOP_->SetNumber_of_nokia(_TO_SHOP_->GetNumber_of_nokia() + _amount);
                _FROM_DIST_->SetNumber_of_nokia(_FROM_DIST_->GetNumber_of_nokia() - _amount);
                _TO_SHOP_->SetNumber_of_samsung(_TO_SHOP_->GetNumber_of_samsung() + _amount);
                _FROM_DIST_->SetNumber_of_samsung(_FROM_DIST_->GetNumber_of_samsung() - _amount);
                _TO_SHOP_->SetNumber_of_iphones(_TO_SHOP_->GetNumber_of_iphones() + _amount);
                _FROM_DIST_->SetNumber_of_iphones(_FROM_DIST_->GetNumber_of_iphones() - _amount);
                _TO_SHOP_->SetNumber_of_sony(_TO_SHOP_->GetNumber_of_sony() + _amount);
                _FROM_DIST_->SetNumber_of_sony(_FROM_DIST_->GetNumber_of_sony() - _amount);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_DIST_);
                txTwo->store(_TO_OSTM_);
                txTwo->store(_FROM_OSTM_);
                /*
                 * NESTED TRANSACTION TEST _to_three
                 */
                _warehouse_transfer_(_to_three, _from_, _tm, _amount);
                nestedDone = tx->commit();
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _nesting_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
nesting function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account This function create nested transactions inside the transaction, and call other function to nesting the transaction as well
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<BANK> type, TO_BANK & FROM_BANK
std::shared_ptr<OSTM> type, TO_OSTM & FROM_OSTM
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED TRANSACTION
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED TRANSACTION IN THE NESTED TRANSACTION two_account_transfer function call
Commit changes
Definition at line 206 of file main.cpp.
References TM::_get_tx(), _two_account_transfer_(), and BANK::SetBalance().
Referenced by main().
                                                                                              {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_);
    std::shared_ptr<BANK> _TO_BANK_, _FROM_BANK_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
            _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
            _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            std::shared_ptr<TX> txTwo = _tm._get_tx();
            bool nestedDone = false;
            while (!nestedDone) {
                _TO_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_to_));
                _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_from_));
                _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
                _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
                txTwo->store(_TO_OSTM_);
                txTwo->store(_FROM_OSTM_);
                _two_account_transfer_(_to_, _from_, _tm, _amount);
                nestedDone = txTwo->commit();
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _six_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_one_, std::shared_ptr< OSTM > _from_two_, std::shared_ptr< OSTM > _from_three_, std::shared_ptr< OSTM > _from_four_, std::shared_ptr< OSTM > _from_five_, TM & _tm, double _amount)
six_account_transfer function, takes six std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from five account to one account
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<BANK> type, TO & FROM_ONE & FROM_TWO & FROM_THREE & FROM_FOUR & FROM_FIVE
std::shared_ptr<OSTM> type, _TO_OSTM & _FROM_ONE_OSTM & _FROM_TWO_OSTM & _FROM_THREE_OSTM & _FROM_FOUR_OSTM & _FROM_FIVE_OSTM
Register the two single account
Required pointers to use in transaction
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 51 of file main.cpp.
References TM::_get_tx(), and BANK::SetBalance().
                                                                                                                                                                                                                                                   {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_one_);
    tx->_register(_from_two_);
    tx->_register(_from_three_);
    tx->_register(_from_four_);
    tx->_register(_from_five_);
    std::shared_ptr<OSTM> _TO_OSTM, _FROM_ONE_OSTM, _FROM_TWO_OSTM, _FROM_THREE_OSTM, _FROM_FOUR_OSTM, _FROM_FIVE_OSTM;
    std::shared_ptr<BANK> _TO_, _FROM_ONE_, _FROM_TWO_, _FROM_THREE_, _FROM_FOUR_, _FROM_FIVE_;
    try {
        bool done = false;
        while (!done) {
            _TO_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_ONE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_one_));
            _FROM_TWO_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_two_));
            _FROM_THREE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_three_));
            _FROM_FOUR_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_four_));
            _FROM_FIVE_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_five_));
            _TO_->SetBalance(_TO_->GetBalance() + (_amount * 5));
            _FROM_ONE_->SetBalance(_FROM_ONE_->GetBalance() - _amount);
            _FROM_TWO_->SetBalance(_FROM_TWO_->GetBalance() - _amount);
            _FROM_THREE_->SetBalance(_FROM_THREE_->GetBalance() - _amount);
            _FROM_FOUR_->SetBalance(_FROM_FOUR_->GetBalance() - _amount);
            _FROM_FIVE_->SetBalance(_FROM_FIVE_->GetBalance() - _amount);
            _TO_OSTM = std::dynamic_pointer_cast<OSTM> (_TO_);
            _FROM_ONE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_ONE_);
            _FROM_TWO_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_TWO_);
            _FROM_THREE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_THREE_);
            _FROM_FOUR_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_FOUR_);
            _FROM_FIVE_OSTM = std::dynamic_pointer_cast<OSTM> (_FROM_FIVE_);
            tx->store(_TO_OSTM);
            tx->store(_FROM_ONE_OSTM);
            tx->store(_FROM_TWO_OSTM);
            tx->store(_FROM_THREE_OSTM);
            tx->store(_FROM_FOUR_OSTM);
            tx->store(_FROM_FIVE_OSTM);
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _two_account_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
two_account_transfer function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<BANK> type, TO_BANK & FROM_BANK
std::shared_ptr<OSTM> type, TO_OSTM & FROM_OSTM
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
NESTED TRANSACTION
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Commit changes
Definition at line 123 of file main.cpp.
References TM::_get_tx(), and BANK::SetBalance().
Referenced by _nesting_().
                                                                                                           {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_);
    std::shared_ptr<BANK> _TO_BANK_, _FROM_BANK_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_to_));
            _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (tx->load(_from_));
            _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
            _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            std::shared_ptr<TX> txTwo = _tm._get_tx();
            bool nestedDone = false;
            while (!nestedDone) {
                _TO_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_to_));
                _FROM_BANK_ = std::dynamic_pointer_cast<BANK> (txTwo->load(_from_));
                _TO_BANK_->SetBalance(_TO_BANK_->GetBalance() + _amount);
                _FROM_BANK_->SetBalance(_FROM_BANK_->GetBalance() - _amount);
                _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_BANK_);
                _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_BANK_);
                txTwo->store(_TO_OSTM_);
                txTwo->store(_FROM_OSTM_);
                nestedDone = txTwo->commit();
            }
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
void _warehouse_transfer_ (std::shared_ptr< OSTM > _to_, std::shared_ptr< OSTM > _from_, TM & _tm, double _amount)
warehouse_transfer function, takes two std::shared_ptr<OSTM> pointer, the Transaction manager, and the amount to use in the transaction and transfer the _amount value from one account to the another account
Parameters:
std::shared_ptr<TX> tx, Transaction Object
std::shared_ptr<WAREHOUSE> type, TO_SHOP & FROM_DIST
std::shared_ptr<OSTM> type, TO_OSTM & FROM_OSTM
Register the two single account
Declare required pointers
From std::shared_ptr<OSTM> to std::shared_ptr<BANK> to access the virtual methods
Make changes with the objects
From std::shared_ptr<BANK> to std::shared_ptr<OSTM> to store the memory spaces
Store changes
Commit changes
Definition at line 358 of file main.cpp.
References TM::_get_tx(), and WAREHOUSE::SetNumber_of_nokia().
Referenced by _complex_warehouse_transfer_(), and _nested_warehouse_transfer_().
                                                                                                         {
    std::shared_ptr<TX> tx = _tm._get_tx();
    tx->_register(_to_);
    tx->_register(_from_);
    std::shared_ptr<WAREHOUSE> _TO_SHOP_, _FROM_DIST_;
    std::shared_ptr<OSTM> _TO_OSTM_, _FROM_OSTM_;
    bool done = false;
    try {
        while (!done) {
            _TO_SHOP_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_to_));
            _FROM_DIST_ = std::dynamic_pointer_cast<WAREHOUSE> (tx->load(_from_));
            _TO_SHOP_->SetNumber_of_nokia(_TO_SHOP_->GetNumber_of_nokia() + _amount);
            _FROM_DIST_->SetNumber_of_nokia(_FROM_DIST_->GetNumber_of_nokia() - _amount);
            _TO_SHOP_->SetNumber_of_samsung(_TO_SHOP_->GetNumber_of_samsung() + _amount);
            _FROM_DIST_->SetNumber_of_samsung(_FROM_DIST_->GetNumber_of_samsung() - _amount);
            _TO_SHOP_->SetNumber_of_iphones(_TO_SHOP_->GetNumber_of_iphones() + _amount);
            _FROM_DIST_->SetNumber_of_iphones(_FROM_DIST_->GetNumber_of_iphones() - _amount);
            _TO_SHOP_->SetNumber_of_sony(_TO_SHOP_->GetNumber_of_sony() + _amount);
            _FROM_DIST_->SetNumber_of_sony(_FROM_DIST_->GetNumber_of_sony() - _amount);
            _TO_OSTM_ = std::dynamic_pointer_cast<OSTM> (_TO_SHOP_);
            _FROM_OSTM_ = std::dynamic_pointer_cast<OSTM> (_FROM_DIST_);
            tx->store(_TO_OSTM_);
            tx->store(_FROM_OSTM_);
            done = tx->commit();
        }
    } catch (std::runtime_error& e) {
        std::cout << e.what() << std::endl;
    }
}
int main (void)
main method to run test Get the Transaction Manager
 TM& tm = TM::Instance();
Create vector to store std::shared_ptr<OSTM> pointers. All object will have unique ID by default
 std::vector<std::shared_ptr<OSTM>> _customer_vec(vector_number);
 std::vector<std::shared_ptr<OSTM>> _warehouse_vec(vector_number);
Create objects type of BANK. All object will have unique ID by default
 std::shared_ptr<OSTM> aib_ptr = new AIB(100, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
 std::shared_ptr<OSTM> boi_ptr = new BOI(200, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
 std::shared_ptr<OSTM> boa_ptr = new BOA(300, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
 std::shared_ptr<OSTM> swplc_ptr = new SWBPLC(400, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
 std::shared_ptr<OSTM> ulster_ptr = new ULSTER(500, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
 std::shared_ptr<OSTM> unbl_ptr = new UNBL(600, 500, 'Joe', 'Blog', 'High street, Kilkenny, Co.Kilkenny');
Create objects type of WAREHOUSE. All object will have unique ID by default
 std::shared_ptr<OSTM> w_dist = new CARPHONE_WAREHOUSE();
 std::shared_ptr<OSTM> c_shop = new CARLOW_W();
 std::shared_ptr<OSTM> k_shop = new KILKENNY_W();
 std::shared_ptr<OSTM> t_shop = new TALLAGH_W();
 std::shared_ptr<OSTM> d_shop = new DUNDALK_W();
 std::shared_ptr<OSTM> s_shop = new SLIGO_W();
Create vector of std::shared_ptr<OSTM> BANK pointers
 vector_number is 100 at the moment
 for(int i=0;i<vector_number;++i)
Create vector of std::shared_ptr<OSTM> WAREHOUSE pointers
 vector_number is 100 at the moment
 for(int i=0;i<vector_number;++i)
Display WAREHOUSE objects before transaction
 w_dist->toString();
 c_shop->toString();
 k_shop->toString();
 t_shop->toString();
 d_shop->toString();
 s_shop->toString();
Display BANK objects before transaction
 aib_ptr->toString();
 boi_ptr->toString();
 boa_ptr->toString();
 swplc_ptr->toString();
 ulster_ptr->toString();
 unbl_ptr->toString();
Parameters:
transferAmount in the transaction, control the value in the transaction between objetcs
threadArraySize control number of threads
 The logic in the IF ELSE statement distribute the threads between three different thread creating option.
 If the threadArraySize is divisible with three, the threads will be distributed between function.
 However, you can creates any number of threads, but to follow the correct output should increase the IF ELSE statement to distribute the threads in equal number.
Creating threads^n -> threadArraySize
 for (int i = 0; i < threadArraySize; ++i)
TEST 1 : Nested transaction Test
 thArray[i] = std::thread(nesting, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
TEST 2 :Three different type of function call where the objects are participating in multiple type of transactions
 thArray[i] = std::thread(two_account_transfer, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
 thArray[i] = std::thread(six_account_transfer, boi_ptr, boa_ptr, swplc_ptr, ulster_ptr, aib_ptr, unbl_ptr, std::ref(tm), transferAmount)
 thArray[i] = std::thread(complex_transfer, aib_ptr, boi_ptr, std::ref(_customer_vec), std::ref(tm), transferAmount);
TEST 3 : Testing WAREHOUSE type pointers within transactions
 thArray[i] = std::thread(phone_transfer, c_shop, w_dist, std::ref(tm), transferAmount);
TEST 4 : Testing WAREHOUSE type pointers within nested transactions
 thArray[i] = std::thread(nested_warehouse_transfer, c_shop, d_shop, k_shop, w_dist, std::ref(tm), transferAmount);
TEST 5 : Testing WAREHOUSE type pointers within mixed and nested transactions
 thArray[i] = std::thread(warehouse_transfer, c_shop, w_dist, std::ref(tm), transferAmount);
 thArray[i] = std::thread(nested_warehouse_transfer, c_shop, d_shop, k_shop, w_dist, std::ref(tm), transferAmount);
 thArray[i] = std::thread(complex_warehouse_transfer, d_shop, c_shop, std::ref(_warehouse_vec), w_dist, std::ref(tm), transferAmount);
Display objects after all transactions are finished
 Uncomment the required corresponding TEST to display results
Extra tx to call and display ROLLBACK value
 std::shared_ptr<TX> tx = tm._get_tx();
Display the number of ROLLBACK by all the threads
 std::cout << 'Rollback counter is : ' << tx->getTest_counter() << std::endl;
Display object from vector
Clean up Transaction Manager from all main process associated transactions
 tm._TX_EXIT();
Display all Transactions associated with the main process. It should be empty after _TX_EXIT() function call!!!
 tm.print_all();
Definition at line 649 of file main.cpp.
References TM::_get_tx(), _nesting_(), TM::_TX_EXIT(), TM::Instance(), TM::print_all(), and vector_number.
               {
    TM& tm = TM::Instance();
    std::vector<std::shared_ptr < OSTM>>_customer_vec; //(vector_number);
    std::vector<std::shared_ptr < OSTM>>_warehouse_vec; //(vector_number);
    std::shared_ptr<OSTM> aib_ptr(new AIB(100, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boi_ptr(new BOI(200, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> boa_ptr(new BOA(300, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> swplc_ptr(new SWBPLC(400, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> ulster_ptr(new ULSTER(500, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> unbl_ptr(new UNBL(600, 500, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
    std::shared_ptr<OSTM> w_dist(new CARPHONE_WAREHOUSE());
    std::shared_ptr<OSTM> c_shop(new CARLOW_W());
    std::shared_ptr<OSTM> k_shop(new KILKENNY_W());
    std::shared_ptr<OSTM> t_shop(new TALLAGH_W());
    std::shared_ptr<OSTM> d_shop(new DUNDALK_W());
    std::shared_ptr<OSTM> s_shop(new SLIGO_W());
    for (int i = 0; i < vector_number; ++i) {
        if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new CARLOW_W());
            _warehouse_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new KILKENNY_W());
            _warehouse_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new TALLAGH_W());
            _warehouse_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new DUNDALK_W());
            _warehouse_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SLIGO_W());
            _warehouse_vec.push_back(std::move(sharedptr));
        }
    }
    for (int i = 0; i < vector_number; ++i) {
        if (i % 6 == 0) {
            std::shared_ptr<OSTM> sharedptr(new AIB(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 5 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOI(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 4 == 0) {
            std::shared_ptr<OSTM> sharedptr(new BOA(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 3 == 0) {
            std::shared_ptr<OSTM> sharedptr(new SWBPLC(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 2 == 0) {
            std::shared_ptr<OSTM> sharedptr(new ULSTER(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        } else if (i % 1 == 0) {
            std::shared_ptr<OSTM> sharedptr(new UNBL(i, 50, "Joe", "Blog", "High street, Kilkenny, Co.Kilkenny"));
            _customer_vec.push_back(std::move(sharedptr));
        }
    }
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    // d_shop->toString();
    // s_shop->toString();
    /*
     * TEST 1 : object requirements
     */
    aib_ptr->toString();
    boi_ptr->toString();
    /*
     * TEST 2 : object requirements
     */
    // aib_ptr->toString();
    // boi_ptr->toString();
    // boa_ptr->toString();
    // swplc_ptr->toString();
    // ulster_ptr->toString();
    // unbl_ptr->toString();
    // for(int i=0; i<vector_number; ++i){
    // _customer_vec[i]->toString();
    // }
    /*
     * TEST 3 : object requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    /*
     * TEST 4 : objects requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    // d_shop->toString();
    // s_shop->toString();
    /*
     * TEST 5 : objects requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    // d_shop->toString();
    // s_shop->toString();
    // for(auto&& elem: _warehouse_vec){
    // elem->toString(); // virtual dispatch
    //
    // }
    int transferAmount = 1;
    int threadArraySize = 99;
    std::thread thArray[threadArraySize];
    for (int i = 0; i < threadArraySize; ++i) {
        if (i % 3 == 0)
            thArray[i] = std::thread(_nesting_, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
        else if (i % 2 == 0)
            thArray[i] = std::thread(_nesting_, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
        else if (i % 1 == 0)
            thArray[i] = std::thread(_nesting_, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
        // if (i % 3 == 0)
        // thArray[i] = std::thread(_two_account_transfer_, aib_ptr, boi_ptr, std::ref(tm), transferAmount);
        // else if (i % 2 == 0)
        // thArray[i] = std::thread(_six_account_transfer_, boi_ptr, boa_ptr, swplc_ptr, ulster_ptr, aib_ptr, unbl_ptr, std::ref(tm), transferAmount);
        // else if (i % 1 == 0)
        // thArray[i] = std::thread(_complex_transfer_, aib_ptr, boi_ptr, std::ref(_customer_vec), std::ref(tm), transferAmount);
        // if (i % 3 == 0)
        // thArray[i] = std::thread(_warehouse_transfer_, c_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 2 == 0)
        // thArray[i] = std::thread(_warehouse_transfer_, k_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 1 == 0)
        // thArray[i] = std::thread(_warehouse_transfer_, t_shop, w_dist, std::ref(tm), transferAmount);
        // if (i % 3 == 0)
        // thArray[i] = std::thread(_nested_warehouse_transfer_, c_shop, d_shop, k_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 2 == 0)
        // thArray[i] = std::thread(_nested_warehouse_transfer_, k_shop, s_shop, t_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 1 == 0)
        // thArray[i] = std::thread(_nested_warehouse_transfer_, t_shop, c_shop, s_shop, w_dist, std::ref(tm), transferAmount);
        // if (i % 3 == 0)
        // thArray[i] = std::thread(_warehouse_transfer_, c_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 2 == 0)
        // thArray[i] = std::thread(_nested_warehouse_transfer_, k_shop, s_shop, t_shop, w_dist, std::ref(tm), transferAmount);
        // else if (i % 1 == 0)
        // thArray[i] = std::thread(_complex_warehouse_transfer_, d_shop, s_shop, c_shop, std::ref(_warehouse_vec), w_dist, std::ref(tm), transferAmount);
    }
    /*
     * Join threads^n -> threadArraySize<br>
     * thArray[i].join();
     */
    for (int i = 0; i < threadArraySize; ++i) {
        thArray[i].join();
    }
    std::cout << "\nMain process print " << std::endl;
    /*
     * TEST 1 : object requirements
     */
    aib_ptr->toString();
    boi_ptr->toString();
    /*
     * TEST 2 : object requirements
     */
    // aib_ptr->toString();
    // boi_ptr->toString();
    // boa_ptr->toString();
    // swplc_ptr->toString();
    // ulster_ptr->toString();
    // unbl_ptr->toString();
    // for(int i=0; i<vector_number; ++i){
    // _customer_vec[i]->toString();
    // }
    /*
     * TEST 3 : object requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    /*
     * TEST 4 : objects requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    // d_shop->toString();
    // s_shop->toString();
    /*
     * TEST 5 : objects requirements
     */
    // w_dist->toString();
    // c_shop->toString();
    // k_shop->toString();
    // t_shop->toString();
    // d_shop->toString();
    // s_shop->toString();
    // for(auto&& elem: _warehouse_vec){
    // elem->toString(); // virtual dispatch
    //
    // }
    /* TEST 5 FINISH */
    std::cout << "\nMAIN PROCESS EXIT !!!! " << std::endl;
    std::shared_ptr<TX> tx = tm._get_tx();
    std::cout << "Rollback counter is : " << tx->getTest_counter() << std::endl;
    // std::cout << "[vector_number]" << std::endl;
    // for (int i = 0; i < vector_number; ++i) {
    // //_customer_vec[i]->toString();
    // auto&& os = _customer_vec.at(i);
    // os->toString();
    // }
    // std::cout << "[_warehouse_vec]" << std::endl;
    // for(auto&& elem: _warehouse_vec){
    // elem->toString(); // virtual dispatch
    //
    // }
    //_customer_vec[10]->toString();
    tm._TX_EXIT();
    std::cout << "\nPRINT ALL FROM TM !!!! SHOULD BE EMPTY AFTER _TX_EXIT() !!" << std::endl;
    tm.print_all();
    return 0;
}
Variable Documentation
int vector_number = 600 [static]
Parameters:
vector_number control the size of the vector to store std::shared_ptr<OSTM> pointer
Definition at line 43 of file main.cpp.
Referenced by main().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.