SWBPLC
NAME
SWBPLC -
SYNOPSIS
#include <SWBPLC.h>
Inherits BANK.
Public Member Functions
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual int GetAccountNumber () const
virtual std::string GetAddress () const
virtual double GetBalance () const
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
virtual std::string GetFirstName () const
virtual std::string GetFullname () const
virtual std::string GetLastName () const
SWBPLC operator= (const SWBPLC &orig)
virtual void SetAccountNumber (int accountNumber)
virtual void SetAddress (std::string address)
virtual void SetBalance (double balance)
virtual void SetFirstName (std::string firstName)
virtual void SetFullname (std::string fullname)
virtual void SetLastName (std::string lastName)
SWBPLC ()
SWBPLC (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)
SWBPLC (std::shared_ptr< BANK > obj, int _version, int _unique_id)
SWBPLC (const SWBPLC &orig)
virtual void toString ()
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type
virtual ~SWBPLC ()
Private Attributes
int accountNumber
std::string address
double balance
std::string firstName
std::string fullname
std::string lastName
Detailed Description
Inherit from BANK
Definition at line 19 of file SWBPLC.h.
Constructor & Destructor Documentation
SWBPLC::SWBPLC () [inline]
Constructor
Definition at line 24 of file SWBPLC.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
Referenced by getBaseCopy(), and SWBPLC().
             : BANK() {
        this->accountNumber = 0;
        this->balance = 50;
        this->firstName = "Joe";
        this->lastName = "Blog";
        this->address = "High street, Carlow";
        this->fullname = firstName + " " + lastName;
    };
SWBPLC::SWBPLC (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address) [inline]
Custom constructor
Definition at line 35 of file SWBPLC.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
                                                                                                          : BANK() {
        this->accountNumber = accountNumber;
        this->balance = balance;
        this->firstName = firstName;
        this->lastName = lastName;
        this->address = address;
        this->fullname = firstName + " " + lastName;
    };
SWBPLC::SWBPLC (std::shared_ptr< BANK > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Definition at line 46 of file SWBPLC.h.
References accountNumber, address, balance, firstName, fullname, lastName, and SWBPLC().
                                                                  : BANK(_version, _unique_id) {
        this->accountNumber = obj->GetAccountNumber();
        this->balance = obj->GetBalance();
        this->firstName = obj->GetFirstName();
        this->lastName = obj->GetLastName();
        this->address = obj->GetAddress();
        this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
        
    };
SWBPLC::SWBPLC (const SWBPLC & orig)
Copy constructor
Definition at line 12 of file SWBPLC.cpp.
                                 {
}
SWBPLC::~SWBPLC () [virtual]
de-constructor
Definition at line 15 of file SWBPLC.cpp.
Referenced by operator=().
                {
}
Member Function Documentation
void SWBPLC::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer
Parameters:
objTO is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
objFROM is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
Reimplemented from OSTM.
Definition at line 34 of file SWBPLC.cpp.
References OSTM::Set_Unique_ID().
Referenced by operator=().
                                                                 {
    std::shared_ptr<SWBPLC> objTO = std::dynamic_pointer_cast<SWBPLC>(to);
    std::shared_ptr<SWBPLC> objFROM = std::dynamic_pointer_cast<SWBPLC>(from);
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    objTO->SetAccountNumber(objFROM->GetAccountNumber());
    objTO->SetBalance(objFROM->GetBalance());
    
}
int SWBPLC::GetAccountNumber () const [virtual]
Reimplemented from BANK.
Definition at line 80 of file SWBPLC.cpp.
References accountNumber.
Referenced by operator=(), and toString().
                                   {
    return accountNumber;
}
std::string SWBPLC::GetAddress () const [virtual]
Reimplemented from BANK.
Definition at line 64 of file SWBPLC.cpp.
References address.
Referenced by operator=().
                                   {
    return address;
}
double SWBPLC::GetBalance () const [virtual]
Reimplemented from BANK.
Definition at line 72 of file SWBPLC.cpp.
References balance.
Referenced by operator=(), and toString().
                                {
    return balance;
}
std::shared_ptr< OSTM > SWBPLC::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
Parameters:
objTO is a BANK type pointer for casting
obj is a std::shared_ptr<BANK> return type
Reimplemented from OSTM.
Definition at line 22 of file SWBPLC.cpp.
References SWBPLC().
Referenced by operator=().
{
    std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
    std::shared_ptr<BANK> obj(new SWBPLC(objTO,object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
std::string SWBPLC::GetFirstName () const [virtual]
Reimplemented from BANK.
Definition at line 96 of file SWBPLC.cpp.
References firstName.
Referenced by operator=(), and toString().
                                     {
    return firstName;
}
std::string SWBPLC::GetFullname () const [virtual]
Reimplemented from BANK.
Definition at line 104 of file SWBPLC.cpp.
References fullname.
Referenced by operator=().
                                    {
    return fullname;
}
std::string SWBPLC::GetLastName () const [virtual]
Reimplemented from BANK.
Definition at line 88 of file SWBPLC.cpp.
References lastName.
Referenced by operator=(), and toString().
                                    {
    return lastName;
}
SWBPLC SWBPLC::operator= (const SWBPLC & orig) [inline]
Operator
Definition at line 63 of file SWBPLC.h.
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~SWBPLC().
{};
void SWBPLC::SetAccountNumber (int accountNumber) [virtual]
Reimplemented from BANK.
Definition at line 76 of file SWBPLC.cpp.
References accountNumber.
Referenced by operator=().
                                               {
    this->accountNumber = accountNumber;
}
void SWBPLC::SetAddress (std::string address) [virtual]
Reimplemented from BANK.
Definition at line 60 of file SWBPLC.cpp.
References address.
Referenced by operator=().
                                         {
    this->address = address;
}
void SWBPLC::SetBalance (double balance) [virtual]
Reimplemented from BANK.
Definition at line 68 of file SWBPLC.cpp.
References balance.
Referenced by operator=().
                                      {
    this->balance = balance;
}
void SWBPLC::SetFirstName (std::string firstName) [virtual]
Reimplemented from BANK.
Definition at line 92 of file SWBPLC.cpp.
References firstName.
Referenced by operator=().
                                             {
    this->firstName = firstName;
}
void SWBPLC::SetFullname (std::string fullname) [virtual]
Reimplemented from BANK.
Definition at line 100 of file SWBPLC.cpp.
References fullname.
Referenced by operator=().
                                           {
    this->fullname = fullname;
}
void SWBPLC::SetLastName (std::string lastName) [virtual]
Reimplemented from BANK.
Definition at line 84 of file SWBPLC.cpp.
References lastName.
Referenced by operator=().
                                           {
    this->lastName = lastName;
}
void SWBPLC::toString () [virtual]
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way
Reimplemented from OSTM.
Definition at line 55 of file SWBPLC.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName().
Referenced by operator=().
{
     std::cout << "\nSWBPLC BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int SWBPLC::accountNumber [private]
Definition at line 96 of file SWBPLC.h.
Referenced by GetAccountNumber(), operator=(), SetAccountNumber(), and SWBPLC().
std::string SWBPLC::address [private]
Definition at line 98 of file SWBPLC.h.
Referenced by GetAddress(), operator=(), SetAddress(), and SWBPLC().
double SWBPLC::balance [private]
Definition at line 97 of file SWBPLC.h.
Referenced by GetBalance(), operator=(), SetBalance(), and SWBPLC().
std::string SWBPLC::firstName [private]
Definition at line 94 of file SWBPLC.h.
Referenced by GetFirstName(), operator=(), SetFirstName(), and SWBPLC().
std::string SWBPLC::fullname [private]
Definition at line 93 of file SWBPLC.h.
Referenced by GetFullname(), operator=(), SetFullname(), and SWBPLC().
std::string SWBPLC::lastName [private]
Definition at line 95 of file SWBPLC.h.
Referenced by GetLastName(), operator=(), SetLastName(), and SWBPLC().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.