UNBL
NAME
UNBL -
SYNOPSIS
#include <UNBL.h>
Inherits BANK.
Public Member Functions
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual int GetAccountNumber () const
virtual std::string GetAddress () const
virtual double GetBalance () const
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
virtual std::string GetFirstName () const
virtual std::string GetFullname () const
virtual std::string GetLastName () const
UNBL operator= (const UNBL &orig)
virtual void SetAccountNumber (int accountNumber)
virtual void SetAddress (std::string address)
virtual void SetBalance (double balance)
virtual void SetFirstName (std::string firstName)
virtual void SetFullname (std::string fullname)
virtual void SetLastName (std::string lastName)
virtual void toString ()
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type
UNBL ()
UNBL (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)
UNBL (std::shared_ptr< BANK > obj, int _version, int _unique_id)
UNBL (const UNBL &orig)
virtual ~UNBL ()
Private Attributes
int accountNumber
std::string address
double balance
std::string firstName
std::string fullname
std::string lastName
Detailed Description
Inherit from BANK
Definition at line 19 of file UNBL.h.
Constructor & Destructor Documentation
UNBL::UNBL () [inline]
Constructor
Definition at line 24 of file UNBL.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
Referenced by getBaseCopy(), and UNBL().
           : BANK() {
        this->accountNumber = 0;
        this->balance = 50;
        this->firstName = "Joe";
        this->lastName = "Blog";
        this->address = "High street, Carlow";
        this->fullname = firstName + " " + lastName;
    };
UNBL::UNBL (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address) [inline]
Custom constructor
Definition at line 35 of file UNBL.h.
References accountNumber, address, balance, firstName, fullname, and lastName.
                                                                                                        : BANK() {
        this->accountNumber = accountNumber;
        this->balance = balance;
        this->firstName = firstName;
        this->lastName = lastName;
        this->address = address;
        this->fullname = firstName + " " + lastName;
    };
UNBL::UNBL (std::shared_ptr< BANK > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Definition at line 46 of file UNBL.h.
References accountNumber, address, balance, firstName, fullname, lastName, and UNBL().
                                                                : BANK(_version, _unique_id) {
 
        this->accountNumber = obj->GetAccountNumber();
        this->balance = obj->GetBalance();
        this->firstName = obj->GetFirstName();
        this->lastName = obj->GetLastName();
        this->address = obj->GetAddress();
        this->fullname = obj->GetFirstName() + " " + obj->GetLastName();
    };
UNBL::UNBL (const UNBL & orig)
Copy constructor
Definition at line 11 of file UNBL.cpp.
                           {
}
UNBL::~UNBL () [virtual]
de-constructor
Definition at line 14 of file UNBL.cpp.
Referenced by operator=().
            {
}
Member Function Documentation
void UNBL::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer
Parameters:
objTO is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
objFROM is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM>
Reimplemented from OSTM.
Definition at line 33 of file UNBL.cpp.
References OSTM::Set_Unique_ID().
Referenced by operator=().
                                                               {
    std::shared_ptr<UNBL> objTO = std::dynamic_pointer_cast<UNBL>(to);
    std::shared_ptr<UNBL> objFROM = std::dynamic_pointer_cast<UNBL>(from);
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    objTO->SetAccountNumber(objFROM->GetAccountNumber());
    objTO->SetBalance(objFROM->GetBalance());
   
}
int UNBL::GetAccountNumber () const [virtual]
Reimplemented from BANK.
Definition at line 78 of file UNBL.cpp.
References accountNumber.
Referenced by operator=(), and toString().
                                 {
    return accountNumber;
}
std::string UNBL::GetAddress () const [virtual]
Reimplemented from BANK.
Definition at line 62 of file UNBL.cpp.
References address.
Referenced by operator=().
                                 {
    return address;
}
double UNBL::GetBalance () const [virtual]
Reimplemented from BANK.
Definition at line 70 of file UNBL.cpp.
References balance.
Referenced by operator=(), and toString().
                              {
    return balance;
}
std::shared_ptr< OSTM > UNBL::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object
Parameters:
objTO is a BANK type pointer for casting
obj is a std::shared_ptr<BANK> return type
Reimplemented from OSTM.
Definition at line 21 of file UNBL.cpp.
References UNBL().
Referenced by operator=().
{
    std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
    std::shared_ptr<BANK> obj(new UNBL(objTO,object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
std::string UNBL::GetFirstName () const [virtual]
Reimplemented from BANK.
Definition at line 94 of file UNBL.cpp.
References firstName.
Referenced by operator=(), and toString().
                                   {
    return firstName;
}
std::string UNBL::GetFullname () const [virtual]
Reimplemented from BANK.
Definition at line 102 of file UNBL.cpp.
References fullname.
Referenced by operator=().
                                  {
    return fullname;
}
std::string UNBL::GetLastName () const [virtual]
Reimplemented from BANK.
Definition at line 86 of file UNBL.cpp.
References lastName.
Referenced by operator=(), and toString().
                                  {
    return lastName;
}
UNBL UNBL::operator= (const UNBL & orig) [inline]
Operator
Definition at line 62 of file UNBL.h.
References accountNumber, address, balance, copy(), firstName, fullname, GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), lastName, SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~UNBL().
{};
void UNBL::SetAccountNumber (int accountNumber) [virtual]
Reimplemented from BANK.
Definition at line 74 of file UNBL.cpp.
References accountNumber.
Referenced by operator=().
                                             {
    this->accountNumber = accountNumber;
}
void UNBL::SetAddress (std::string address) [virtual]
Reimplemented from BANK.
Definition at line 58 of file UNBL.cpp.
References address.
Referenced by operator=().
                                       {
    this->address = address;
}
void UNBL::SetBalance (double balance) [virtual]
Reimplemented from BANK.
Definition at line 66 of file UNBL.cpp.
References balance.
Referenced by operator=().
                                    {
    this->balance = balance;
}
void UNBL::SetFirstName (std::string firstName) [virtual]
Reimplemented from BANK.
Definition at line 90 of file UNBL.cpp.
References firstName.
Referenced by operator=().
                                           {
    this->firstName = firstName;
}
void UNBL::SetFullname (std::string fullname) [virtual]
Reimplemented from BANK.
Definition at line 98 of file UNBL.cpp.
References fullname.
Referenced by operator=().
                                         {
    this->fullname = fullname;
}
void UNBL::SetLastName (std::string lastName) [virtual]
Reimplemented from BANK.
Definition at line 82 of file UNBL.cpp.
References lastName.
Referenced by operator=().
                                         {
    this->lastName = lastName;
}
void UNBL::toString () [virtual]
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way
Reimplemented from OSTM.
Definition at line 53 of file UNBL.cpp.
References OSTM::Get_Unique_ID(), OSTM::Get_Version(), GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName().
Referenced by operator=().
{
   std::cout << "\nUNBL BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Member Data Documentation
int UNBL::accountNumber [private]
Definition at line 95 of file UNBL.h.
Referenced by GetAccountNumber(), operator=(), SetAccountNumber(), and UNBL().
std::string UNBL::address [private]
Definition at line 97 of file UNBL.h.
Referenced by GetAddress(), operator=(), SetAddress(), and UNBL().
double UNBL::balance [private]
Definition at line 96 of file UNBL.h.
Referenced by GetBalance(), operator=(), SetBalance(), and UNBL().
std::string UNBL::firstName [private]
Definition at line 93 of file UNBL.h.
Referenced by GetFirstName(), operator=(), SetFirstName(), and UNBL().
std::string UNBL::fullname [private]
Definition at line 92 of file UNBL.h.
Referenced by GetFullname(), operator=(), SetFullname(), and UNBL().
std::string UNBL::lastName [private]
Definition at line 94 of file UNBL.h.
Referenced by GetLastName(), operator=(), SetLastName(), and UNBL().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.