.TH "AIB" 3 "Wed Mar 7 2018" "C++ Softwrae Transactional memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AIB \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AIB\&.h>\fP
.PP
Inherits \fBBANK\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAIB\fP ()"
.br
.ti -1c
.RI "\fBAIB\fP (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)"
.br
.ti -1c
.RI "\fBAIB\fP (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBAIB\fP (const \fBAIB\fP &orig)"
.br
.ti -1c
.RI "\fBAIB\fP \fBoperator=\fP (const \fBAIB\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~AIB\fP ()"
.br
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)"
.br
.RI "\fIcopy function, make deep copy of the object/pointer \fP"
.ti -1c
.RI "virtual std::shared_ptr< \fBOSTM\fP > \fBgetBaseCopy\fP (std::shared_ptr< \fBOSTM\fP > object)"
.br
.RI "\fIgetBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object \fP"
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type \fP"
.ti -1c
.RI "virtual void \fBSetAddress\fP (std::string address)"
.br
.ti -1c
.RI "virtual std::string \fBGetAddress\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetBalance\fP (double balance)"
.br
.ti -1c
.RI "virtual double \fBGetBalance\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetAccountNumber\fP (int accountNumber)"
.br
.ti -1c
.RI "virtual int \fBGetAccountNumber\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetLastName\fP (std::string lastName)"
.br
.ti -1c
.RI "virtual std::string \fBGetLastName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFirstName\fP (std::string firstName)"
.br
.ti -1c
.RI "virtual std::string \fBGetFirstName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFullname\fP (std::string fullname)"
.br
.ti -1c
.RI "virtual std::string \fBGetFullname\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Inherit from \fBBANK\fP 
.PP
Definition at line 18 of file AIB\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AIB::AIB ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 23 of file AIB\&.h\&.
.SS "AIB::AIB (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)\fC [inline]\fP"
Custom constructor 
.PP
Definition at line 36 of file AIB\&.h\&.
.SS "AIB::AIB (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)\fC [inline]\fP"
Custom constructor, used by the library for deep copying 
.PP
Definition at line 48 of file AIB\&.h\&.
.SS "AIB::AIB (const \fBAIB\fP & orig)"
Copy constructor 
.PP
Definition at line 14 of file AIB\&.cpp\&.
.SS "AIB::~AIB ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 17 of file AIB\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void AIB::copy (std::shared_ptr< \fBOSTM\fP > to, std::shared_ptr< \fBOSTM\fP > from)\fC [virtual]\fP"

.PP
copy function, make deep copy of the object/pointer 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.br
\fIobjFROM\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 37 of file AIB\&.cpp\&.
.SS "std::shared_ptr< \fBOSTM\fP > AIB::getBaseCopy (std::shared_ptr< \fBOSTM\fP > object)\fC [virtual]\fP"

.PP
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a \fBBANK\fP type pointer for casting 
.br
\fIobj\fP is a std::shared_ptr<BANK> return type 
.RE
.PP

.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 24 of file AIB\&.cpp\&.
.SS "\fBAIB\fP AIB::operator= (const \fBAIB\fP & orig)\fC [inline]\fP"
Operator 
.PP
Definition at line 66 of file AIB\&.h\&.
.SS "void AIB::toString ()\fC [virtual]\fP"

.PP
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way 
.PP
Reimplemented from \fBOSTM\fP\&.
.PP
Definition at line 56 of file AIB\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Softwrae Transactional memory from the source code\&.
