.TH "CARPHONE_WAREHOUSE.cpp" 3 "Wed Mar 7 2018" "C++ Software Transactional memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CARPHONE_WAREHOUSE.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'CARPHONE_WAREHOUSE\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional memory from the source code\&.
