SLIGO_W
NAME
SLIGO_W -
SYNOPSIS
#include <SLIGO_W.h>
Inherits WAREHOUSE.
Public Member Functions
SLIGO_W ()
SLIGO_W (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)
SLIGO_W (std::shared_ptr< WAREHOUSE > obj, int _version, int _unique_id)
SLIGO_W (const SLIGO_W &orig)
SLIGO_W operator= (const SLIGO_W &orig)
virtual ~SLIGO_W ()
virtual void copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)
copy function, make deep copy of the object/pointer
virtual std::shared_ptr< OSTM > getBaseCopy (std::shared_ptr< OSTM > object)
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object
virtual void toString ()
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type
virtual void SetNumber_of_alcatel (int _number_of_alcatel)
virtual int GetNumber_of_alcatel ()
virtual void SetNumber_of_nokia (int _number_of_nokia)
virtual int GetNumber_of_nokia ()
virtual void SetNumber_of_huawei (int _number_of_huawei)
virtual int GetNumber_of_huawei ()
virtual void SetNumber_of_sony (int _number_of_sony)
virtual int GetNumber_of_sony ()
virtual void SetNumber_of_samsung (int _number_of_samsung)
virtual int GetNumber_of_samsung ()
virtual void SetNumber_of_iphones (int _number_of_iphones)
virtual int GetNumber_of_iphones ()
virtual void SetShop_name (std::string _shop_name)
virtual std::string GetShop_name ()
virtual void SetShop_address (std::string _shop_address)
virtual std::string GetShop_address ()
Detailed Description
Inherit from WAREHOUSE
Definition at line 19 of file SLIGO_W.h.
Constructor & Destructor Documentation
SLIGO_W::SLIGO_W () [inline]
Constructor
Definition at line 24 of file SLIGO_W.h.
Referenced by getBaseCopy(), and SLIGO_W().
              : WAREHOUSE(){
        
        this->_shop_address = "Sligo River Street";
        this->_shop_name = "SLIGO S_WAREHOUSE";
        this->_number_of_iphones = 200;
        this->_number_of_samsung = 200;
        this->_number_of_sony = 200;
        this->_number_of_huawei = 200;
        this->_number_of_nokia = 200;
        this->_number_of_alcatel = 200;
    };
SLIGO_W::SLIGO_W (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel) [inline]
Custom constructor
Definition at line 38 of file SLIGO_W.h.
                                                                                                                          : WAREHOUSE(){
        /*
         * copy over values
         */
        this->_shop_address = address;
        this->_shop_name = shop_name;
        this->_number_of_iphones = iphone;
        this->_number_of_samsung = samsung;
        this->_number_of_sony = sony;
        this->_number_of_huawei = huawei;
        this->_number_of_nokia = nokia;
        this->_number_of_alcatel = alcatel;
        
    };
SLIGO_W::SLIGO_W (std::shared_ptr< WAREHOUSE > obj, int _version, int _unique_id) [inline]
Custom constructor, used by the library for deep copying
Definition at line 55 of file SLIGO_W.h.
References SLIGO_W().
                                                                       : WAREHOUSE(_version, _unique_id){
        /*
         * copy over values
         */
        this->_shop_address = obj->GetShop_address();
        this->_shop_name = obj->GetShop_name();
        this->_number_of_iphones = obj->GetNumber_of_iphones();
        this->_number_of_samsung = obj->GetNumber_of_samsung();
        this->_number_of_sony = obj->GetNumber_of_sony();
        this->_number_of_huawei = obj->GetNumber_of_huawei();
        this->_number_of_nokia = obj->GetNumber_of_nokia();
        this->_number_of_alcatel = obj->GetNumber_of_alcatel();
    }
SLIGO_W::SLIGO_W (const SLIGO_W & orig)
Copy constructor
Definition at line 15 of file SLIGO_W.cpp.
                                    {
}
SLIGO_W::~SLIGO_W () [virtual]
de-constructor
Definition at line 12 of file SLIGO_W.cpp.
Referenced by operator=().
                  {
}
Member Function Documentation
void SLIGO_W::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from) [virtual]
copy function, make deep copy of the object/pointer
Parameters:
objTO is a BANK* type object casted back from std::shared_ptr<OSTM>
objFROM is a BANK* type object casted back from std::shared_ptr<OSTM>
Definition at line 35 of file SLIGO_W.cpp.
Referenced by operator=().
                                                                  {
    std::shared_ptr<SLIGO_W> objTO = std::dynamic_pointer_cast<SLIGO_W>(to);
    std::shared_ptr<SLIGO_W> objFROM = std::dynamic_pointer_cast<SLIGO_W>(from);
    objTO->_shop_address = objFROM->GetShop_address();
    objTO->_shop_name = objFROM->GetShop_name();
    objTO->_number_of_iphones = objFROM->GetNumber_of_iphones();
    objTO->_number_of_samsung = objFROM->GetNumber_of_samsung();
    objTO->_number_of_sony = objFROM->GetNumber_of_sony();
    objTO->_number_of_huawei = objFROM->GetNumber_of_huawei();
    objTO->_number_of_nokia = objFROM->GetNumber_of_nokia();
    objTO->_number_of_alcatel = objFROM->GetNumber_of_alcatel();
    objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
    objTO->Set_Version(objFROM->Get_Version());
    
   
}
std::shared_ptr< OSTM > SLIGO_W::getBaseCopy (std::shared_ptr< OSTM > object) [virtual]
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object
Parameters:
objTO is a BANK type pointer for casting
obj is a BANK* return type
Definition at line 22 of file SLIGO_W.cpp.
References SLIGO_W().
Referenced by operator=().
{
    std::shared_ptr<WAREHOUSE> objTO = std::dynamic_pointer_cast<WAREHOUSE>(object);
    std::shared_ptr<WAREHOUSE> obj(new SLIGO_W(objTO, object->Get_Version(),object->Get_Unique_ID()));
    std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);
    return ostm_obj;
}
int SLIGO_W::GetNumber_of_alcatel () [virtual]
Implements WAREHOUSE.
Definition at line 73 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                                 {
    return _number_of_alcatel;
}
int SLIGO_W::GetNumber_of_huawei () [virtual]
Implements WAREHOUSE.
Definition at line 89 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                                {
    return _number_of_huawei;
}
int SLIGO_W::GetNumber_of_iphones () [virtual]
Implements WAREHOUSE.
Definition at line 113 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                                 {
    return _number_of_iphones;
}
int SLIGO_W::GetNumber_of_nokia () [virtual]
Implements WAREHOUSE.
Definition at line 81 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                               {
    return _number_of_nokia;
}
int SLIGO_W::GetNumber_of_samsung () [virtual]
Implements WAREHOUSE.
Definition at line 105 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                                 {
    return _number_of_samsung;
}
int SLIGO_W::GetNumber_of_sony () [virtual]
Implements WAREHOUSE.
Definition at line 97 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                              {
    return _number_of_sony;
}
std::string SLIGO_W::GetShop_address () [virtual]
Implements WAREHOUSE.
Definition at line 129 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                                  {
    return _shop_address;
}
std::string SLIGO_W::GetShop_name () [virtual]
Implements WAREHOUSE.
Definition at line 121 of file SLIGO_W.cpp.
Referenced by operator=(), and toString().
                               {
    return _shop_name;
}
SLIGO_W SLIGO_W::operator= (const SLIGO_W & orig) [inline]
Operator
Definition at line 75 of file SLIGO_W.h.
References copy(), getBaseCopy(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), GetShop_name(), SetNumber_of_alcatel(), SetNumber_of_huawei(), SetNumber_of_iphones(), SetNumber_of_nokia(), SetNumber_of_samsung(), SetNumber_of_sony(), SetShop_address(), SetShop_name(), toString(), and ~SLIGO_W().
{};
void SLIGO_W::SetNumber_of_alcatel (int _number_of_alcatel) [virtual]
Implements WAREHOUSE.
Definition at line 69 of file SLIGO_W.cpp.
Referenced by operator=().
                                                         {
    this->_number_of_alcatel = _number_of_alcatel;
}
void SLIGO_W::SetNumber_of_huawei (int _number_of_huawei) [virtual]
Implements WAREHOUSE.
Definition at line 85 of file SLIGO_W.cpp.
Referenced by operator=().
                                                       {
    this->_number_of_huawei = _number_of_huawei;
}
void SLIGO_W::SetNumber_of_iphones (int _number_of_iphones) [virtual]
Implements WAREHOUSE.
Definition at line 109 of file SLIGO_W.cpp.
Referenced by operator=().
                                                         {
    this->_number_of_iphones = _number_of_iphones;
}
void SLIGO_W::SetNumber_of_nokia (int _number_of_nokia) [virtual]
Implements WAREHOUSE.
Definition at line 77 of file SLIGO_W.cpp.
Referenced by operator=().
                                                     {
    this->_number_of_nokia = _number_of_nokia;
}
void SLIGO_W::SetNumber_of_samsung (int _number_of_samsung) [virtual]
Implements WAREHOUSE.
Definition at line 101 of file SLIGO_W.cpp.
Referenced by operator=().
                                                         {
    this->_number_of_samsung = _number_of_samsung;
}
void SLIGO_W::SetNumber_of_sony (int _number_of_sony) [virtual]
Implements WAREHOUSE.
Definition at line 93 of file SLIGO_W.cpp.
Referenced by operator=().
                                                   {
    this->_number_of_sony = _number_of_sony;
}
void SLIGO_W::SetShop_address (std::string _shop_address) [virtual]
Implements WAREHOUSE.
Definition at line 125 of file SLIGO_W.cpp.
Referenced by operator=().
                                                     {
    this->_shop_address = _shop_address;
}
void SLIGO_W::SetShop_name (std::string _shop_name) [virtual]
Implements WAREHOUSE.
Definition at line 117 of file SLIGO_W.cpp.
Referenced by operator=().
                                               {
    this->_shop_name = _shop_name;
}
void SLIGO_W::toString () [virtual]
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way
Definition at line 62 of file SLIGO_W.cpp.
References GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), and GetShop_name().
Referenced by operator=().
{
    std::cout << "\n" << this->GetShop_name() << "\nUnique ID : " << this->Get_Unique_ID() << "\nShop Name : " << this->GetShop_name() << "\nShop Address : " << this->GetShop_address() << "\nNo. Iphones : " << this->GetNumber_of_iphones() << "\nNo. Samsung : " << this->GetNumber_of_samsung() << "\nNo. Sony : " << this->GetNumber_of_sony() << "\nNo. Huawei : " << this->GetNumber_of_huawei() << "\nNo. Nokia : " << this->GetNumber_of_nokia() << "\nNo. Alcatel : " << this->GetNumber_of_alcatel() << "\nVersion number : " << this->Get_Version() << std::endl;
}
Author
Generated automatically by Doxygen for C++ Software Transactional memory from the source code.