.TH "TALLAGH_W" 3 "Wed Mar 7 2018" "C++ Software Transactional memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TALLAGH_W \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TALLAGH_W\&.h>\fP
.PP
Inherits \fBWAREHOUSE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTALLAGH_W\fP ()"
.br
.ti -1c
.RI "\fBTALLAGH_W\fP (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)"
.br
.ti -1c
.RI "\fBTALLAGH_W\fP (std::shared_ptr< \fBWAREHOUSE\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBTALLAGH_W\fP (const \fBTALLAGH_W\fP &orig)"
.br
.ti -1c
.RI "\fBTALLAGH_W\fP \fBoperator=\fP (const \fBTALLAGH_W\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~TALLAGH_W\fP ()"
.br
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)"
.br
.RI "\fIcopy function, make deep copy of the object/pointer \fP"
.ti -1c
.RI "virtual std::shared_ptr< OSTM > \fBgetBaseCopy\fP (std::shared_ptr< OSTM > object)"
.br
.RI "\fIgetBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object \fP"
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type \fP"
.ti -1c
.RI "virtual void \fBSetNumber_of_alcatel\fP (int _number_of_alcatel)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_alcatel\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_nokia\fP (int _number_of_nokia)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_nokia\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_huawei\fP (int _number_of_huawei)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_huawei\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_sony\fP (int _number_of_sony)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_sony\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_samsung\fP (int _number_of_samsung)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_samsung\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetNumber_of_iphones\fP (int _number_of_iphones)"
.br
.ti -1c
.RI "virtual int \fBGetNumber_of_iphones\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetShop_name\fP (std::string _shop_name)"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_name\fP ()"
.br
.ti -1c
.RI "virtual void \fBSetShop_address\fP (std::string _shop_address)"
.br
.ti -1c
.RI "virtual std::string \fBGetShop_address\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Inherit from \fBWAREHOUSE\fP 
.PP
Definition at line 19 of file TALLAGH_W\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TALLAGH_W::TALLAGH_W ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 24 of file TALLAGH_W\&.h\&.
.PP
Referenced by getBaseCopy(), and TALLAGH_W()\&.
.PP
.nf
24                 : WAREHOUSE(){
25         
26         this->_shop_address = "Tallagh Low street";
27         this->_shop_name = "TALLAGH T_WAREHOUSE";
28         this->_number_of_iphones = 200;
29         this->_number_of_samsung = 200;
30         this->_number_of_sony = 200;
31         this->_number_of_huawei = 200;
32         this->_number_of_nokia = 200;
33         this->_number_of_alcatel = 200;
34     };
.fi
.SS "TALLAGH_W::TALLAGH_W (std::string address, std::string shop_name, int iphone, int samsung, int sony, int huawei, int nokia, int alcatel)\fC [inline]\fP"
Custom constructor 
.PP
Definition at line 38 of file TALLAGH_W\&.h\&.
.PP
.nf
38                                                                                                                             : WAREHOUSE(){
39         /*
40          * copy over values
41          */
42         this->_shop_address = address;
43         this->_shop_name = shop_name;
44         this->_number_of_iphones = iphone;
45         this->_number_of_samsung = samsung;
46         this->_number_of_sony = sony;
47         this->_number_of_huawei = huawei;
48         this->_number_of_nokia = nokia;
49         this->_number_of_alcatel = alcatel;
50         
51     };
.fi
.SS "TALLAGH_W::TALLAGH_W (std::shared_ptr< \fBWAREHOUSE\fP > obj, int _version, int _unique_id)\fC [inline]\fP"
Custom constructor, used by the library for deep copying 
.PP
Definition at line 55 of file TALLAGH_W\&.h\&.
.PP
References TALLAGH_W()\&.
.PP
.nf
55                                                                          : WAREHOUSE(_version, _unique_id){
56         /*
57          * copy over values
58          */
59         this->_shop_address = obj->GetShop_address();
60         this->_shop_name = obj->GetShop_name();
61         this->_number_of_iphones = obj->GetNumber_of_iphones();
62         this->_number_of_samsung = obj->GetNumber_of_samsung();
63         this->_number_of_sony = obj->GetNumber_of_sony();
64         this->_number_of_huawei = obj->GetNumber_of_huawei();
65         this->_number_of_nokia = obj->GetNumber_of_nokia();
66         this->_number_of_alcatel = obj->GetNumber_of_alcatel();
67     }
.fi
.SS "TALLAGH_W::TALLAGH_W (const \fBTALLAGH_W\fP & orig)"
Copy constructor 
.PP
Definition at line 15 of file TALLAGH_W\&.cpp\&.
.PP
.nf
15                                           {
16 }
.fi
.SS "TALLAGH_W::~TALLAGH_W ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 12 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
12                       {
13 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void TALLAGH_W::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)\fC [virtual]\fP"

.PP
copy function, make deep copy of the object/pointer 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a BANK* type object casted back from std::shared_ptr<OSTM> 
.br
\fIobjFROM\fP is a BANK* type object casted back from std::shared_ptr<OSTM> 
.RE
.PP

.PP
Definition at line 35 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
35                                                                     {
36 
37     std::shared_ptr<TALLAGH_W> objTO = std::dynamic_pointer_cast<TALLAGH_W>(to);
38     std::shared_ptr<TALLAGH_W> objFROM = std::dynamic_pointer_cast<TALLAGH_W>(from);
39     objTO->_shop_address = objFROM->GetShop_address();
40     objTO->_shop_name = objFROM->GetShop_name();
41     objTO->_number_of_iphones = objFROM->GetNumber_of_iphones();
42     objTO->_number_of_samsung = objFROM->GetNumber_of_samsung();
43     objTO->_number_of_sony = objFROM->GetNumber_of_sony();
44     objTO->_number_of_huawei = objFROM->GetNumber_of_huawei();
45     objTO->_number_of_nokia = objFROM->GetNumber_of_nokia();
46     objTO->_number_of_alcatel = objFROM->GetNumber_of_alcatel();
47     objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
48     objTO->Set_Version(objFROM->Get_Version());
49     
50    
51 }
.fi
.SS "std::shared_ptr< OSTM > TALLAGH_W::getBaseCopy (std::shared_ptr< OSTM > object)\fC [virtual]\fP"

.PP
getBaseCopy function, make deep copy of the object/pointer and Return a new BANK* type object 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a \fBBANK\fP type pointer for casting 
.br
\fIobj\fP is a BANK* return type 
.RE
.PP

.PP
Definition at line 22 of file TALLAGH_W\&.cpp\&.
.PP
References TALLAGH_W()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
23 {
24 
25     std::shared_ptr<WAREHOUSE> objTO = std::dynamic_pointer_cast<WAREHOUSE>(object);
26     std::shared_ptr<WAREHOUSE> obj(new TALLAGH_W(objTO, object->Get_Version(),object->Get_Unique_ID()));
27     std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);                                  
28     return ostm_obj;
29 }
.fi
.SS "int TALLAGH_W::GetNumber_of_alcatel ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 71 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
71                                    {
72     return _number_of_alcatel;
73 }
.fi
.SS "int TALLAGH_W::GetNumber_of_huawei ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 87 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
87                                   {
88     return _number_of_huawei;
89 }
.fi
.SS "int TALLAGH_W::GetNumber_of_iphones ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 111 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
111                                    {
112     return _number_of_iphones;
113 }
.fi
.SS "int TALLAGH_W::GetNumber_of_nokia ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 79 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
79                                  {
80     return _number_of_nokia;
81 }
.fi
.SS "int TALLAGH_W::GetNumber_of_samsung ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 103 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
103                                    {
104     return _number_of_samsung;
105 }
.fi
.SS "int TALLAGH_W::GetNumber_of_sony ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 95 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
95                                 {
96     return _number_of_sony;
97 }
.fi
.SS "std::string TALLAGH_W::GetShop_address ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 127 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
127                                     {
128     return _shop_address;
129 }
.fi
.SS "std::string TALLAGH_W::GetShop_name ()\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 119 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
119                                  {
120     return _shop_name;
121 }
.fi
.SS "\fBTALLAGH_W\fP TALLAGH_W::operator= (const \fBTALLAGH_W\fP & orig)\fC [inline]\fP"
Operator 
.PP
Definition at line 75 of file TALLAGH_W\&.h\&.
.PP
References copy(), getBaseCopy(), GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), GetShop_name(), SetNumber_of_alcatel(), SetNumber_of_huawei(), SetNumber_of_iphones(), SetNumber_of_nokia(), SetNumber_of_samsung(), SetNumber_of_sony(), SetShop_address(), SetShop_name(), toString(), and ~TALLAGH_W()\&.
.PP
.nf
75 {};
.fi
.SS "void TALLAGH_W::SetNumber_of_alcatel (int _number_of_alcatel)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 67 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
67                                                            {
68     this->_number_of_alcatel = _number_of_alcatel;
69 }
.fi
.SS "void TALLAGH_W::SetNumber_of_huawei (int _number_of_huawei)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 83 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
83                                                          {
84     this->_number_of_huawei = _number_of_huawei;
85 }
.fi
.SS "void TALLAGH_W::SetNumber_of_iphones (int _number_of_iphones)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 107 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
107                                                            {
108     this->_number_of_iphones = _number_of_iphones;
109 }
.fi
.SS "void TALLAGH_W::SetNumber_of_nokia (int _number_of_nokia)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 75 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
75                                                        {
76     this->_number_of_nokia = _number_of_nokia;
77 }
.fi
.SS "void TALLAGH_W::SetNumber_of_samsung (int _number_of_samsung)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 99 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
99                                                            {
100     this->_number_of_samsung = _number_of_samsung;
101 }
.fi
.SS "void TALLAGH_W::SetNumber_of_sony (int _number_of_sony)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 91 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
91                                                      {
92     this->_number_of_sony = _number_of_sony;
93 }
.fi
.SS "void TALLAGH_W::SetShop_address (std::string _shop_address)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 123 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
123                                                        {
124     this->_shop_address = _shop_address;
125 }
.fi
.SS "void TALLAGH_W::SetShop_name (std::string _shop_name)\fC [virtual]\fP"

.PP
Implements \fBWAREHOUSE\fP\&.
.PP
Definition at line 115 of file TALLAGH_W\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
115                                                  {
116     this->_shop_name = _shop_name;
117 }
.fi
.SS "void TALLAGH_W::toString ()\fC [virtual]\fP"

.PP
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way 
.PP
Definition at line 62 of file TALLAGH_W\&.cpp\&.
.PP
References GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), and GetShop_name()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
63 {
64     std::cout << "\n" << this->GetShop_name() << "\nUnique ID : " << this->Get_Unique_ID() << "\nShop Name : "  << this->GetShop_name() << "\nShop Address : " << this->GetShop_address() << "\nNo\&. Iphones : " << this->GetNumber_of_iphones() << "\nNo\&. Samsung : " << this->GetNumber_of_samsung() << "\nNo\&. Sony : " << this->GetNumber_of_sony() << "\nNo\&. Huawei : " << this->GetNumber_of_huawei() << "\nNo\&. Nokia : " << this->GetNumber_of_nokia() << "\nNo\&. Alcatel : " << this->GetNumber_of_alcatel() << "\nVersion number : " << this->Get_Version() << std::endl;
65 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional memory from the source code\&.
