.TH "ULSTER" 3 "Wed Mar 7 2018" "C++ Software Transactional memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ULSTER \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ULSTER\&.h>\fP
.PP
Inherits \fBBANK\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBULSTER\fP ()"
.br
.ti -1c
.RI "\fBULSTER\fP (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)"
.br
.ti -1c
.RI "\fBULSTER\fP (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)"
.br
.ti -1c
.RI "\fBULSTER\fP (const \fBULSTER\fP &orig)"
.br
.ti -1c
.RI "\fBULSTER\fP \fBoperator=\fP (const \fBULSTER\fP &orig)"
.br
.ti -1c
.RI "virtual \fB~ULSTER\fP ()"
.br
.ti -1c
.RI "virtual void \fBcopy\fP (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)"
.br
.RI "\fIcopy function, make deep copy of the object/pointer \fP"
.ti -1c
.RI "virtual std::shared_ptr< OSTM > \fBgetBaseCopy\fP (std::shared_ptr< OSTM > object)"
.br
.RI "\fIgetBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object \fP"
.ti -1c
.RI "virtual void \fBtoString\fP ()"
.br
.RI "\fI_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type \fP"
.ti -1c
.RI "virtual void \fBSetAddress\fP (std::string address)"
.br
.ti -1c
.RI "virtual std::string \fBGetAddress\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetBalance\fP (double balance)"
.br
.ti -1c
.RI "virtual double \fBGetBalance\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetAccountNumber\fP (int accountNumber)"
.br
.ti -1c
.RI "virtual int \fBGetAccountNumber\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetLastName\fP (std::string lastName)"
.br
.ti -1c
.RI "virtual std::string \fBGetLastName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFirstName\fP (std::string firstName)"
.br
.ti -1c
.RI "virtual std::string \fBGetFirstName\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetFullname\fP (std::string fullname)"
.br
.ti -1c
.RI "virtual std::string \fBGetFullname\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Inherit from \fBBANK\fP 
.PP
Definition at line 19 of file ULSTER\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ULSTER::ULSTER ()\fC [inline]\fP"
Constructor 
.PP
Definition at line 24 of file ULSTER\&.h\&.
.PP
Referenced by getBaseCopy(), and ULSTER()\&.
.PP
.nf
24              : BANK() {
25         this->accountNumber = 0;
26         this->balance = 50;
27         this->firstName = "Joe";
28         this->lastName = "Blog";
29         this->address = "High street, Carlow";
30         this->fullname = firstName + " " + lastName;
31     };
.fi
.SS "ULSTER::ULSTER (int accountNumber, double balance, std::string firstName, std::string lastName, std::string address)\fC [inline]\fP"
Custom constructor 
.PP
Definition at line 35 of file ULSTER\&.h\&.
.PP
.nf
35                                                                                                           : BANK() {
36         this->accountNumber = accountNumber;
37         this->balance = balance;
38         this->firstName = firstName;
39         this->lastName = lastName;
40         this->address = address;
41         this->fullname = firstName + " " + lastName;
42     };
.fi
.SS "ULSTER::ULSTER (std::shared_ptr< \fBBANK\fP > obj, int _version, int _unique_id)\fC [inline]\fP"
Custom constructor, used by the library for deep copying 
.PP
Definition at line 46 of file ULSTER\&.h\&.
.PP
References ULSTER()\&.
.PP
.nf
46                                                                   : BANK(_version, _unique_id) {
47 
48         this->accountNumber = obj->GetAccountNumber();
49         this->balance = obj->GetBalance();
50         this->firstName = obj->GetFirstName();
51         this->lastName = obj->GetLastName();
52         this->address = obj->GetAddress();
53         this->fullname = obj->GetFirstName() + " " + obj->GetLastName(); 
54     };
.fi
.SS "ULSTER::ULSTER (const \fBULSTER\fP & orig)"
Copy constructor 
.PP
Definition at line 15 of file ULSTER\&.cpp\&.
.PP
.nf
15                                  {
16 }
.fi
.SS "ULSTER::~ULSTER ()\fC [virtual]\fP"
de-constructor 
.PP
Definition at line 18 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
18                 {
19 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ULSTER::copy (std::shared_ptr< OSTM > to, std::shared_ptr< OSTM > from)\fC [virtual]\fP"

.PP
copy function, make deep copy of the object/pointer 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.br
\fIobjFROM\fP is a std::shared_ptr<BANK> type object casted back from std::shared_ptr<OSTM> 
.RE
.PP

.PP
Definition at line 37 of file ULSTER\&.cpp\&.
.PP
References SetAccountNumber()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
37                                                                  {
38 
39     std::shared_ptr<ULSTER> objTO = std::dynamic_pointer_cast<ULSTER>(to);
40     std::shared_ptr<ULSTER> objFROM = std::dynamic_pointer_cast<ULSTER>(from);
41     objTO->Set_Unique_ID(objFROM->Get_Unique_ID());
42     objTO->Set_Version(objFROM->Get_Version());
43     objTO->SetAccountNumber(objFROM->GetAccountNumber());
44     objTO->SetBalance(objFROM->GetBalance());
45 
46     
47 }
.fi
.SS "int ULSTER::GetAccountNumber () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 83 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
83                                    {
84     return accountNumber;
85 }
.fi
.SS "std::string ULSTER::GetAddress () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 67 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
67                                    {
68     return address;
69 }
.fi
.SS "double ULSTER::GetBalance () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 75 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
75                                 {
76     return balance;
77 }
.fi
.SS "std::shared_ptr< OSTM > ULSTER::getBaseCopy (std::shared_ptr< OSTM > object)\fC [virtual]\fP"

.PP
getBaseCopy function, make deep copy of the object/pointer and Return a new std::shared_ptr<BANK> type object 
.PP
\fBParameters:\fP
.RS 4
\fIobjTO\fP is a \fBBANK\fP type pointer for casting 
.br
\fIobj\fP is a std::shared_ptr<BANK> return type 
.RE
.PP

.PP
Definition at line 25 of file ULSTER\&.cpp\&.
.PP
References ULSTER()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
26 {
27     std::shared_ptr<BANK> objTO = std::dynamic_pointer_cast<BANK>(object);
28     std::shared_ptr<BANK> obj(new ULSTER(objTO,object->Get_Version(),object->Get_Unique_ID())); 
29     std::shared_ptr<OSTM> ostm_obj = std::dynamic_pointer_cast<OSTM>(obj);                                  
30     return ostm_obj;
31 }
.fi
.SS "std::string ULSTER::GetFirstName () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 99 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
99                                      {
100     return firstName;
101 }
.fi
.SS "std::string ULSTER::GetFullname () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 107 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
107                                     {
108     return fullname;
109 }
.fi
.SS "std::string ULSTER::GetLastName () const\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 91 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=(), and toString()\&.
.PP
.nf
91                                     {
92     return lastName;
93 }
.fi
.SS "\fBULSTER\fP ULSTER::operator= (const \fBULSTER\fP & orig)\fC [inline]\fP"
Operator 
.PP
Definition at line 62 of file ULSTER\&.h\&.
.PP
References copy(), GetAccountNumber(), GetAddress(), GetBalance(), getBaseCopy(), GetFirstName(), GetFullname(), GetLastName(), SetAccountNumber(), SetAddress(), SetBalance(), SetFirstName(), SetFullname(), SetLastName(), toString(), and ~ULSTER()\&.
.PP
.nf
62 {};
.fi
.SS "void ULSTER::SetAccountNumber (int accountNumber)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 79 of file ULSTER\&.cpp\&.
.PP
Referenced by copy(), and operator=()\&.
.PP
.nf
79                                                {
80     this->accountNumber = accountNumber;
81 }
.fi
.SS "void ULSTER::SetAddress (std::string address)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 63 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
63                                          {
64     this->address = address;
65 }
.fi
.SS "void ULSTER::SetBalance (double balance)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 71 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
71                                       {
72     this->balance = balance;
73 }
.fi
.SS "void ULSTER::SetFirstName (std::string firstName)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 95 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
95                                              {
96     this->firstName = firstName;
97 }
.fi
.SS "void ULSTER::SetFullname (std::string fullname)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 103 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
103                                            {
104     this->fullname = fullname;
105 }
.fi
.SS "void ULSTER::SetLastName (std::string lastName)\fC [virtual]\fP"

.PP
Implements \fBBANK\fP\&.
.PP
Definition at line 87 of file ULSTER\&.cpp\&.
.PP
Referenced by operator=()\&.
.PP
.nf
87                                            {
88     this->lastName = lastName;
89 }
.fi
.SS "void ULSTER::toString ()\fC [virtual]\fP"

.PP
_cast, is use to cast bak the std::shared_ptr<OSTM> to the required type toString function, displays the object values in formatted way 
.PP
Definition at line 58 of file ULSTER\&.cpp\&.
.PP
References GetAccountNumber(), GetBalance(), GetFirstName(), and GetLastName()\&.
.PP
Referenced by operator=()\&.
.PP
.nf
59 {
60    std::cout << "\nULSTER BANK" << "\nUnique ID : " << this->Get_Unique_ID() << "\nInt account : " << this->GetAccountNumber() << "\nDouble value : " << this->GetBalance() << "\nFirst name: " << this->GetFirstName() << "\nLast name : " << this->GetLastName()  << "\nVersion number : " << this->Get_Version() << std::endl;
61 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software Transactional memory from the source code\&.
