WAREHOUSE
NAME
WAREHOUSE -
SYNOPSIS
#include <WAREHOUSE.h>
Inherits OSTM.
Inherited by CARLOW_W, CARPHONE_WAREHOUSE, DUNDALK_W, KILKENNY_W, SLIGO_W, and TALLAGH_W.
Public Member Functions
WAREHOUSE ()
WAREHOUSE (int _version, int _unique_id)
WAREHOUSE (const WAREHOUSE &orig)
virtual ~WAREHOUSE ()
virtual void SetNumber_of_alcatel (int _number_of_alcatel)=0
virtual int GetNumber_of_alcatel ()=0
virtual void SetNumber_of_nokia (int _number_of_nokia)=0
virtual int GetNumber_of_nokia ()=0
virtual void SetNumber_of_huawei (int _number_of_huawei)=0
virtual int GetNumber_of_huawei ()=0
virtual void SetNumber_of_sony (int _number_of_sony)=0
virtual int GetNumber_of_sony ()=0
virtual void SetNumber_of_samsung (int _number_of_samsung)=0
virtual int GetNumber_of_samsung ()=0
virtual void SetNumber_of_iphones (int _number_of_iphones)=0
virtual int GetNumber_of_iphones ()=0
virtual void SetShop_name (std::string _shop_name)=0
virtual std::string GetShop_name ()=0
virtual void SetShop_address (std::string _shop_address)=0
virtual std::string GetShop_address ()=0
Detailed Description
WAREHOUSE inherit from OSTM library
Definition at line 16 of file WAREHOUSE.h.
Constructor & Destructor Documentation
WAREHOUSE::WAREHOUSE () [inline]
Constructor
Definition at line 21 of file WAREHOUSE.h.
Referenced by WAREHOUSE().
               :OSTM(){
        
    };
WAREHOUSE::WAREHOUSE (int _version, int _unique_id) [inline]
Custom Constructor
Definition at line 27 of file WAREHOUSE.h.
References GetNumber_of_alcatel(), GetNumber_of_huawei(), GetNumber_of_iphones(), GetNumber_of_nokia(), GetNumber_of_samsung(), GetNumber_of_sony(), GetShop_address(), GetShop_name(), SetNumber_of_alcatel(), SetNumber_of_huawei(), SetNumber_of_iphones(), SetNumber_of_nokia(), SetNumber_of_samsung(), SetNumber_of_sony(), SetShop_address(), SetShop_name(), WAREHOUSE(), and ~WAREHOUSE().
                                            : OSTM(_version, _unique_id){
        
    };
WAREHOUSE::WAREHOUSE (const WAREHOUSE & orig)
Copy constructor
Definition at line 12 of file WAREHOUSE.cpp.
                                          {
}
WAREHOUSE::~WAREHOUSE () [virtual]
de-constructor
Definition at line 15 of file WAREHOUSE.cpp.
Referenced by WAREHOUSE().
                      {
}
Member Function Documentation
virtual int WAREHOUSE::GetNumber_of_alcatel () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual int WAREHOUSE::GetNumber_of_huawei () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual int WAREHOUSE::GetNumber_of_iphones () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual int WAREHOUSE::GetNumber_of_nokia () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual int WAREHOUSE::GetNumber_of_samsung () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual int WAREHOUSE::GetNumber_of_sony () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual std::string WAREHOUSE::GetShop_address () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual std::string WAREHOUSE::GetShop_name () [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_alcatel (int _number_of_alcatel) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_huawei (int _number_of_huawei) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_iphones (int _number_of_iphones) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_nokia (int _number_of_nokia) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by _complex_warehouse_transfer_(), _nested_warehouse_transfer_(), _warehouse_transfer_(), and WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_samsung (int _number_of_samsung) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetNumber_of_sony (int _number_of_sony) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetShop_address (std::string _shop_address) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
virtual void WAREHOUSE::SetShop_name (std::string _shop_name) [pure virtual]
Implemented in CARPHONE_WAREHOUSE, SLIGO_W, TALLAGH_W, CARLOW_W, DUNDALK_W, and KILKENNY_W.
Referenced by WAREHOUSE().
Author
Generated automatically by Doxygen for C++ Software Transactional memory from the source code.