.TH "/media/zoltan/Data/00_2018_ITCarlow/00_Modules/06_Project/Documents/Git_Sync/Linux/OSTM/OSTM.cpp" 3 "Wed Mar 7 2018" "C++ Software transactional Memory" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/zoltan/Data/00_2018_ITCarlow/00_Modules/06_Project/Documents/Git_Sync/Linux/OSTM/OSTM.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OSTM\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for C++ Software transactional Memory from the source code\&.
