TM
NAME
TM -
SYNOPSIS
#include <TM.h>
Public Member Functions
std::shared_ptr< TX > const _get_tx ()
@81 _get_tx std::shared_ptr<TX>, return an trtansaction Object as a shared_ptr, if TX not exists then create and register.# If the transaction Object exists then increasing the nesting level within the Transaction Object.
void _TX_EXIT ()
@108 _TX_EXIT void, when the thread calls the ostm_exit function in the transaction, and it will clear all elements from the shared global collection associated with the main process
void print_all ()
@132 ONLY FOR TESTING print_all void function , print out all object key from txMAP collection associated with the main process.
Static Public Member Functions
static TM & Instance ()
@31 Instance TM, Scott Meyer's Singleton creation, thread safe Transaction Manager instance creation.
Private Member Functions
std::map< std::thread::id, int > get_thread_Map ()
@148 get_thread_Map std::map, returning a map to store all unique ID from all objects from all transactions within the main processes
TM & operator= (const TM &)=delete
TM copy operator, prevent from copying the Transaction Manager.
void registerTX ()
@45 registerTX void function, register a new TX Transaction object into ythe txMap/Transaction Map to manage all the transactions within the shared library. TM Transaction managger checking the Process ID existence in the process map collection, If not in the map then register.
TM ()=default
TM (const TM &)=delete
TM copy constructor, prevent from copying the Transaction Manager.
~TM ()=default
Private Attributes
std::mutex get_Lock
std::mutex register_Lock
std::map< std::thread::id, std::shared_ptr< TX > > txMap
Static Private Attributes
static pid_t _tm_id
static std::map< pid_t, std::map< std::thread::id, int > > process_map_collection
Detailed Description
Definition at line 70 of file TM.h.
Constructor & Destructor Documentation
TM::TM () [private], [default]
TM::~TM () [private], [default]
TM::TM (const TM &) [private], [delete]
TM copy constructor, prevent from copying the Transaction Manager.
Member Function Documentation
std::shared_ptr< TX > const TM::_get_tx ()
@81 _get_tx std::shared_ptr<TX>, return an trtansaction Object as a shared_ptr, if TX not exists then create and register.# If the transaction Object exists then increasing the nesting level within the Transaction Object. _get_tx std::shared_ptr<TX>, returning a shared pointer transaction object
Definition at line 81 of file TM.cpp.
References get_Lock, registerTX(), and txMap.
{
   
    /* @85 guard std::lock_guard, locks the get_Lock mutex, unlock automatically when goes out of the scope get_Lock std::mutex, used by the lock_guard to protect txMap from race conditions */
    std::lock_guard<std::mutex> guard(get_Lock);
    /* @87 txMap try to find the TX Transaction object by it's actual thread ID if registred in the txMap */
    std::map<std::thread::id, std::shared_ptr<TX>>::iterator it = txMap.find(std::this_thread::get_id());
    /* @89 Check if iterator pointing to the end of the txMap then insert */
    if(it == txMap.end())
    {
      /* @92 If cannot find then call the register function to register the thread with a transaction */
       registerTX();
       /* @94 If it's registered first time then we need to find it after registration */
       it = txMap.find(std::this_thread::get_id());
       
    } else {
        /* @98 If transaction already registered, it means the thread participating in nested transactions, and increase the nesting */
        it->second->_increase_tx_nesting();
    }
    /* @101 Returning back the transaction (TX) object to the thread */
    return it->second;
}
void TM::_TX_EXIT ()
@108 _TX_EXIT void, when the thread calls the ostm_exit function in the transaction, and it will clear all elements from the shared global collection associated with the main process _TX_EXIT void function, the thread (TX object) calls the ostm_exit function from the transaction, and clear all elements from the shared global collection associated with the main process
Definition at line 108 of file TM.cpp.
References TX::ostm_exit(), process_map_collection, and txMap.
                 {
    /* @110 Transaction manger create a local Transaction Object to access the TX class function without nesting any transaction */
    TX tx(std::this_thread::get_id());
    /* @112 getppid() return the actual main process thread id, I used it to associate the Transactionas with the main processes */
    pid_t ppid = getppid();
    /* @114 process_map_collection try to find the main process by it's ppid if registred in the library */
    std::map<pid_t, std::map< std::thread::id, int >>::iterator process_map_collection_Iterator = TM::process_map_collection.find(ppid);
    /* @116 Check if iterator NOT pointing to the end of the process map then register */
    if (process_map_collection_Iterator != TM::process_map_collection.end()) {
        /* @118 Iterate through the process_map_collection to find all transaction associated with main process */
        for (auto current = process_map_collection_Iterator->second.begin(); current != process_map_collection_Iterator->second.end(); ++current) {
            /* @120 Delete all transaction associated with the actual main process */
            txMap.erase(current->first);
        }
        /* @123 When all transaction deleted, delete the main process from the Transacion Manager */
        TM::process_map_collection.erase(ppid);
    }
    /* @126 TX class delete all Global Object shared between the transaction. This function calls only when the main process exists to clear out memory */
    tx.ostm_exit();
}
std::map< std::thread::id, int > TM::get_thread_Map () [private]
@148 get_thread_Map std::map, returning a map to store all unique ID from all objects from all transactions within the main processes
Definition at line 148 of file TM.cpp.
Referenced by registerTX().
                                              {
    /* @150 thread_Map std::map< int, int > create a map to store int key and int value */
    std::map< std::thread::id, int > thread_Map;
    /* @152 return the map */
    return thread_Map;
}
TM & TM::Instance () [static]
@31 Instance TM, Scott Meyer's Singleton creation, thread safe Transaction Manager instance creation. Scott Meyer's Singleton creation, thread safe Transaction Manager instance creation.
Definition at line 31 of file TM.cpp.
References _tm_id.
                 {
   /* @33 _instance TM, static class reference to the instance of the Transaction Manager class */
    static TM _instance;
    /* @35 _instance ppid, assigning the process id whoever created the Singleton instance */
    _instance._tm_id = getpid();
    /* @37 return Singleton instance */
    return _instance;
}
TM& TM::operator= (const TM &) [private], [delete]
TM copy operator, prevent from copying the Transaction Manager.
void TM::print_all ()
@132 ONLY FOR TESTING print_all void function , print out all object key from txMAP collection associated with the main process. ONLY FOR TESTING! print_all void function, prints all object in the txMap
Definition at line 132 of file TM.cpp.
References get_Lock, and txMap.
                  {
    /* @134 Locking the print function */
    get_Lock.lock();
    /* @136 Iterate through the txMap to print out the thread id's*/
    for (auto current = txMap.begin(); current != txMap.end(); ++current) {
        /* @138 Print key (thread number)*/
        std::cout << "KEY : " << current->first << std::endl;
    }
    /* @140 Unlocking the print function*/
    get_Lock.unlock();
}
void TM::registerTX () [private]
@45 registerTX void function, register a new TX Transaction object into ythe txMap/Transaction Map to manage all the transactions within the shared library. TM Transaction managger checking the Process ID existence in the process map collection, If not in the map then register.
Definition at line 45 of file TM.cpp.
References get_thread_Map(), process_map_collection, register_Lock, and txMap.
Referenced by _get_tx().
{
  /* @49 guard std::lock_guard, locks the register_Lock mutex, unlock automatically when goes out of the scope register_Lock std::mutex, used by the lock_guard to protect shared map from race conditions */
    std::lock_guard<std::mutex> guard(register_Lock);
    /* @51 getppid() return the actual main process thread id, I used it to associate the Transactionas with the main processes */
    pid_t ppid = getppid();
    /* @53 process_map_collection try to find the main process by it's ppid if registred in the library */
    std::map<pid_t, std::map< std::thread::id, int >>::iterator process_map_collection_Iterator = TM::process_map_collection.find(ppid);
    /* @55 Check if iterator pointing to the end of the process map then register */
    if (process_map_collection_Iterator == TM::process_map_collection.end()) {
        /* @57 Require new map to insert to the process map as a value by the ppid key */
        std::map< std::thread::id, int >map = get_thread_Map();
        /* @59 Register main process/application to the global map */
        TM::process_map_collection.insert({ppid, map});
    }
    /* @63 txMap std::map, collection to store all transaction created by the Transaction Manager */
    std::map<std::thread::id, std::shared_ptr < TX>>::iterator it = txMap.find(std::this_thread::get_id());
    /* @65 Check if iterator pointing to the end of the txMap then insert */
    if (it == txMap.end()) {
        /* @67 Create a new Transaction Object as a shared pointer */
        std::shared_ptr<TX> _transaction_object(new TX(std::this_thread::get_id()));
        /* @69 txMap insert the new transaction into the txMap by the threadID key */
        txMap.insert({std::this_thread::get_id(), _transaction_object});
        /* @71 Get the map if the transaction registered first time */
        process_map_collection_Iterator = TM::process_map_collection.find(ppid);
        /* @73 Insert to the GLOBAL MAP as a helper to clean up at end of main process. The value 1 is not used yet */
        process_map_collection_Iterator->second.insert({std::this_thread::get_id(), 1});
    }
}
Member Data Documentation
pid_t TM::_tm_id [static], [private]
Definition at line 115 of file TM.h.
Referenced by Instance().
std::mutex TM::get_Lock [private]
Definition at line 111 of file TM.h.
Referenced by _get_tx(), and print_all().
std::map< pid_t, std::map< std::thread::id, int > > TM::process_map_collection [static], [private]
Definition at line 95 of file TM.h.
Referenced by _TX_EXIT(), and registerTX().
std::mutex TM::register_Lock [private]
Definition at line 107 of file TM.h.
Referenced by registerTX().
std::map<std::thread::id, std::shared_ptr<TX> > TM::txMap [private]
Definition at line 91 of file TM.h.
Referenced by _get_tx(), _TX_EXIT(), print_all(), and registerTX().
Author
Generated automatically by Doxygen for C++ Software transactional Memory from the source code.